import type { Capability, PlatformActor, TenantResource } from "../../../packages/contracts/src/platform";
import type { CRMActivity, CRMEntityLink, ConvertLeadInput, CreateLeadInput } from "../../../packages/contracts/src/crm";
import { getChatStore } from "../../../packages/database/src/chat-store";
import { getCRMStore } from "../../../packages/database/src/crm-store";
import { getWorkStore } from "../../../packages/database/src/work-store";
import { can, requireCapability } from "../../permissions/src/authorization";
import * as workService from "../../work/src/work-service";

const tko_resource=(actor:PlatformActor,type:string,id:string):TenantResource=>({tenantId:actor.tenantId,type,id,visibility:"internal"});
const tko_require=(actor:PlatformActor,capability:Capability,type:string,id:string)=>requireCapability(actor,capability,tko_resource(actor,type,id));
async function tko_requireSourceEntity(actor:PlatformActor,type:CRMEntityLink["sourceType"],id:string):Promise<void>{const store=getCRMStore();const exists=type==="lead"?Boolean(await store.getLead(actor.tenantId,id)):type==="company"?Boolean(await store.getCompany(actor.tenantId,id)):type==="contact"?(await store.listContacts(actor.tenantId)).some(item=>item.id===id):Boolean(await store.getDeal(actor.tenantId,id));if(!exists)throw new Error("CRM_ENTITY_NOT_FOUND");}

export async function overview(actor:PlatformActor){tko_require(actor,"crm.read","crm","overview");const store=getCRMStore();return {leads:await store.listLeads(actor.tenantId),companies:await store.listCompanies(actor.tenantId),pipelines:await store.listPipelines(actor.tenantId)};}
export async function createLead(input:CreateLeadInput){tko_require(input.actor,"crm.lead.manage","crm_lead","new");return getCRMStore().createLead(input);}
export async function lead(actor:PlatformActor,id:string){const item=await getCRMStore().getLead(actor.tenantId,id);if(!item)throw new Error("CRM_LEAD_NOT_FOUND");tko_require(actor,"crm.read","crm_lead",id);return {lead:item,activities:await getCRMStore().listActivities(actor.tenantId,"lead",id),links:await getCRMStore().listLinks(actor.tenantId,"lead",id)};}
export async function createCompany(actor:PlatformActor,input:Parameters<ReturnType<typeof getCRMStore>["createCompany"]>[1]){tko_require(actor,"crm.company.manage","crm_company","new");return getCRMStore().createCompany(actor,input);}
export async function createContact(actor:PlatformActor,input:Parameters<ReturnType<typeof getCRMStore>["createContact"]>[1]){tko_require(actor,"crm.contact.manage","crm_contact","new");return getCRMStore().createContact(actor,input);}
export async function createPipeline(actor:PlatformActor,input:Parameters<ReturnType<typeof getCRMStore>["createPipeline"]>[1]){tko_require(actor,"crm.pipeline.manage","crm_pipeline","new");return getCRMStore().createPipeline(actor,input);}
export async function board(actor:PlatformActor,pipelineId:string){tko_require(actor,"crm.read","crm_pipeline",pipelineId);return getCRMStore().dealBoard(actor.tenantId,pipelineId);}
export async function dealDetails(actor:PlatformActor,dealId:string){const store=getCRMStore();const deal=await store.getDeal(actor.tenantId,dealId);if(!deal)throw new Error("CRM_DEAL_NOT_FOUND");tko_require(actor,"crm.read","crm_deal",dealId);const handoff=await store.getDealHandoff(actor.tenantId,dealId);const project=handoff?.deliveryProjectId?await getWorkStore().getProject(actor.tenantId,handoff.deliveryProjectId):null;const channel=handoff?.deliveryChannelId?await getChatStore().getChannel(actor.tenantId,handoff.deliveryChannelId):null;const deliveryProject=project&&can(actor,"work.project.read",project).allowed?{id:project.id,name:project.name,key:project.key}:null;const deliveryChannel=channel&&can(actor,"chat.channel.read",channel).allowed?{id:channel.id,name:channel.name}:null;return {deal,handoff,deliveryProject,deliveryChannel};}
export async function createDeal(actor:PlatformActor,input:Parameters<ReturnType<typeof getCRMStore>["createDeal"]>[1]){tko_require(actor,"crm.deal.manage","crm_deal","new");return getCRMStore().createDeal(actor,input);}
export async function moveDeal(actor:PlatformActor,input:Parameters<ReturnType<typeof getCRMStore>["moveDeal"]>[1]){tko_require(actor,"crm.deal.manage","crm_deal",input.dealId);return getCRMStore().moveDeal(actor,input);}
export async function requestDealHandoff(actor:PlatformActor,input:{dealId:string;correlationId:string}){tko_require(actor,"crm.deal.handoff","crm_deal",input.dealId);return getCRMStore().ensureDealHandoff(actor,input);}
export async function completeDealHandoff(actor:PlatformActor,input:{dealId:string;deliveryProjectId:string;deliveryChannelId:string;correlationId:string}){tko_require(actor,"crm.deal.handoff","crm_deal",input.dealId);return getCRMStore().completeDealHandoff(actor,input);}
export async function addActivity(actor:PlatformActor,input:Parameters<ReturnType<typeof getCRMStore>["addActivity"]>[1]){tko_require(actor,"crm.activity.manage","crm_activity","new");return getCRMStore().addActivity(actor,input);}
export async function convertLead(input:ConvertLeadInput){tko_require(input.actor,"crm.lead.convert","crm_lead",input.leadId);return getCRMStore().convertLead(input);}
export async function createFollowUp(actor:PlatformActor,input:{entityType:CRMEntityLink["sourceType"];entityId:string;projectId:string;title:string;dueAt?:Date|null;assigneeMemberIds?:string[];correlationId:string}){tko_require(actor,"crm.follow_up.create","crm_follow_up",input.entityId);await tko_requireSourceEntity(actor,input.entityType,input.entityId);const item=await workService.createWorkItem({actor,projectId:input.projectId,title:input.title,dueAt:input.dueAt??null,assigneeMemberIds:input.assigneeMemberIds?.length?input.assigneeMemberIds:undefined,correlationId:input.correlationId});const link=await getCRMStore().linkEntity(actor,{sourceType:input.entityType,sourceId:input.entityId,targetType:"work_item",targetId:item.id,relationType:"follow_up",correlationId:input.correlationId});await getCRMStore().addActivity(actor,{entityType:input.entityType,entityId:input.entityId,activityType:"linked_work_event",subject:`Follow-up ${item.key}`,metadata:{workItemId:item.id},correlationId:input.correlationId});return {item,link};}
export async function link(actor:PlatformActor,input:Parameters<ReturnType<typeof getCRMStore>["linkEntity"]>[1]){tko_require(actor,"crm.read","crm_link",input.sourceId);await tko_requireSourceEntity(actor,input.sourceType,input.sourceId);return getCRMStore().linkEntity(actor,input);}

// M3 CRM UI extras -------------------------------------------------------------
export async function companies(actor:PlatformActor){tko_require(actor,"crm.read","crm","companies");return getCRMStore().listCompanies(actor.tenantId);}
export async function contacts(actor:PlatformActor,companyId?:string){tko_require(actor,"crm.read","crm","contacts");return getCRMStore().listContacts(actor.tenantId,companyId);}
export async function stages(actor:PlatformActor,pipelineId:string){tko_require(actor,"crm.read","crm_pipeline",pipelineId);return getCRMStore().listStages(actor.tenantId,pipelineId);}
export async function company(actor:PlatformActor,companyId:string){const store=getCRMStore();const company=await store.getCompany(actor.tenantId,companyId);if(!company)throw new Error("CRM_COMPANY_NOT_FOUND");tko_require(actor,"crm.read","crm_company",companyId);const [contacts,deals,activities,links]=await Promise.all([store.listContacts(actor.tenantId,companyId),store.listDeals(actor.tenantId,undefined,companyId),store.listActivities(actor.tenantId,"company",companyId),store.listLinks(actor.tenantId,"company",companyId)]);return {company,contacts,deals,activities,links};}
export async function contact(actor:PlatformActor,contactId:string){const store=getCRMStore();const found=(await store.listContacts(actor.tenantId)).find(item=>item.id===contactId);if(!found)throw new Error("CRM_CONTACT_NOT_FOUND");tko_require(actor,"crm.read","crm_contact",contactId);return {contact:found,activities:await store.listActivities(actor.tenantId,"contact",contactId),links:await store.listLinks(actor.tenantId,"contact",contactId)};}
export async function entityActivities(actor:PlatformActor,entityType:CRMActivity["entityType"],entityId:string){await tko_requireSourceEntity(actor,entityType,entityId);tko_require(actor,"crm.read","crm_activity",entityId);return getCRMStore().listActivities(actor.tenantId,entityType,entityId);}
export async function entityLinks(actor:PlatformActor,sourceType:CRMActivity["entityType"],sourceId:string){await tko_requireSourceEntity(actor,sourceType,sourceId);tko_require(actor,"crm.read","crm_link",sourceId);return getCRMStore().listLinks(actor.tenantId,sourceType,sourceId);}
export async function updateLead(actor:PlatformActor,input:Parameters<ReturnType<typeof getCRMStore>["updateLead"]>[1]){tko_require(actor,"crm.lead.manage","crm_lead",input.leadId);return getCRMStore().updateLead(actor,input);}
export async function updateCompany(actor:PlatformActor,input:Parameters<ReturnType<typeof getCRMStore>["updateCompany"]>[1]){tko_require(actor,"crm.company.manage","crm_company",input.companyId);return getCRMStore().updateCompany(actor,input);}
export async function updateContact(actor:PlatformActor,input:Parameters<ReturnType<typeof getCRMStore>["updateContact"]>[1]){tko_require(actor,"crm.contact.manage","crm_contact",input.contactId);return getCRMStore().updateContact(actor,input);}
