import { useState } from "react";
import { Bot, CheckCircle2, FileText, Play, Plus, Send, ShieldCheck, Sparkles, WandSparkles } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const tko_kinds = ["work_item", "project", "channel", "message", "lead", "deal", "document", "form"] as const;
type TkoContextReference = { kind: (typeof tko_kinds)[number]; id: string };
type TkoCitation = { kind: string; id: string; label: string; locator: string };
const tko_statusTone = (tko_status: string) => tko_status === "executed" || tko_status === "completed" ? "bg-[#ecfdf3] text-[#027a48]" : tko_status === "failed" || tko_status === "expired" ? "bg-[#fef3f2] text-[#b42318]" : tko_status === "confirmed" ? "bg-[#eef4ff] text-[#175cd3]" : "bg-[#f4f3ff] text-[#5b51e8]";

export default function AI() {
  const tko_utils = trpc.useUtils();
  const tko_runs = trpc.ai.runs.useQuery(undefined, { retry: false });
  const tko_proposals = trpc.ai.proposals.useQuery(undefined, { retry: false });
  const [tko_prompt, tko_setPrompt] = useState("");
  const [tko_result, tko_setResult] = useState<string | null>(null);
  const [tko_citations, tko_setCitations] = useState<TkoCitation[]>([]);
  const [tko_context, tko_setContext] = useState<TkoContextReference[]>([]);
  const [tko_contextKind, tko_setContextKind] = useState<TkoContextReference["kind"]>("work_item");
  const [tko_contextId, tko_setContextId] = useState("");
  const tko_refresh = () => { void tko_utils.ai.runs.invalidate(); void tko_utils.ai.proposals.invalidate(); };
  const tko_read = trpc.ai.read.useMutation({ onSuccess: tko_value => { tko_setResult(tko_value.run.output ?? "No answer was returned."); tko_setCitations(tko_value.citations); tko_refresh(); }, onError: tko_error => toast.error(tko_error.message) });
  const tko_draft = trpc.ai.draft.useMutation({ onSuccess: tko_value => { tko_setResult(tko_value.run.output ?? "No draft was returned."); tko_setCitations(tko_value.citations); tko_refresh(); }, onError: tko_error => toast.error(tko_error.message) });
  const tko_confirm = trpc.ai.confirm.useMutation({ onSuccess: () => { toast.success("Proposal confirmed. Review and run it when you are ready."); tko_refresh(); }, onError: tko_error => toast.error(tko_error.message) });
  const tko_execute = trpc.ai.execute.useMutation({ onSuccess: () => { toast.success("Confirmed action executed and recorded."); tko_refresh(); }, onError: tko_error => toast.error(tko_error.message) });
  const tko_addContext = () => { const tko_id = tko_contextId.trim(); if (!/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(tko_id)) return toast.error("Enter a valid entity UUID."); if (tko_context.some(tko_item => tko_item.id === tko_id && tko_item.kind === tko_contextKind)) return; tko_setContext(tko_current => [...tko_current, { kind: tko_contextKind, id: tko_id }]); tko_setContextId(""); };
  const tko_run = (tko_mode: "read" | "draft") => { if (!tko_prompt.trim()) return toast.error("Enter a request for Tasko AI."); (tko_mode === "read" ? tko_read : tko_draft).mutate({ prompt: tko_prompt.trim(), context: tko_context }); };
  return <main className="mx-auto max-w-7xl p-5 sm:p-6 lg:p-10"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#766df0]">Tasko intelligence</p><h1 className="mt-1 text-3xl font-bold tracking-[-.05em] text-[#182230]">Ask about authorized work.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#667085]">AI is grounded only in the resources you can read. Drafts stay non-persistent, while write actions become reviewable proposals before they can run.</p></div><span className="inline-flex items-center gap-2 rounded-full bg-[#ecfdf3] px-3 py-1.5 text-xs font-semibold text-[#027a48]"><ShieldCheck className="h-3.5 w-3.5" /> Permission-aware</span></header>
    <section className="mt-7 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><article className="rounded-2xl border border-[#eaecf0] bg-white p-5 shadow-[0_1px_3px_rgba(16,24,40,.05)]"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#f0efff] text-[#5b51e8]"><Sparkles className="h-5 w-5" /></span><div><h2 className="font-semibold text-[#182230]">Operational assistant</h2><p className="text-xs text-[#667085]">Read answers and drafts are generated server-side with citations.</p></div></div><textarea value={tko_prompt} onChange={tko_event => tko_setPrompt(tko_event.target.value)} placeholder="For example: summarize the risks and next actions in the linked work." className="mt-5 min-h-32 w-full resize-y rounded-xl border border-[#d0d5dd] bg-[#fcfcfd] px-3.5 py-3 text-sm leading-6 text-[#344054] outline-none placeholder:text-[#98a2b3] focus:border-[#8178f8] focus:ring-4 focus:ring-[#eeedff]" /><div className="mt-3 flex flex-wrap items-center gap-2"><button type="button" onClick={() => tko_run("read")} disabled={tko_read.isPending || tko_draft.isPending} className="inline-flex items-center gap-2 rounded-lg bg-[#5b51e8] px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-[#4d43da] disabled:opacity-60"><Bot className="h-4 w-4" />{tko_read.isPending ? "Reviewing…" : "Ask AI"}</button><button type="button" onClick={() => tko_run("draft")} disabled={tko_read.isPending || tko_draft.isPending} className="inline-flex items-center gap-2 rounded-lg border border-[#c7d7fe] bg-[#eef4ff] px-3.5 py-2.5 text-sm font-semibold text-[#175cd3] transition hover:bg-[#dbeafe] disabled:opacity-60"><WandSparkles className="h-4 w-4" />{tko_draft.isPending ? "Drafting…" : "Create draft"}</button><p className="ml-auto text-xs text-[#98a2b3]">Never include passwords, tokens, or API keys.</p></div>{tko_result ? <div className="mt-5 rounded-xl border border-[#e7e5ff] bg-[#fafaff] p-4"><p className="text-xs font-bold uppercase tracking-[.1em] text-[#766df0]">Response</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#344054]">{tko_result}</p>{tko_citations.length ? <div className="mt-4 border-t border-[#e7e5ff] pt-3"><p className="text-[10px] font-bold uppercase tracking-[.1em] text-[#766df0]">Authorized sources</p><div className="mt-2 flex flex-wrap gap-2">{tko_citations.map(tko_citation => <a key={`${tko_citation.kind}:${tko_citation.id}`} href={tko_citation.locator} className="rounded-md border border-[#d9d6fe] bg-white px-2 py-1 text-xs font-medium text-[#5b51e8] hover:bg-[#f4f3ff]">[{tko_citation.label}]</a>)}</div></div> : null}</div> : null}</article>
      <article className="rounded-2xl border border-[#eaecf0] bg-white p-5 shadow-[0_1px_3px_rgba(16,24,40,.05)]"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#fff6ed] text-[#b54708]"><FileText className="h-5 w-5" /></span><div><h2 className="font-semibold text-[#182230]">Authorized context</h2><p className="text-xs text-[#667085]">Reference specific Tasko objects for grounded answers.</p></div></div><div className="mt-5 grid grid-cols-[.85fr_1.5fr_auto] gap-2"><select value={tko_contextKind} onChange={tko_event => tko_setContextKind(tko_event.target.value as TkoContextReference["kind"])} className="rounded-lg border border-[#d0d5dd] bg-white px-2 text-xs font-medium text-[#475467]">{tko_kinds.map(tko_kind => <option key={tko_kind}>{tko_kind.replaceAll("_", " ")}</option>)}</select><input value={tko_contextId} onChange={tko_event => tko_setContextId(tko_event.target.value)} placeholder="Entity UUID" className="min-w-0 rounded-lg border border-[#d0d5dd] px-2.5 text-xs outline-none focus:border-[#8178f8]" /><button type="button" onClick={tko_addContext} className="grid h-9 w-9 place-items-center rounded-lg bg-[#f0efff] text-[#5b51e8] hover:bg-[#e7e5ff]" aria-label="Add context"><Plus className="h-4 w-4" /></button></div><div className="mt-4 space-y-2">{tko_context.length ? tko_context.map(tko_item => <div key={`${tko_item.kind}:${tko_item.id}`} className="flex items-center gap-2 rounded-lg border border-[#f2f4f7] bg-[#fcfcfd] px-2.5 py-2"><span className="rounded bg-[#f0efff] px-1.5 py-0.5 text-[10px] font-bold text-[#5b51e8]">{tko_item.kind}</span><span className="min-w-0 flex-1 truncate font-mono text-[10px] text-[#667085]">{tko_item.id}</span><button type="button" onClick={() => tko_setContext(tko_current => tko_current.filter(tko_value => tko_value !== tko_item))} className="text-xs font-semibold text-[#b42318]">Remove</button></div>) : <p className="rounded-xl border border-dashed border-[#d0d5dd] px-3 py-6 text-center text-xs leading-5 text-[#98a2b3]">No objects attached. AI will not see workspace content until you add authorized context.</p>}</div></article></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><article className="rounded-2xl border border-[#eaecf0] bg-white p-5 shadow-[0_1px_3px_rgba(16,24,40,.05)]"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-[#182230]">Action proposals</h2><p className="mt-1 text-xs text-[#667085]">Write tools cannot run automatically. Confirmation and execution are separately audited.</p></div><Send className="h-5 w-5 text-[#766df0]" /></div><div className="mt-4 divide-y divide-[#f2f4f7]">{tko_proposals.data?.length ? tko_proposals.data.map(tko_proposal => <div key={tko_proposal.id} className="flex flex-wrap items-center gap-3 py-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#f4f3ff] text-[#5b51e8]"><Play className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-[#344054]">{tko_proposal.toolName}</p><p className="mt-0.5 truncate text-xs text-[#98a2b3]">{Object.values(tko_proposal.preview).filter(tko_value => typeof tko_value === "string").join(" · ") || "Review requested action"}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${tko_statusTone(tko_proposal.status)}`}>{tko_proposal.status}</span>{tko_proposal.status === "proposed" ? <button type="button" disabled={tko_confirm.isPending} onClick={() => tko_confirm.mutate({ proposalId: tko_proposal.id })} className="text-xs font-semibold text-[#175cd3] hover:underline">Confirm</button> : null}{tko_proposal.status === "confirmed" ? <button type="button" disabled={tko_execute.isPending} onClick={() => tko_execute.mutate({ proposalId: tko_proposal.id })} className="text-xs font-semibold text-[#027a48] hover:underline">Run action</button> : null}</div>) : <p className="py-8 text-center text-sm text-[#667085]">No write action has been proposed.</p>}</div></article>
      <article className="rounded-2xl border border-[#eaecf0] bg-white p-5 shadow-[0_1px_3px_rgba(16,24,40,.05)]"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-[#182230]">Run history</h2><p className="mt-1 text-xs text-[#667085]">Metadata, outputs and citations are traceable from each run.</p></div><CheckCircle2 className="h-5 w-5 text-[#027a48]" /></div><div className="mt-4 divide-y divide-[#f2f4f7]">{tko_runs.data?.length ? tko_runs.data.slice(0, 7).map(tko_run => <div key={tko_run.id} className="flex items-center gap-3 py-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#f2f4f7] text-xs font-bold text-[#475467]">AI</span><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-[#344054]">{tko_run.mode} run</p><p className="text-xs text-[#98a2b3]">{new Date(tko_run.createdAt).toLocaleString()}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${tko_statusTone(tko_run.status)}`}>{tko_run.status}</span></div>) : <p className="py-8 text-center text-sm text-[#667085]">No AI run is recorded in this workspace.</p>}</div></article></section>
  </main>;
}
