import { useState } from "react";
import { Cable, Code2, KeyRound, Link2, Plus, Radio, RotateCcw, ShieldCheck, Webhook } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const tko_scopes = ["imports:read", "imports:write", "webhooks:manage", "integrations:manage", "work:read", "work:write", "chat:read", "chat:write", "crm:read", "crm:write"] as const;
const tko_providers = ["github", "gitlab", "jira", "clickup", "slack"] as const;
const tko_statusTone = (tko_status: string) => tko_status === "active" || tko_status === "delivered" ? "bg-[#ecfdf3] text-[#027a48]" : tko_status === "dead_letter" || tko_status === "revoked" ? "bg-[#fef3f2] text-[#b42318]" : "bg-[#f4f3ff] text-[#5b51e8]";
const tko_tokenStatus = (tko_token: { revokedAt: Date | null; expiresAt: Date | null }) => tko_token.revokedAt ? "revoked" : tko_token.expiresAt && new Date(tko_token.expiresAt).getTime() <= Date.now() ? "expired" : "active";

export default function Ecosystem() {
  const tko_utils = trpc.useUtils();
  const tko_tokens = trpc.ecosystem.tokens.useQuery(undefined, { retry: false });
  const tko_webhooks = trpc.ecosystem.webhooks.useQuery(undefined, { retry: false });
  const tko_connections = trpc.ecosystem.connections.useQuery(undefined, { retry: false });
  const [tko_tokenName, tko_setTokenName] = useState("Automation integration");
  const [tko_selectedScopes, tko_setSelectedScopes] = useState<string[]>(["imports:read"]);
  const [tko_plainToken, tko_setPlainToken] = useState<string | null>(null);
  const [tko_webhookSecret, tko_setWebhookSecret] = useState<string | null>(null);
  const [tko_webhookName, tko_setWebhookName] = useState("Tasko events");
  const [tko_endpoint, tko_setEndpoint] = useState("https://example.test/tasko/webhooks");
  const [tko_eventTypes, tko_setEventTypes] = useState("work.work_item_created.v1");
  const [tko_provider, tko_setProvider] = useState<(typeof tko_providers)[number]>("github");
  const [tko_connectionName, tko_setConnectionName] = useState("Engineering workspace");
  const tko_issue = trpc.ecosystem.issueToken.useMutation({ onSuccess: tko_result => { tko_setPlainToken(tko_result.secret); void tko_utils.ecosystem.tokens.invalidate(); toast.success("Token issued. Copy it now; it will not be shown again."); }, onError: tko_error => toast.error(tko_error.message) });
  const tko_revoke = trpc.ecosystem.revokeToken.useMutation({ onSuccess: () => { void tko_utils.ecosystem.tokens.invalidate(); toast.success("Token revoked."); }, onError: tko_error => toast.error(tko_error.message) });
  const tko_createWebhook = trpc.ecosystem.createWebhook.useMutation({ onSuccess: tko_result => { tko_setWebhookSecret(tko_result.signingSecret); void tko_utils.ecosystem.webhooks.invalidate(); toast.success("Webhook subscription created. Copy its signing secret now."); }, onError: tko_error => toast.error(tko_error.message) });
  const tko_connect = trpc.ecosystem.connect.useMutation({ onSuccess: () => { void tko_utils.ecosystem.connections.invalidate(); toast.success("Integration boundary registered."); }, onError: tko_error => toast.error(tko_error.message) });
  const tko_toggleScope = (tko_scope: string) => tko_setSelectedScopes(tko_current => tko_current.includes(tko_scope) ? tko_current.filter(tko_item => tko_item !== tko_scope) : [...tko_current, tko_scope]);
  return <main className="mx-auto max-w-7xl p-5 sm:p-6 lg:p-10"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#766df0]">Developer ecosystem</p><h1 className="mt-1 text-3xl font-bold tracking-[-.05em] text-[#182230]">Controlled access for connected work</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#667085]">Issue scoped tokens, register signed webhook deliveries and manage provider boundaries. Credentials and tenant roles are resolved server-side.</p></div><span className="rounded-full bg-[#ecfdf3] px-3 py-1.5 text-xs font-semibold text-[#027a48]">Audited mutations</span></header>
    <section className="mt-7 grid gap-5 xl:grid-cols-2"><article className="rounded-2xl border border-[#eaecf0] bg-white p-5 shadow-[0_1px_3px_rgba(16,24,40,.05)]"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#f0efff] text-[#5b51e8]"><KeyRound className="h-5 w-5" /></span><div><h2 className="font-semibold text-[#182230]">Scoped API token</h2><p className="text-xs text-[#667085]">Minimum scopes only; revoke at any time.</p></div></div><label className="mt-5 block text-xs font-semibold text-[#475467]">Token name<input value={tko_tokenName} onChange={tko_event => tko_setTokenName(tko_event.target.value)} className="mt-1.5 w-full rounded-lg border border-[#d0d5dd] px-3 py-2.5 text-sm" /></label><div className="mt-4 flex flex-wrap gap-2">{tko_scopes.map(tko_scope => <button key={tko_scope} type="button" onClick={() => tko_toggleScope(tko_scope)} className={`rounded-full px-2.5 py-1.5 text-xs font-semibold transition ${tko_selectedScopes.includes(tko_scope) ? "bg-[#5b51e8] text-white" : "bg-[#f2f4f7] text-[#667085] hover:bg-[#e7e5ff]"}`}>{tko_scope}</button>)}</div><button type="button" disabled={tko_issue.isPending || !tko_selectedScopes.length} onClick={() => tko_issue.mutate({ name: tko_tokenName, scopes: tko_selectedScopes as typeof tko_scopes[number][] })} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[#5b51e8] px-3 py-2.5 text-sm font-semibold text-white disabled:opacity-60"><Plus className="h-4 w-4" />{tko_issue.isPending ? "Issuing…" : "Issue token"}</button>{tko_plainToken ? <div className="mt-4 rounded-xl border border-[#f6c8c3] bg-[#fffbfa] p-3"><p className="text-xs font-semibold text-[#b42318]">Copy this secret now — it will not be displayed again.</p><code className="mt-2 block break-all rounded-lg bg-white p-2 text-xs text-[#344054]">{tko_plainToken}</code></div> : null}</article>
      <article className="rounded-2xl border border-[#eaecf0] bg-white p-5 shadow-[0_1px_3px_rgba(16,24,40,.05)]"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eef4ff] text-[#175cd3]"><Webhook className="h-5 w-5" /></span><div><h2 className="font-semibold text-[#182230]">Signed webhook</h2><p className="text-xs text-[#667085]">HMAC signing, retry/backoff and dead-letter visibility.</p></div></div><label className="mt-5 block text-xs font-semibold text-[#475467]">Subscription name<input value={tko_webhookName} onChange={tko_event => tko_setWebhookName(tko_event.target.value)} className="mt-1.5 w-full rounded-lg border border-[#d0d5dd] px-3 py-2.5 text-sm" /></label><label className="mt-3 block text-xs font-semibold text-[#475467]">HTTPS endpoint<input value={tko_endpoint} onChange={tko_event => tko_setEndpoint(tko_event.target.value)} className="mt-1.5 w-full rounded-lg border border-[#d0d5dd] px-3 py-2.5 text-sm" /></label><label className="mt-3 block text-xs font-semibold text-[#475467]">Event types <span className="font-normal text-[#98a2b3]">(comma-separated)</span><input value={tko_eventTypes} onChange={tko_event => tko_setEventTypes(tko_event.target.value)} className="mt-1.5 w-full rounded-lg border border-[#d0d5dd] px-3 py-2.5 text-sm" /></label><button type="button" disabled={tko_createWebhook.isPending} onClick={() => tko_createWebhook.mutate({ name: tko_webhookName, endpointUrl: tko_endpoint, eventTypes: tko_eventTypes.split(",").map(tko_item => tko_item.trim()).filter(Boolean) })} className="mt-5 inline-flex items-center gap-2 rounded-lg border border-[#c7d7fe] bg-[#eef4ff] px-3 py-2.5 text-sm font-semibold text-[#175cd3] disabled:opacity-60"><Radio className="h-4 w-4" />{tko_createWebhook.isPending ? "Registering…" : "Register webhook"}</button>{tko_webhookSecret ? <div className="mt-4 rounded-xl border border-[#f6c8c3] bg-[#fffbfa] p-3"><p className="text-xs font-semibold text-[#b42318]">Copy this HMAC signing secret now — it will not be displayed again.</p><code className="mt-2 block break-all rounded-lg bg-white p-2 text-xs text-[#344054]">{tko_webhookSecret}</code></div> : null}</article></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><article className="rounded-2xl border border-[#eaecf0] bg-white p-5 shadow-[0_1px_3px_rgba(16,24,40,.05)]"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-[#182230]">API tokens</h2><p className="mt-1 text-xs text-[#667085]">Only token metadata is shown after issuance.</p></div><Code2 className="h-5 w-5 text-[#766df0]" /></div><div className="mt-4 divide-y divide-[#f2f4f7]">{tko_tokens.data?.length ? tko_tokens.data.map(tko_token => { const tko_state = tko_tokenStatus(tko_token); return <div key={tko_token.id} className="flex flex-wrap items-center gap-3 py-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#f4f3ff] text-[#5b51e8]"><KeyRound className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#344054]">{tko_token.name}</p><p className="mt-0.5 truncate text-xs text-[#98a2b3]">{tko_token.scopes.join(", ")}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${tko_statusTone(tko_state)}`}>{tko_state}</span>{tko_state === "active" ? <button type="button" disabled={tko_revoke.isPending} onClick={() => tko_revoke.mutate({ tokenId: tko_token.id })} className="text-xs font-semibold text-[#b42318] hover:underline">Revoke</button> : null}</div>; }) : <p className="py-8 text-center text-sm text-[#667085]">No developer token has been issued.</p>}</div></article>
      <article className="rounded-2xl border border-[#eaecf0] bg-white p-5 shadow-[0_1px_3px_rgba(16,24,40,.05)]"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#ecfdf3] text-[#027a48]"><Cable className="h-5 w-5" /></span><div><h2 className="font-semibold text-[#182230]">External connection</h2><p className="text-xs text-[#667085]">Register a provider boundary; credentials stay out of the browser.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-[#475467]">Provider<select value={tko_provider} onChange={tko_event => tko_setProvider(tko_event.target.value as typeof tko_provider)} className="mt-1.5 w-full rounded-lg border border-[#d0d5dd] bg-white px-3 py-2.5 text-sm">{tko_providers.map(tko_option => <option key={tko_option} value={tko_option}>{tko_option}</option>)}</select></label><label className="text-xs font-semibold text-[#475467]">Display name<input value={tko_connectionName} onChange={tko_event => tko_setConnectionName(tko_event.target.value)} className="mt-1.5 w-full rounded-lg border border-[#d0d5dd] px-3 py-2.5 text-sm" /></label></div><button type="button" disabled={tko_connect.isPending} onClick={() => tko_connect.mutate({ provider: tko_provider, displayName: tko_connectionName })} className="mt-4 inline-flex items-center gap-2 rounded-lg border border-[#b7ebcd] bg-[#ecfdf3] px-3 py-2.5 text-sm font-semibold text-[#027a48] disabled:opacity-60"><Link2 className="h-4 w-4" />{tko_connect.isPending ? "Registering…" : "Register connection"}</button><div className="mt-4 divide-y divide-[#f2f4f7]">{tko_connections.data?.length ? tko_connections.data.map(tko_connection => <div key={tko_connection.id} className="flex items-center gap-3 py-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#f2f4f7] text-xs font-bold text-[#475467]">{tko_connection.provider.slice(0, 2).toUpperCase()}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-[#344054]">{tko_connection.displayName}</span><span className="text-xs text-[#98a2b3]">{tko_connection.provider}</span></span><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${tko_statusTone(tko_connection.status)}`}>{tko_connection.status}</span></div>) : <p className="py-5 text-sm text-[#667085]">No provider boundary is registered.</p>}</div></article></section>
    <section className="mt-5 rounded-2xl border border-[#eaecf0] bg-white p-5 shadow-[0_1px_3px_rgba(16,24,40,.05)]"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#fff6ed] text-[#b54708]"><ShieldCheck className="h-5 w-5" /></span><div><h2 className="font-semibold text-[#182230]">Webhook delivery policy</h2><p className="mt-1 text-xs text-[#667085]">Events originate from the transactional outbox. The delivery worker signs payloads with an encrypted server-held secret and routes failed attempts through bounded retry/backoff before dead-lettering.</p></div><RotateCcw className="ml-auto h-5 w-5 text-[#98a2b3]" /></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{tko_webhooks.data?.length ? tko_webhooks.data.map(tko_webhook => <div key={tko_webhook.id} className="rounded-xl border border-[#f2f4f7] bg-[#fcfcfd] p-3"><p className="truncate text-sm font-semibold text-[#344054]">{tko_webhook.name}</p><p className="mt-1 truncate text-xs text-[#98a2b3]">{tko_webhook.endpointUrl}</p><span className={`mt-3 inline-block rounded-full px-2 py-1 text-[10px] font-bold ${tko_statusTone(tko_webhook.status)}`}>{tko_webhook.status}</span></div>) : <p className="text-sm text-[#667085]">Register a webhook to begin signed outbox-driven delivery.</p>}</div></section>
  </main>;
}
