import { useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, FileUp, Layers3, Play, Plus, TableProperties } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const tko_sources = ["crm_csv", "jira", "clickup", "slack"] as const;
const tko_targets = ["lead", "work_item", "channel", "message"] as const;
const tko_label = (tko_value: string) => tko_value.replaceAll("_", " ");
const tko_statusTone = (tko_status: string) => tko_status === "completed" ? "bg-[#ecfdf3] text-[#027a48]" : tko_status === "failed" || tko_status === "error" ? "bg-[#fef3f2] text-[#b42318]" : "bg-[#f4f3ff] text-[#5b51e8]";

export default function Imports() {
  const tko_utils = trpc.useUtils();
  const tko_imports = trpc.ecosystem.imports.useQuery(undefined, { retry: false });
  const [tko_source, tko_setSource] = useState<(typeof tko_sources)[number]>("crm_csv");
  const [tko_name, tko_setName] = useState("Customer data migration");
  const [tko_selectedJobId, tko_setSelectedJobId] = useState<string | null>(null);
  const [tko_sourceRecordId, tko_setSourceRecordId] = useState("row-001");
  const [tko_sourceType, tko_setSourceType] = useState("crm_contact");
  const [tko_payload, tko_setPayload] = useState('{"firstName":"Ada","lastName":"Lovelace","email":"ada@example.test","companyName":"Analytical Engines"}');
  const [tko_target, tko_setTarget] = useState<(typeof tko_targets)[number]>("lead");
  const [tko_batchIds, tko_setBatchIds] = useState<string[]>([]);
  const tko_selectedJob = tko_selectedJobId ?? tko_imports.data?.[0]?.id ?? null;
  const tko_preview = trpc.ecosystem.previewImport.useQuery({ jobId: tko_selectedJob ?? "00000000-0000-0000-0000-000000000000" }, { enabled: Boolean(tko_selectedJob), retry: false });

  const tko_create = trpc.ecosystem.createImport.useMutation({
    onSuccess: tko_job => { tko_setSelectedJobId(tko_job.id); void tko_utils.ecosystem.imports.invalidate(); toast.success("Import job created. Stage source records before execution."); },
    onError: tko_error => toast.error(tko_error.message),
  });
  const tko_stage = trpc.ecosystem.stageImport.useMutation({
    onSuccess: () => { void tko_preview.refetch(); void tko_utils.ecosystem.imports.invalidate(); toast.success("Record staged for validation and preview."); },
    onError: tko_error => toast.error(tko_error.message),
  });
  const tko_mapping = trpc.ecosystem.saveImportMapping.useMutation({
    onSuccess: () => { void tko_preview.refetch(); toast.success("Mapping saved. The job is ready to queue."); },
    onError: tko_error => toast.error(tko_error.message),
  });
  const tko_queue = trpc.ecosystem.queueImport.useMutation({
    onSuccess: tko_batches => { tko_setBatchIds(tko_batches.map(tko_batch => tko_batch.id)); void tko_preview.refetch(); toast.success(`${tko_batches.length} batch${tko_batches.length === 1 ? "" : "es"} queued.`); },
    onError: tko_error => toast.error(tko_error.message),
  });
  const tko_execute = trpc.ecosystem.executeImportBatch.useMutation({
    onSuccess: () => { void tko_preview.refetch(); void tko_utils.ecosystem.imports.invalidate(); toast.success("Batch materialized with source mappings recorded."); },
    onError: tko_error => toast.error(tko_error.message),
  });

  const tko_defaultFields = useMemo(() => tko_target === "lead"
    ? [{ sourceField: "firstName", targetField: "firstName", transform: "identity" as const, required: true }, { sourceField: "lastName", targetField: "lastName", transform: "identity" as const, required: false }, { sourceField: "email", targetField: "email", transform: "email" as const, required: false }, { sourceField: "companyName", targetField: "companyName", transform: "identity" as const, required: false }]
    : [{ sourceField: tko_target === "work_item" ? "title" : "name", targetField: tko_target === "work_item" ? "title" : "name", transform: "identity" as const, required: true }], [tko_target]);

  const tko_stageRecord = () => {
    if (!tko_selectedJob) return toast.error("Create or select an import job first.");
    try {
      const tko_parsed = JSON.parse(tko_payload) as Record<string, unknown>;
      tko_stage.mutate({ jobId: tko_selectedJob, records: [{ sourceRecordId: tko_sourceRecordId, sourceType: tko_sourceType, payload: tko_parsed, status: "valid" }] });
    } catch { toast.error("Payload must be valid JSON."); }
  };

  return <main className="mx-auto max-w-7xl p-5 sm:p-6 lg:p-10">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#766df0]">Import center</p><h1 className="mt-1 text-3xl font-bold tracking-[-.05em] text-[#182230]">Staged, reviewable imports</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#667085]">Parse and validate source data before mapping it into Tasko. Executions remain resumable and record source mappings for idempotency.</p></div><span className="rounded-full bg-[#ecfdf3] px-3 py-1.5 text-xs font-semibold text-[#027a48]">Tenant scoped</span></header>

    <section className="mt-7 grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><article className="rounded-2xl border border-[#eaecf0] bg-white p-5 shadow-[0_1px_3px_rgba(16,24,40,.05)]"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#f0efff] text-[#5b51e8]"><Plus className="h-5 w-5" /></span><div><h2 className="font-semibold text-[#182230]">Start an import</h2><p className="text-xs text-[#667085]">Create an idempotent import job.</p></div></div><label className="mt-5 block text-xs font-semibold text-[#475467]">Source<select value={tko_source} onChange={tko_event => tko_setSource(tko_event.target.value as typeof tko_source)} className="mt-1.5 w-full rounded-lg border border-[#d0d5dd] bg-white px-3 py-2.5 text-sm font-medium text-[#344054]">{tko_sources.map(tko_option => <option key={tko_option} value={tko_option}>{tko_label(tko_option)}</option>)}</select></label><label className="mt-4 block text-xs font-semibold text-[#475467]">Job name<input value={tko_name} onChange={tko_event => tko_setName(tko_event.target.value)} className="mt-1.5 w-full rounded-lg border border-[#d0d5dd] px-3 py-2.5 text-sm text-[#344054]" maxLength={240} /></label><button type="button" disabled={tko_create.isPending} onClick={() => tko_create.mutate({ source: tko_source, name: tko_name, idempotencyKey: crypto.randomUUID() })} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-[#5b51e8] px-3 py-2.5 text-sm font-semibold text-white transition hover:bg-[#4d43da] disabled:opacity-60 active:scale-[.97]"><FileUp className="h-4 w-4" />{tko_create.isPending ? "Creating…" : "Create import job"}</button></article>
      <article className="rounded-2xl border border-[#eaecf0] bg-white p-5 shadow-[0_1px_3px_rgba(16,24,40,.05)]"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-[#182230]">Import jobs</h2><p className="mt-1 text-xs text-[#667085]">Select a job to inspect staged records and execution state.</p></div><Layers3 className="h-5 w-5 text-[#766df0]" /></div><div className="mt-4 divide-y divide-[#f2f4f7]">{tko_imports.data?.length ? tko_imports.data.map(tko_job => <button key={tko_job.id} type="button" onClick={() => { tko_setSelectedJobId(tko_job.id); tko_setBatchIds([]); }} className={`flex w-full items-center gap-3 px-2 py-3 text-left transition hover:bg-[#fcfcfd] ${tko_job.id === tko_selectedJob ? "bg-[#f7f7ff]" : ""}`}><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-[#f4f3ff] text-xs font-bold text-[#5b51e8]">{tko_job.source.slice(0, 2).toUpperCase()}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-[#344054]">{tko_job.name}</span><span className="mt-0.5 block text-xs text-[#98a2b3]">{tko_job.importedRecords} / {tko_job.totalRecords} imported</span></span><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${tko_statusTone(tko_job.status)}`}>{tko_label(tko_job.status)}</span><ArrowRight className="h-4 w-4 text-[#98a2b3]" /></button>) : <p className="py-10 text-center text-sm text-[#667085]">No import jobs yet. Create one to begin a controlled migration.</p>}</div></article></section>

    {tko_selectedJob ? <section className="mt-5 grid gap-5 xl:grid-cols-[1fr_1fr]"><article className="rounded-2xl border border-[#eaecf0] bg-white p-5 shadow-[0_1px_3px_rgba(16,24,40,.05)]"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eef4ff] text-[#175cd3]"><TableProperties className="h-5 w-5" /></span><div><h2 className="font-semibold text-[#182230]">1. Stage a record</h2><p className="text-xs text-[#667085]">Use parsed source data. The backend validates ownership and source-record idempotency.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-[#475467]">Source record ID<input value={tko_sourceRecordId} onChange={tko_event => tko_setSourceRecordId(tko_event.target.value)} className="mt-1.5 w-full rounded-lg border border-[#d0d5dd] px-3 py-2.5 text-sm" /></label><label className="text-xs font-semibold text-[#475467]">Source type<input value={tko_sourceType} onChange={tko_event => tko_setSourceType(tko_event.target.value)} className="mt-1.5 w-full rounded-lg border border-[#d0d5dd] px-3 py-2.5 text-sm" /></label></div><label className="mt-3 block text-xs font-semibold text-[#475467]">JSON payload<textarea value={tko_payload} onChange={tko_event => tko_setPayload(tko_event.target.value)} className="mt-1.5 min-h-32 w-full rounded-lg border border-[#d0d5dd] p-3 font-mono text-xs leading-5 text-[#344054]" /></label><button type="button" disabled={tko_stage.isPending} onClick={tko_stageRecord} className="mt-4 inline-flex items-center gap-2 rounded-lg border border-[#c7d7fe] bg-[#eef4ff] px-3 py-2.5 text-sm font-semibold text-[#175cd3] transition hover:bg-[#dbe8ff] disabled:opacity-60"><CheckCircle2 className="h-4 w-4" />{tko_stage.isPending ? "Staging…" : "Validate & stage"}</button></article>
      <article className="rounded-2xl border border-[#eaecf0] bg-white p-5 shadow-[0_1px_3px_rgba(16,24,40,.05)]"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#ecfdf3] text-[#027a48]"><Layers3 className="h-5 w-5" /></span><div><h2 className="font-semibold text-[#182230]">2. Map &amp; execute</h2><p className="text-xs text-[#667085]">Persisted mappings are required before batch materialization.</p></div></div><label className="mt-5 block text-xs font-semibold text-[#475467]">Target model<select value={tko_target} onChange={tko_event => tko_setTarget(tko_event.target.value as typeof tko_target)} className="mt-1.5 w-full rounded-lg border border-[#d0d5dd] bg-white px-3 py-2.5 text-sm font-medium text-[#344054]">{tko_targets.map(tko_option => <option key={tko_option} value={tko_option}>{tko_label(tko_option)}</option>)}</select></label><div className="mt-4 rounded-xl border border-[#f2f4f7] bg-[#fcfcfd] p-3"><p className="text-xs font-semibold text-[#475467]">Suggested fields</p><div className="mt-2 space-y-1">{tko_defaultFields.map(tko_field => <p key={tko_field.targetField} className="font-mono text-[11px] text-[#667085]">{tko_field.sourceField} <span className="text-[#98a2b3]">→</span> {tko_field.targetField}{tko_field.required ? " · required" : ""}</p>)}</div></div><div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={tko_mapping.isPending} onClick={() => tko_mapping.mutate({ jobId: tko_selectedJob, sourceType: tko_sourceType, targetKind: tko_target, duplicateStrategy: "skip", fields: tko_defaultFields })} className="rounded-lg border border-[#c7d7fe] bg-[#eef4ff] px-3 py-2.5 text-sm font-semibold text-[#175cd3] disabled:opacity-60">{tko_mapping.isPending ? "Saving…" : "Save mapping"}</button><button type="button" disabled={tko_queue.isPending || !tko_preview.data?.records.length} onClick={() => tko_queue.mutate({ jobId: tko_selectedJob, idempotencyKey: crypto.randomUUID() })} className="rounded-lg bg-[#5b51e8] px-3 py-2.5 text-sm font-semibold text-white transition hover:bg-[#4d43da] disabled:opacity-60">Queue batches</button>{tko_batchIds.map(tko_batchId => <button key={tko_batchId} type="button" disabled={tko_execute.isPending} onClick={() => tko_execute.mutate({ batchId: tko_batchId })} className="inline-flex items-center gap-2 rounded-lg bg-[#027a48] px-3 py-2.5 text-sm font-semibold text-white disabled:opacity-60"><Play className="h-4 w-4" />Run batch</button>)}</div></article></section> : null}

    {tko_selectedJob ? <section className="mt-5 rounded-2xl border border-[#eaecf0] bg-white p-5 shadow-[0_1px_3px_rgba(16,24,40,.05)]"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-[#182230]">Preview &amp; validation</h2><p className="mt-1 text-xs text-[#667085]">Records never materialize until a mapping is saved and a queued batch is intentionally run.</p></div><span className="rounded-full bg-[#f4f3ff] px-3 py-1 text-xs font-bold text-[#5b51e8]">{tko_preview.data?.records.length ?? 0} staged</span></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-[#eaecf0] text-xs uppercase tracking-wide text-[#98a2b3]"><tr><th className="pb-3">Source record</th><th className="pb-3">Type</th><th className="pb-3">Status</th><th className="pb-3">Target</th><th className="pb-3">Validation</th></tr></thead><tbody>{tko_preview.data?.records.length ? tko_preview.data.records.map(tko_record => <tr key={tko_record.id} className="border-b border-[#f2f4f7] last:border-0"><td className="py-3 font-mono text-xs text-[#475467]">{tko_record.sourceRecordId}</td><td className="py-3 text-[#475467]">{tko_record.sourceType}</td><td className="py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${tko_statusTone(tko_record.status)}`}>{tko_record.status}</span></td><td className="py-3 text-[#475467]">{tko_record.targetKind ?? "Not mapped"}</td><td className="py-3 text-xs text-[#667085]">{Object.keys(tko_record.validation).length ? JSON.stringify(tko_record.validation) : "No issues"}</td></tr>) : <tr><td colSpan={5} className="py-8 text-center text-sm text-[#667085]">Stage a source record to inspect validation and mapping readiness.</td></tr>}</tbody></table></div></section> : null}
  </main>;
}
