import type { ImportFieldMapping, ImportSource, ImportTargetKind } from "../../../packages/contracts/src/ecosystem";
import type { StageImportRecordInput } from "../../../packages/database/src/ecosystem-store";

export interface ImportAdapterOutput { source: ImportSource; records: StageImportRecordInput[]; suggestedMappings: Array<{ sourceType: string; targetKind: ImportTargetKind; fields: ImportFieldMapping[] }>; warnings: string[]; }
const tko_record = (tko_sourceRecordId: string, tko_sourceType: string, tko_payload: Record<string, unknown>): StageImportRecordInput => ({ sourceRecordId: tko_sourceRecordId, sourceType: tko_sourceType, payload: tko_payload, status: "valid", validation: {} });
const tko_string = (tko_value: unknown): string => typeof tko_value === "string" ? tko_value.trim() : "";

function tko_csvRows(tko_csv: string): string[][] { const tko_rows: string[][] = []; let tko_row: string[] = [], tko_field = "", tko_quotes = false; for (let tko_index = 0; tko_index < tko_csv.length; tko_index += 1) { const tko_character = tko_csv[tko_index]; if (tko_character === '"' && tko_csv[tko_index + 1] === '"') { tko_field += '"'; tko_index += 1; } else if (tko_character === '"') tko_quotes = !tko_quotes; else if (tko_character === "," && !tko_quotes) { tko_row.push(tko_field); tko_field = ""; } else if ((tko_character === "\n" || tko_character === "\r") && !tko_quotes) { if (tko_character === "\r" && tko_csv[tko_index + 1] === "\n") tko_index += 1; tko_row.push(tko_field); if (tko_row.some(tko_value => tko_value.trim())) tko_rows.push(tko_row); tko_row = []; tko_field = ""; } else tko_field += tko_character; } tko_row.push(tko_field); if (tko_row.some(tko_value => tko_value.trim())) tko_rows.push(tko_row); return tko_rows; }
const tko_workMapping: ImportAdapterOutput["suggestedMappings"] = [{ sourceType: "issue", targetKind: "work_item", fields: [{ sourceField: "summary", targetField: "title", transform: "identity", required: true }, { sourceField: "description", targetField: "description", transform: "identity", required: false }, { sourceField: "taskoProjectId", targetField: "projectId", transform: "identity", required: true }] }];

export function parseJiraIssues(tko_issues: Array<Record<string, unknown>>, tko_taskoProjectId: string): ImportAdapterOutput { return { source: "jira", records: tko_issues.map(tko_issue => tko_record(tko_string(tko_issue.id) || tko_string(tko_issue.key), "issue", { summary: tko_string(tko_issue.summary) || tko_string((tko_issue.fields as Record<string, unknown> | undefined)?.summary), description: tko_string(tko_issue.description) || tko_string((tko_issue.fields as Record<string, unknown> | undefined)?.description), taskoProjectId: tko_taskoProjectId, sourceKey: tko_string(tko_issue.key) })), suggestedMappings: tko_workMapping, warnings: [] }; }
export function parseClickUpTasks(tko_tasks: Array<Record<string, unknown>>, tko_taskoProjectId: string): ImportAdapterOutput { return { source: "clickup", records: tko_tasks.map(tko_task => tko_record(tko_string(tko_task.id), "issue", { summary: tko_string(tko_task.name), description: tko_string(tko_task.description), taskoProjectId: tko_taskoProjectId, sourceUrl: tko_string(tko_task.url) })), suggestedMappings: tko_workMapping, warnings: [] }; }
export function parseCrmCsv(tko_csv: string): ImportAdapterOutput { const [tko_headers = [], ...tko_rows] = tko_csvRows(tko_csv); const tko_normalizedHeaders = tko_headers.map(tko_header => tko_header.trim().toLowerCase()); const tko_records = tko_rows.map((tko_row, tko_index) => { const tko_payload = Object.fromEntries(tko_normalizedHeaders.map((tko_header, tko_column) => [tko_header, tko_row[tko_column] ?? ""])); return tko_record(tko_string(tko_payload.id) || `csv-${tko_index + 1}`, "crm_contact", tko_payload); }); return { source: "crm_csv", records: tko_records, suggestedMappings: [{ sourceType: "crm_contact", targetKind: "lead", fields: [{ sourceField: "name", targetField: "name", transform: "split_name", required: true }, { sourceField: "email", targetField: "email", transform: "email", required: false }, { sourceField: "company", targetField: "companyName", transform: "identity", required: false }, { sourceField: "phone", targetField: "phone", transform: "identity", required: false }] }], warnings: [] }; }
export function parseSlackExport(tko_export: { channels?: Array<Record<string, unknown>>; messages?: Array<Record<string, unknown>> }): ImportAdapterOutput { const tko_channels = (tko_export.channels ?? []).map(tko_channel => tko_record(tko_string(tko_channel.id) || tko_string(tko_channel.name), "channel", { name: tko_string(tko_channel.name), topic: tko_string((tko_channel.topic as Record<string, unknown> | undefined)?.value), kind: tko_channel.is_private ? "private" : "public" })); const tko_messages = (tko_export.messages ?? []).map((tko_message, tko_index) => tko_record(tko_string(tko_message.ts) || `message-${tko_index + 1}`, "message", { channelSourceId: tko_string(tko_message.channel) || tko_string(tko_message.channel_id), text: tko_string(tko_message.text), originalTs: tko_string(tko_message.ts), originalUser: tko_string(tko_message.user) })); return { source: "slack", records: [...tko_channels, ...tko_messages], suggestedMappings: [{ sourceType: "channel", targetKind: "channel", fields: [{ sourceField: "name", targetField: "name", transform: "identity", required: true }, { sourceField: "topic", targetField: "topic", transform: "identity", required: false }, { sourceField: "kind", targetField: "kind", transform: "identity", required: false }] }, { sourceType: "message", targetKind: "message", fields: [{ sourceField: "channelSourceId", targetField: "channelSourceId", transform: "identity", required: true }, { sourceField: "text", targetField: "text", transform: "identity", required: false }] }], warnings: ["Slack author identities are preserved in immutable staged payload metadata; imported messages are attributed to the executing Tasko member until identity mapping is configured."] }; }
