export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  storageBackend: process.env.TASKO_STORAGE_BACKEND ?? "",
  s3Endpoint: process.env.TASKO_S3_ENDPOINT ?? "",
  s3Region: process.env.TASKO_S3_REGION ?? "",
  s3Bucket: process.env.TASKO_S3_BUCKET ?? "",
  s3AccessKeyId: process.env.TASKO_S3_ACCESS_KEY_ID ?? "",
  s3SecretAccessKey: process.env.TASKO_S3_SECRET_ACCESS_KEY ?? "",
  s3ForcePathStyle: process.env.TASKO_S3_FORCE_PATH_STYLE === "true",
};
