import crypto from "node:crypto";
import pg from "pg";
import { tko_config } from "../../config/src/tasko-config";
import type { AIContextReference, AIRun, AIToolProposal, CreateAIRunInput, CreateAIToolProposalInput } from "../../contracts/src/ai";
import type { PlatformActor } from "../../contracts/src/platform";
import { getPlatformStore } from "./platform-store";

type TkoRow = Record<string, unknown>;
const tko_clone = <T>(tko_value: T): T => structuredClone(tko_value);
const tko_json = <T>(tko_value: unknown, tko_fallback: T): T => typeof tko_value === "string" ? JSON.parse(tko_value) as T : (tko_value ?? tko_fallback) as T;
const tko_date = (tko_value: unknown): Date | null => tko_value ? new Date(String(tko_value)) : null;

export interface AIStore {
  createRun(input: CreateAIRunInput): Promise<AIRun>;
  completeRun(actor: PlatformActor, input: { runId: string; status: AIRun["status"]; output?: string | null; model?: string | null; inputTokens?: number | null; outputTokens?: number | null; costMicros?: number | null; error?: string | null; correlationId: string }): Promise<AIRun>;
  saveContextReferences(actor: PlatformActor, input: { runId: string; references: Array<Omit<AIContextReference, "id" | "tenantId" | "type" | "runId" | "createdAt">>; correlationId: string }): Promise<AIContextReference[]>;
  getRun(tenantId: string, runId: string): Promise<AIRun | null>;
  listRuns(tenantId: string): Promise<AIRun[]>;
  listContextReferences(tenantId: string, runId: string): Promise<AIContextReference[]>;
  createProposal(input: CreateAIToolProposalInput & { risk: AIToolProposal["risk"]; expiresAt: Date }): Promise<AIToolProposal>;
  getProposal(tenantId: string, proposalId: string): Promise<AIToolProposal | null>;
  listProposals(tenantId: string): Promise<AIToolProposal[]>;
  updateProposal(actor: PlatformActor, input: { proposalId: string; status: AIToolProposal["status"]; correlationId: string }): Promise<AIToolProposal>;
}

export class MemoryAIStore implements AIStore {
  private readonly tko_runs = new Map<string, AIRun>();
  private readonly tko_references = new Map<string, AIContextReference>();
  private readonly tko_proposals = new Map<string, AIToolProposal>();
  async createRun(tko_input: CreateAIRunInput): Promise<AIRun> { const tko_run: AIRun = { id: crypto.randomUUID(), tenantId: tko_input.actor.tenantId, type: "ai_run", requestedByMemberId: tko_input.actor.memberId, mode: tko_input.mode, prompt: tko_input.prompt, status: "running", model: null, output: null, inputTokens: null, outputTokens: null, costMicros: null, error: null, createdAt: new Date(), completedAt: null }; this.tko_runs.set(tko_run.id, tko_run); await this.tko_emit(tko_input.actor, "ai.run_started.v1", { runId: tko_run.id, mode: tko_run.mode }, "ai.run.started", "ai_run", tko_run.id, tko_input.correlationId); return tko_clone(tko_run); }
  async completeRun(tko_actor: PlatformActor, tko_input: Parameters<AIStore["completeRun"]>[1]): Promise<AIRun> { const tko_run = this.tko_requireRun(tko_actor.tenantId, tko_input.runId); Object.assign(tko_run, { status: tko_input.status, output: tko_input.output ?? null, model: tko_input.model ?? null, inputTokens: tko_input.inputTokens ?? null, outputTokens: tko_input.outputTokens ?? null, costMicros: tko_input.costMicros ?? null, error: tko_input.error ?? null, completedAt: new Date() }); await this.tko_emit(tko_actor, "ai.run_completed.v1", { runId: tko_run.id, status: tko_run.status }, "ai.run.completed", "ai_run", tko_run.id, tko_input.correlationId); return tko_clone(tko_run); }
  async saveContextReferences(tko_actor: PlatformActor, tko_input: Parameters<AIStore["saveContextReferences"]>[1]): Promise<AIContextReference[]> { this.tko_requireRun(tko_actor.tenantId, tko_input.runId); const tko_rows = tko_input.references.map(tko_reference => { const tko_value: AIContextReference = { id: crypto.randomUUID(), tenantId: tko_actor.tenantId, type: "ai_context_reference", runId: tko_input.runId, ...tko_reference, createdAt: new Date() }; this.tko_references.set(tko_value.id, tko_value); return tko_value; }); await this.tko_emit(tko_actor, "ai.context_resolved.v1", { runId: tko_input.runId, count: tko_rows.length }, "ai.context.resolved", "ai_run", tko_input.runId, tko_input.correlationId); return tko_rows.map(tko_clone); }
  async getRun(tko_tenantId: string, tko_runId: string): Promise<AIRun | null> { const tko_run = this.tko_runs.get(tko_runId); return tko_run?.tenantId === tko_tenantId ? tko_clone(tko_run) : null; }
  async listRuns(tko_tenantId: string): Promise<AIRun[]> { return Array.from(this.tko_runs.values()).filter(tko_run => tko_run.tenantId === tko_tenantId).map(tko_clone); }
  async listContextReferences(tko_tenantId: string, tko_runId: string): Promise<AIContextReference[]> { return Array.from(this.tko_references.values()).filter(tko_row => tko_row.tenantId === tko_tenantId && tko_row.runId === tko_runId).map(tko_clone); }
  async createProposal(tko_input: Parameters<AIStore["createProposal"]>[0]): Promise<AIToolProposal> { const tko_existing = Array.from(this.tko_proposals.values()).find(tko_row => tko_row.tenantId === tko_input.actor.tenantId && tko_row.idempotencyKey === tko_input.idempotencyKey); if (tko_existing) return tko_clone(tko_existing); const tko_value: AIToolProposal = { id: crypto.randomUUID(), tenantId: tko_input.actor.tenantId, type: "ai_tool_proposal", runId: tko_input.runId, toolName: tko_input.toolName, risk: tko_input.risk, input: tko_clone(tko_input.input), preview: tko_clone(tko_input.preview), idempotencyKey: tko_input.idempotencyKey, status: "proposed", proposedByMemberId: tko_input.actor.memberId, confirmedByMemberId: null, executedAt: null, expiresAt: tko_input.expiresAt, createdAt: new Date(), updatedAt: new Date() }; this.tko_proposals.set(tko_value.id, tko_value); await this.tko_emit(tko_input.actor, "ai.proposal_created.v1", { proposalId: tko_value.id, toolName: tko_value.toolName }, "ai.proposal.created", "ai_tool_proposal", tko_value.id, tko_input.correlationId); return tko_clone(tko_value); }
  async getProposal(tko_tenantId: string, tko_proposalId: string): Promise<AIToolProposal | null> { const tko_value = this.tko_proposals.get(tko_proposalId); return tko_value?.tenantId === tko_tenantId ? tko_clone(tko_value) : null; }
  async listProposals(tko_tenantId: string): Promise<AIToolProposal[]> { return Array.from(this.tko_proposals.values()).filter(tko_row => tko_row.tenantId === tko_tenantId).map(tko_clone); }
  async updateProposal(tko_actor: PlatformActor, tko_input: Parameters<AIStore["updateProposal"]>[1]): Promise<AIToolProposal> { const tko_value = this.tko_proposals.get(tko_input.proposalId); if (!tko_value || tko_value.tenantId !== tko_actor.tenantId) throw new Error("AI_PROPOSAL_NOT_FOUND"); if (tko_value.status !== "proposed" && tko_input.status === "confirmed") throw new Error("AI_PROPOSAL_NOT_CONFIRMABLE"); tko_value.status = tko_input.status; tko_value.confirmedByMemberId = tko_input.status === "confirmed" ? tko_actor.memberId : tko_value.confirmedByMemberId; tko_value.executedAt = tko_input.status === "executed" ? new Date() : tko_value.executedAt; tko_value.updatedAt = new Date(); await this.tko_emit(tko_actor, `ai.proposal_${tko_input.status}.v1`, { proposalId: tko_value.id }, `ai.proposal.${tko_input.status}`, "ai_tool_proposal", tko_value.id, tko_input.correlationId); return tko_clone(tko_value); }
  private tko_requireRun(tko_tenantId: string, tko_runId: string): AIRun { const tko_run = this.tko_runs.get(tko_runId); if (!tko_run || tko_run.tenantId !== tko_tenantId) throw new Error("AI_RUN_NOT_FOUND"); return tko_run; }
  private async tko_emit(tko_actor: PlatformActor, tko_eventType: string, tko_payload: Record<string, unknown>, tko_action: string, tko_resourceType: string, tko_resourceId: string, tko_correlationId: string): Promise<void> { await getPlatformStore().writeDurableMutation({ actor: tko_actor, tenantId: tko_actor.tenantId, eventType: tko_eventType, topic: "ai", payload: tko_payload, auditAction: tko_action, resourceType: tko_resourceType, resourceId: tko_resourceId, correlationId: tko_correlationId }); }
}

export class PostgresAIStore implements AIStore {
  private readonly tko_pool: pg.Pool;
  constructor(tko_url: string) { this.tko_pool = new pg.Pool({ connectionString: tko_url, max: 10 }); }
  async createRun(tko_input: CreateAIRunInput): Promise<AIRun> { return this.tko_tx(tko_input.actor, async tko_client => { const tko_row = (await tko_client.query("insert into ai_runs(id,tenant_id,requested_by_member_id,mode,prompt,status) values($1,$2,$3,$4,$5,'running') returning *", [crypto.randomUUID(), tko_input.actor.tenantId, tko_input.actor.memberId, tko_input.mode, tko_input.prompt])).rows[0]; const tko_run = this.tko_runRow(tko_row); await this.tko_emit(tko_client, tko_input.actor, "ai.run_started.v1", { runId: tko_run.id, mode: tko_run.mode }, "ai.run.started", "ai_run", tko_run.id, tko_input.correlationId); return tko_run; }); }
  async completeRun(tko_actor: PlatformActor, tko_input: Parameters<AIStore["completeRun"]>[1]): Promise<AIRun> { return this.tko_tx(tko_actor, async tko_client => { const tko_row = (await tko_client.query("update ai_runs set status=$3,output=$4,model=$5,input_tokens=$6,output_tokens=$7,cost_micros=$8,error=$9,completed_at=now() where tenant_id=$1 and id=$2 returning *", [tko_actor.tenantId, tko_input.runId, tko_input.status, tko_input.output ?? null, tko_input.model ?? null, tko_input.inputTokens ?? null, tko_input.outputTokens ?? null, tko_input.costMicros ?? null, tko_input.error ?? null])).rows[0]; if (!tko_row) throw new Error("AI_RUN_NOT_FOUND"); const tko_run = this.tko_runRow(tko_row); await this.tko_emit(tko_client, tko_actor, "ai.run_completed.v1", { runId: tko_run.id, status: tko_run.status }, "ai.run.completed", "ai_run", tko_run.id, tko_input.correlationId); return tko_run; }); }
  async saveContextReferences(tko_actor: PlatformActor, tko_input: Parameters<AIStore["saveContextReferences"]>[1]): Promise<AIContextReference[]> { return this.tko_tx(tko_actor, async tko_client => { const tko_rows: AIContextReference[] = []; for (const tko_reference of tko_input.references) { const tko_result = await tko_client.query("insert into ai_context_references(id,tenant_id,run_id,resource_kind,resource_id,label,locator) values($1,$2,$3,$4,$5,$6,$7) on conflict(tenant_id,run_id,resource_kind,resource_id) do update set label=excluded.label returning *", [crypto.randomUUID(), tko_actor.tenantId, tko_input.runId, tko_reference.resourceKind, tko_reference.resourceId, tko_reference.label, tko_reference.locator]); tko_rows.push(this.tko_referenceRow(tko_result.rows[0])); } await this.tko_emit(tko_client, tko_actor, "ai.context_resolved.v1", { runId: tko_input.runId, count: tko_rows.length }, "ai.context.resolved", "ai_run", tko_input.runId, tko_input.correlationId); return tko_rows; }); }
  async getRun(tko_tenantId: string, tko_runId: string): Promise<AIRun | null> { return this.tko_read(tko_tenantId, async tko_client => { const tko_result = await tko_client.query("select * from ai_runs where tenant_id=$1 and id=$2", [tko_tenantId, tko_runId]); return tko_result.rowCount ? this.tko_runRow(tko_result.rows[0]) : null; }); }
  async listRuns(tko_tenantId: string): Promise<AIRun[]> { return this.tko_read(tko_tenantId, async tko_client => (await tko_client.query("select * from ai_runs where tenant_id=$1 order by created_at desc", [tko_tenantId])).rows.map(this.tko_runRow)); }
  async listContextReferences(tko_tenantId: string, tko_runId: string): Promise<AIContextReference[]> { return this.tko_read(tko_tenantId, async tko_client => (await tko_client.query("select * from ai_context_references where tenant_id=$1 and run_id=$2", [tko_tenantId, tko_runId])).rows.map(this.tko_referenceRow)); }
  async createProposal(tko_input: Parameters<AIStore["createProposal"]>[0]): Promise<AIToolProposal> { return this.tko_tx(tko_input.actor, async tko_client => { const tko_result = await tko_client.query("insert into ai_tool_proposals(id,tenant_id,run_id,tool_name,risk,input_json,preview_json,idempotency_key,status,proposed_by_member_id,expires_at) values($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8,'proposed',$9,$10) on conflict(tenant_id,idempotency_key) do update set updated_at=now() returning *", [crypto.randomUUID(), tko_input.actor.tenantId, tko_input.runId, tko_input.toolName, tko_input.risk, JSON.stringify(tko_input.input), JSON.stringify(tko_input.preview), tko_input.idempotencyKey, tko_input.actor.memberId, tko_input.expiresAt]); const tko_value = this.tko_proposalRow(tko_result.rows[0]); await this.tko_emit(tko_client, tko_input.actor, "ai.proposal_created.v1", { proposalId: tko_value.id, toolName: tko_value.toolName }, "ai.proposal.created", "ai_tool_proposal", tko_value.id, tko_input.correlationId); return tko_value; }); }
  async getProposal(tko_tenantId: string, tko_proposalId: string): Promise<AIToolProposal | null> { return this.tko_read(tko_tenantId, async tko_client => { const tko_result = await tko_client.query("select * from ai_tool_proposals where tenant_id=$1 and id=$2", [tko_tenantId, tko_proposalId]); return tko_result.rowCount ? this.tko_proposalRow(tko_result.rows[0]) : null; }); }
  async listProposals(tko_tenantId: string): Promise<AIToolProposal[]> { return this.tko_read(tko_tenantId, async tko_client => (await tko_client.query("select * from ai_tool_proposals where tenant_id=$1 order by created_at desc", [tko_tenantId])).rows.map(this.tko_proposalRow)); }
  async updateProposal(tko_actor: PlatformActor, tko_input: Parameters<AIStore["updateProposal"]>[1]): Promise<AIToolProposal> { return this.tko_tx(tko_actor, async tko_client => { const tko_result = await tko_client.query("update ai_tool_proposals set status=$3,confirmed_by_member_id=case when $3='confirmed' then $4 else confirmed_by_member_id end,executed_at=case when $3='executed' then now() else executed_at end,updated_at=now() where tenant_id=$1 and id=$2 and ($3 <> 'confirmed' or status='proposed') returning *", [tko_actor.tenantId, tko_input.proposalId, tko_input.status, tko_actor.memberId]); if (!tko_result.rowCount) throw new Error("AI_PROPOSAL_NOT_CONFIRMABLE"); const tko_value = this.tko_proposalRow(tko_result.rows[0]); await this.tko_emit(tko_client, tko_actor, `ai.proposal_${tko_input.status}.v1`, { proposalId: tko_value.id }, `ai.proposal.${tko_input.status}`, "ai_tool_proposal", tko_value.id, tko_input.correlationId); return tko_value; }); }
  private async tko_read<T>(tko_tenantId: string, tko_operation: (tko_client: pg.PoolClient) => Promise<T>): Promise<T> { const tko_client = await this.tko_pool.connect(); try { await tko_client.query("begin"); await tko_client.query("select set_config('app.tenant_id',$1,true)", [tko_tenantId]); const tko_value = await tko_operation(tko_client); await tko_client.query("commit"); return tko_value; } catch (tko_error) { await tko_client.query("rollback"); throw tko_error; } finally { tko_client.release(); } }
  private tko_tx<T>(tko_actor: PlatformActor, tko_operation: (tko_client: pg.PoolClient) => Promise<T>): Promise<T> { return this.tko_read(tko_actor.tenantId, tko_operation); }
  private async tko_emit(tko_client: pg.PoolClient, tko_actor: PlatformActor, tko_eventType: string, tko_payload: Record<string, unknown>, tko_action: string, tko_resourceType: string, tko_resourceId: string, tko_correlationId: string): Promise<void> { await tko_client.query("insert into audit_logs(id,tenant_id,actor_auth_subject,action,resource_type,resource_id,correlation_id,metadata_json) values(gen_random_uuid(),$1,$2,$3,$4,$5,$6,'{}'::jsonb)", [tko_actor.tenantId, tko_actor.authSubject, tko_action, tko_resourceType, tko_resourceId, tko_correlationId]); await tko_client.query("insert into outbox(id,event_id,tenant_id,topic,event_type,payload_json,actor_auth_subject,correlation_id,status,attempts,available_at) values($1,$2,$3,'ai',$4,$5::jsonb,$6,$7,'pending',0,now())", [crypto.randomUUID(), crypto.randomUUID(), tko_actor.tenantId, tko_eventType, JSON.stringify(tko_payload), tko_actor.authSubject, tko_correlationId]); }
  private tko_runRow = (tko_row: TkoRow): AIRun => ({ id: String(tko_row.id), tenantId: String(tko_row.tenant_id), type: "ai_run", requestedByMemberId: String(tko_row.requested_by_member_id), mode: tko_row.mode as AIRun["mode"], prompt: String(tko_row.prompt), status: tko_row.status as AIRun["status"], model: tko_row.model ? String(tko_row.model) : null, output: tko_row.output ? String(tko_row.output) : null, inputTokens: tko_row.input_tokens === null ? null : Number(tko_row.input_tokens), outputTokens: tko_row.output_tokens === null ? null : Number(tko_row.output_tokens), costMicros: tko_row.cost_micros === null ? null : Number(tko_row.cost_micros), error: tko_row.error ? String(tko_row.error) : null, createdAt: new Date(String(tko_row.created_at)), completedAt: tko_date(tko_row.completed_at) });
  private tko_referenceRow = (tko_row: TkoRow): AIContextReference => ({ id: String(tko_row.id), tenantId: String(tko_row.tenant_id), type: "ai_context_reference", runId: String(tko_row.run_id), resourceKind: tko_row.resource_kind as AIContextReference["resourceKind"], resourceId: String(tko_row.resource_id), label: String(tko_row.label), locator: String(tko_row.locator), createdAt: new Date(String(tko_row.created_at)) });
  private tko_proposalRow = (tko_row: TkoRow): AIToolProposal => ({ id: String(tko_row.id), tenantId: String(tko_row.tenant_id), type: "ai_tool_proposal", runId: String(tko_row.run_id), toolName: tko_row.tool_name as AIToolProposal["toolName"], risk: tko_row.risk as AIToolProposal["risk"], input: tko_json(tko_row.input_json, {}), preview: tko_json(tko_row.preview_json, {}), idempotencyKey: String(tko_row.idempotency_key), status: tko_row.status as AIToolProposal["status"], proposedByMemberId: String(tko_row.proposed_by_member_id), confirmedByMemberId: tko_row.confirmed_by_member_id ? String(tko_row.confirmed_by_member_id) : null, executedAt: tko_date(tko_row.executed_at), expiresAt: new Date(String(tko_row.expires_at)), createdAt: new Date(String(tko_row.created_at)), updatedAt: new Date(String(tko_row.updated_at)) });
}

let tko_store: AIStore | null = null;
export function getAIStore(): AIStore { if (tko_store) return tko_store; tko_store = tko_config.postgresUrl ? new PostgresAIStore(tko_config.postgresUrl) : new MemoryAIStore(); return tko_store; }
export function setAIStoreForTests(tko_next: AIStore | null): void { tko_store = tko_next; }
