import type { PlatformActor } from "../../contracts/src/platform";
import type { CRMActivity, CRMCompany, CRMContact, CRMConversionResult, CRMDeal, CRMDealBoard, CRMDealHandoff, CRMEntityLink, CRMLead, CRMPipeline, CRMPipelineStage, ConvertLeadInput, CreateLeadInput, UpdateCompanyInput, UpdateContactInput, UpdateLeadInput } from "../../contracts/src/crm";
import { tko_config } from "../../config/src/tasko-config";
import { getPlatformStore } from "./platform-store";
import { PostgresCRMStore } from "./postgres-crm-store";

export interface CRMStore {
  listLeads(tenantId: string): Promise<CRMLead[]>;
  getLead(tenantId: string, leadId: string): Promise<CRMLead | null>;
  createLead(input: CreateLeadInput): Promise<CRMLead>;
  listCompanies(tenantId: string): Promise<CRMCompany[]>;
  getCompany(tenantId: string, companyId: string): Promise<CRMCompany | null>;
  createCompany(actor: PlatformActor, input: { name: string; domain?: string; website?: string; industry?: string; employeeRange?: string; country?: string; lifecycleStatus?: string; tags?: string[]; correlationId: string }): Promise<CRMCompany>;
  listContacts(tenantId: string, companyId?: string): Promise<CRMContact[]>;
  createContact(actor: PlatformActor, input: { companyId?: string | null; firstName: string; lastName: string; title?: string; emails?: string[]; phones?: string[]; tags?: string[]; correlationId: string }): Promise<CRMContact>;
  listPipelines(tenantId: string): Promise<CRMPipeline[]>;
  listStages(tenantId: string, pipelineId: string): Promise<CRMPipelineStage[]>;
  createPipeline(actor: PlatformActor, input: { name: string; stages?: Array<{ name: string; probabilityDefault: number; category: CRMPipelineStage["category"] }>; correlationId: string }): Promise<{ pipeline: CRMPipeline; stages: CRMPipelineStage[] }>;
  listDeals(tenantId: string, pipelineId?: string, companyId?: string): Promise<CRMDeal[]>;
  getDeal(tenantId: string, dealId: string): Promise<CRMDeal | null>;
  createDeal(actor: PlatformActor, input: { companyId?: string | null; pipelineId: string; stageId: string; name: string; amountCents?: number | null; currency?: string; probability?: number; expectedCloseDate?: Date | null; source?: string; nextStep?: string; correlationId: string }): Promise<CRMDeal>;
  moveDeal(actor: PlatformActor, input: { dealId: string; stageId: string; lossReason?: string; correlationId: string }): Promise<CRMDeal>;
  updateLead(actor: PlatformActor, input: UpdateLeadInput): Promise<CRMLead>;
  updateCompany(actor: PlatformActor, input: UpdateCompanyInput): Promise<CRMCompany>;
  updateContact(actor: PlatformActor, input: UpdateContactInput): Promise<CRMContact>;
  dealBoard(tenantId: string, pipelineId: string): Promise<CRMDealBoard>;
  addActivity(actor: PlatformActor, input: { entityType: CRMActivity["entityType"]; entityId: string; activityType: CRMActivity["activityType"]; subject?: string; body?: string; metadata?: Record<string, unknown>; correlationId: string }): Promise<CRMActivity>;
  listActivities(tenantId: string, entityType: CRMActivity["entityType"], entityId: string): Promise<CRMActivity[]>;
  linkEntity(actor: PlatformActor, input: { sourceType: CRMEntityLink["sourceType"]; sourceId: string; targetType: CRMEntityLink["targetType"]; targetId: string; relationType: CRMEntityLink["relationType"]; correlationId: string }): Promise<CRMEntityLink>;
  listLinks(tenantId: string, sourceType: CRMEntityLink["sourceType"], sourceId: string): Promise<CRMEntityLink[]>;
  getDealHandoff(tenantId: string, dealId: string): Promise<CRMDealHandoff | null>;
  ensureDealHandoff(actor: PlatformActor, input: { dealId: string; correlationId: string }): Promise<CRMDealHandoff>;
  completeDealHandoff(actor: PlatformActor, input: { dealId: string; deliveryProjectId: string; deliveryChannelId: string; correlationId: string }): Promise<CRMDealHandoff>;
  convertLead(input: ConvertLeadInput): Promise<CRMConversionResult>;
}

const tko_clone = <T>(value: T): T => structuredClone(value);
const tko_now = () => new Date();
const tko_cleanTags = (tags: string[] = []) => Array.from(new Set(tags.map(tag => tag.trim()).filter(Boolean))).slice(0, 50);

export class MemoryCRMStore implements CRMStore {
  private readonly tko_leads = new Map<string, CRMLead>();
  private readonly tko_companies = new Map<string, CRMCompany>();
  private readonly tko_contacts = new Map<string, CRMContact>();
  private readonly tko_pipelines = new Map<string, CRMPipeline>();
  private readonly tko_stages = new Map<string, CRMPipelineStage>();
  private readonly tko_deals = new Map<string, CRMDeal>();
  private readonly tko_activities = new Map<string, CRMActivity>();
  private readonly tko_links = new Map<string, CRMEntityLink>();
  private readonly tko_handoffs = new Map<string, CRMDealHandoff>();

  async listLeads(tenantId: string) { return Array.from(this.tko_leads.values()).filter(item => item.tenantId === tenantId).sort((a, b) => b.updatedAt.getTime() - a.updatedAt.getTime()).map(tko_clone); }
  async getLead(tenantId: string, leadId: string) { const tko_item = this.tko_leads.get(leadId); return tko_item?.tenantId === tenantId ? tko_clone(tko_item) : null; }
  async listCompanies(tenantId: string) { return Array.from(this.tko_companies.values()).filter(item => item.tenantId === tenantId).sort((a, b) => a.name.localeCompare(b.name)).map(tko_clone); }
  async getCompany(tenantId: string, companyId: string) { const tko_item = this.tko_companies.get(companyId); return tko_item?.tenantId === tenantId ? tko_clone(tko_item) : null; }
  async listContacts(tenantId: string, companyId?: string) { return Array.from(this.tko_contacts.values()).filter(item => item.tenantId === tenantId && (!companyId || item.companyId === companyId)).map(tko_clone); }
  async listPipelines(tenantId: string) { return Array.from(this.tko_pipelines.values()).filter(item => item.tenantId === tenantId && item.active).map(tko_clone); }
  async listStages(tenantId: string, pipelineId: string) { return Array.from(this.tko_stages.values()).filter(item => item.tenantId === tenantId && item.pipelineId === pipelineId).sort((a,b) => a.sortOrder-b.sortOrder).map(tko_clone); }
  async listDeals(tenantId: string, pipelineId?: string, companyId?: string) { return Array.from(this.tko_deals.values()).filter(item => item.tenantId === tenantId && (!pipelineId || item.pipelineId === pipelineId) && (!companyId || item.companyId === companyId)).map(tko_clone); }
  async getDeal(tenantId: string, dealId: string) { const tko_item = this.tko_deals.get(dealId); return tko_item?.tenantId === tenantId ? tko_clone(tko_item) : null; }
  async listActivities(tenantId: string, entityType: CRMActivity["entityType"], entityId: string) { return Array.from(this.tko_activities.values()).filter(item => item.tenantId === tenantId && item.entityType === entityType && item.entityId === entityId).sort((a,b) => b.createdAt.getTime()-a.createdAt.getTime()).map(tko_clone); }
  async listLinks(tenantId: string, sourceType: CRMEntityLink["sourceType"], sourceId: string) { return Array.from(this.tko_links.values()).filter(item => item.tenantId === tenantId && item.sourceType === sourceType && item.sourceId === sourceId).map(tko_clone); }
  async getDealHandoff(tenantId: string, dealId: string) { const tko_item = this.tko_handoffs.get(dealId); return tko_item?.tenantId === tenantId ? tko_clone(tko_item) : null; }

  async createLead(input: CreateLeadInput) {
    const tko_now1 = tko_now(); const tko_lead: CRMLead = { id: crypto.randomUUID(), tenantId: input.actor.tenantId, type: "crm_lead", visibility: "internal", ownerMemberId: input.actor.memberId, firstName: input.firstName.trim(), lastName: input.lastName.trim(), companyName: input.companyName?.trim() ?? "", jobTitle: input.jobTitle?.trim() ?? "", email: input.email?.trim().toLowerCase() ?? "", phone: input.phone?.trim() ?? "", website: input.website?.trim() ?? "", country: input.country?.trim() ?? "", source: input.source?.trim() ?? "", status: input.status ?? "new", score: input.score ?? null, tags: tko_cleanTags(input.tags), notes: input.notes?.trim() ?? "", nextFollowUpAt: input.nextFollowUpAt ?? null, customFields: tko_clone(input.customFields ?? {}), convertedAt: null, convertedCompanyId: null, convertedContactId: null, convertedDealId: null, conversionKey: null, createdAt: tko_now1, updatedAt: tko_now1 };
    this.tko_leads.set(tko_lead.id, tko_lead); await this.tko_emit(input.actor, "crm.lead_created.v1", "crm.lead", { leadId: tko_lead.id }, "crm.lead.created", "crm_lead", tko_lead.id, input.correlationId); return tko_clone(tko_lead);
  }
  async createCompany(actor: PlatformActor, input: { name: string; domain?: string; website?: string; industry?: string; employeeRange?: string; country?: string; lifecycleStatus?: string; tags?: string[]; correlationId: string }) {
    const tko_existing = Array.from(this.tko_companies.values()).find(item => item.tenantId === actor.tenantId && item.name.toLowerCase() === input.name.trim().toLowerCase()); if (tko_existing) return tko_clone(tko_existing);
    const tko_now1 = tko_now(); const tko_company: CRMCompany = { id: crypto.randomUUID(), tenantId: actor.tenantId, type: "crm_company", visibility: "internal", name: input.name.trim(), domain: input.domain?.trim().toLowerCase() ?? "", website: input.website?.trim() ?? "", industry: input.industry?.trim() ?? "", employeeRange: input.employeeRange?.trim() ?? "", country: input.country?.trim() ?? "", ownerMemberId: actor.memberId, lifecycleStatus: input.lifecycleStatus?.trim() ?? "prospect", tags: tko_cleanTags(input.tags), customFields: {}, createdAt: tko_now1, updatedAt: tko_now1 };
    this.tko_companies.set(tko_company.id, tko_company); await this.tko_emit(actor, "crm.company_created.v1", "crm.company", { companyId: tko_company.id }, "crm.company.created", "crm_company", tko_company.id, input.correlationId); return tko_clone(tko_company);
  }
  async createContact(actor: PlatformActor, input: { companyId?: string | null; firstName: string; lastName: string; title?: string; emails?: string[]; phones?: string[]; tags?: string[]; correlationId: string }) {
    if (input.companyId && !(await this.getCompany(actor.tenantId, input.companyId))) throw new Error("CRM_COMPANY_NOT_FOUND"); const tko_now1 = tko_now(); const tko_item: CRMContact = { id: crypto.randomUUID(), tenantId: actor.tenantId, type: "crm_contact", visibility: "internal", companyId: input.companyId ?? null, firstName: input.firstName.trim(), lastName: input.lastName.trim(), title: input.title?.trim() ?? "", emails: Array.from(new Set((input.emails ?? []).map(v => v.trim().toLowerCase()).filter(Boolean))), phones: Array.from(new Set((input.phones ?? []).map(v => v.trim()).filter(Boolean))), ownerMemberId: actor.memberId, tags: tko_cleanTags(input.tags), customFields: {}, createdAt: tko_now1, updatedAt: tko_now1 };
    this.tko_contacts.set(tko_item.id,tko_item); await this.tko_emit(actor,"crm.contact_created.v1","crm.contact",{contactId:tko_item.id,companyId:tko_item.companyId},"crm.contact.created","crm_contact",tko_item.id,input.correlationId); return tko_clone(tko_item);
  }
  async createPipeline(actor: PlatformActor, input: { name: string; stages?: Array<{ name: string; probabilityDefault: number; category: CRMPipelineStage["category"] }>; correlationId: string }) {
    const tko_pipeline: CRMPipeline = { id: crypto.randomUUID(), tenantId: actor.tenantId, type: "crm_pipeline", visibility: "internal", name: input.name.trim(), active: true, createdAt: tko_now() }; this.tko_pipelines.set(tko_pipeline.id,tko_pipeline);
    const tko_template = input.stages ?? [{name:"Discovery",probabilityDefault:20,category:"open" as const},{name:"Proposal",probabilityDefault:60,category:"open" as const},{name:"Won",probabilityDefault:100,category:"won" as const},{name:"Lost",probabilityDefault:0,category:"lost" as const}];
    const tko_stages = tko_template.map((stage,index): CRMPipelineStage => ({id:crypto.randomUUID(),tenantId:actor.tenantId,type:"crm_pipeline_stage",visibility:"internal",pipelineId:tko_pipeline.id,name:stage.name.trim(),sortOrder:(index+1)*100,probabilityDefault:stage.probabilityDefault,category:stage.category})); tko_stages.forEach(stage=>this.tko_stages.set(stage.id,stage)); await this.tko_emit(actor,"crm.pipeline_created.v1","crm.pipeline",{pipelineId:tko_pipeline.id},"crm.pipeline.created","crm_pipeline",tko_pipeline.id,input.correlationId); return { pipeline:tko_clone(tko_pipeline),stages:tko_stages.map(tko_clone) };
  }
  async createDeal(actor: PlatformActor, input: { companyId?: string | null; pipelineId: string; stageId: string; name: string; amountCents?: number | null; currency?: string; probability?: number; expectedCloseDate?: Date | null; source?: string; nextStep?: string; correlationId: string }) {
    const tko_pipeline = this.tko_pipelines.get(input.pipelineId); const tko_stage = this.tko_stages.get(input.stageId); if (!tko_pipeline || tko_pipeline.tenantId !== actor.tenantId || !tko_stage || tko_stage.pipelineId !== tko_pipeline.id) throw new Error("CRM_PIPELINE_STAGE_NOT_FOUND"); if (input.companyId && !(await this.getCompany(actor.tenantId,input.companyId))) throw new Error("CRM_COMPANY_NOT_FOUND"); const tko_now1=tko_now(); const tko_deal: CRMDeal={id:crypto.randomUUID(),tenantId:actor.tenantId,type:"crm_deal",visibility:"internal",companyId:input.companyId??null,pipelineId:tko_pipeline.id,stageId:tko_stage.id,name:input.name.trim(),amountCents:input.amountCents??null,currency:(input.currency??"USD").toUpperCase(),probability:input.probability??tko_stage.probabilityDefault,ownerMemberId:actor.memberId,expectedCloseDate:input.expectedCloseDate??null,source:input.source?.trim()??"",nextStep:input.nextStep?.trim()??"",wonAt:tko_stage.category==="won"?tko_now1:null,lostAt:tko_stage.category==="lost"?tko_now1:null,lossReason:"",customFields:{},createdAt:tko_now1,updatedAt:tko_now1}; this.tko_deals.set(tko_deal.id,tko_deal); await this.tko_emit(actor,"crm.deal_created.v1","crm.deal",{dealId:tko_deal.id,pipelineId:tko_deal.pipelineId,stageId:tko_deal.stageId},"crm.deal.created","crm_deal",tko_deal.id,input.correlationId); return tko_clone(tko_deal);
  }
  async moveDeal(actor: PlatformActor, input: { dealId: string; stageId: string; lossReason?: string; correlationId: string }) { const tko_deal=this.tko_deals.get(input.dealId); const tko_stage=this.tko_stages.get(input.stageId); if(!tko_deal||tko_deal.tenantId!==actor.tenantId||!tko_stage||tko_stage.tenantId!==actor.tenantId||tko_stage.pipelineId!==tko_deal.pipelineId) throw new Error("CRM_DEAL_OR_STAGE_NOT_FOUND"); const tko_before=tko_deal.stageId; const tko_now1=tko_now(); tko_deal.stageId=tko_stage.id; tko_deal.probability=tko_stage.probabilityDefault; tko_deal.wonAt=tko_stage.category==="won"?tko_now1:null; tko_deal.lostAt=tko_stage.category==="lost"?tko_now1:null; tko_deal.lossReason=tko_stage.category==="lost"?(input.lossReason?.trim()??""):""; tko_deal.updatedAt=tko_now1; this.tko_deals.set(tko_deal.id,tko_deal); await this.addActivity(actor,{entityType:"deal",entityId:tko_deal.id,activityType:"status_change",subject:`Moved to ${tko_stage.name}`,metadata:{beforeStageId:tko_before,afterStageId:tko_stage.id,...(tko_deal.lossReason?{lossReason:tko_deal.lossReason}:{})},correlationId:input.correlationId}); await this.tko_emit(actor,tko_stage.category==="won"?"crm.deal_won.v1":"crm.deal_stage_changed.v1","crm.deal",{dealId:tko_deal.id,beforeStageId:tko_before,afterStageId:tko_stage.id,pipelineId:tko_deal.pipelineId,...(tko_deal.lossReason?{lossReason:tko_deal.lossReason}:{})},tko_stage.category==="won"?"crm.deal.won":"crm.deal.stage_changed","crm_deal",tko_deal.id,input.correlationId); return tko_clone(tko_deal); }
  async dealBoard(tenantId: string,pipelineId: string) { const tko_pipeline=this.tko_pipelines.get(pipelineId); if(!tko_pipeline||tko_pipeline.tenantId!==tenantId) throw new Error("CRM_PIPELINE_NOT_FOUND"); const tko_stages=await this.listStages(tenantId,pipelineId); const tko_deals=await this.listDeals(tenantId,pipelineId); const tko_totalsByStage=Object.fromEntries(tko_stages.map(stage=>[stage.id,{amountCents:0,weightedAmountCents:0}])); for(const tko_deal of tko_deals){const tko_total=tko_totalsByStage[tko_deal.stageId]; if(tko_total&&tko_deal.amountCents!==null){tko_total.amountCents+=tko_deal.amountCents; tko_total.weightedAmountCents+=Math.round(tko_deal.amountCents*tko_deal.probability/100);}} return {pipeline:tko_clone(tko_pipeline),stages: tko_stages,deals: tko_deals,totalsByStage: tko_totalsByStage}; }
  async updateLead(actor: PlatformActor, input: UpdateLeadInput) { const tko_lead=this.tko_leads.get(input.leadId); if(!tko_lead||tko_lead.tenantId!==actor.tenantId) throw new Error("CRM_LEAD_NOT_FOUND"); if((input.status as string)==="converted") throw new Error("CRM_LEAD_STATUS_CONVERTED_REQUIRES_CONVERSION"); const tko_beforeStatus=tko_lead.status; if(input.ownerMemberId!==undefined&&input.ownerMemberId.trim()) tko_lead.ownerMemberId=input.ownerMemberId.trim(); if(input.firstName!==undefined) tko_lead.firstName=input.firstName.trim(); if(input.lastName!==undefined) tko_lead.lastName=input.lastName.trim(); if(input.companyName!==undefined) tko_lead.companyName=input.companyName.trim(); if(input.jobTitle!==undefined) tko_lead.jobTitle=input.jobTitle.trim(); if(input.email!==undefined) tko_lead.email=input.email.trim().toLowerCase(); if(input.phone!==undefined) tko_lead.phone=input.phone.trim(); if(input.website!==undefined) tko_lead.website=input.website.trim(); if(input.country!==undefined) tko_lead.country=input.country.trim(); if(input.source!==undefined) tko_lead.source=input.source.trim(); if(input.status!==undefined) tko_lead.status=input.status; if(input.score!==undefined) tko_lead.score=input.score; if(input.tags!==undefined) tko_lead.tags=tko_cleanTags(input.tags); if(input.notes!==undefined) tko_lead.notes=input.notes.trim(); if(input.nextFollowUpAt!==undefined) tko_lead.nextFollowUpAt=input.nextFollowUpAt; if(input.customFields!==undefined) tko_lead.customFields=tko_clone(input.customFields); tko_lead.updatedAt=tko_now(); this.tko_leads.set(tko_lead.id,tko_lead); if(input.status!==undefined&&input.status!==tko_beforeStatus) await this.addActivity(actor,{entityType:"lead",entityId:tko_lead.id,activityType:"status_change",subject:`Status changed to ${input.status}`,metadata:{beforeStatus: tko_beforeStatus,afterStatus:input.status},correlationId:input.correlationId}); await this.tko_emit(actor,"crm.lead_updated.v1","crm.lead",{leadId:tko_lead.id},"crm.lead.updated","crm_lead",tko_lead.id,input.correlationId); return tko_clone(tko_lead); }
  async updateCompany(actor: PlatformActor, input: UpdateCompanyInput) { const tko_company=this.tko_companies.get(input.companyId); if(!tko_company||tko_company.tenantId!==actor.tenantId) throw new Error("CRM_COMPANY_NOT_FOUND"); if(input.ownerMemberId!==undefined&&input.ownerMemberId.trim()) tko_company.ownerMemberId=input.ownerMemberId.trim(); if(input.name!==undefined) tko_company.name=input.name.trim(); if(input.domain!==undefined) tko_company.domain=input.domain.trim().toLowerCase(); if(input.website!==undefined) tko_company.website=input.website.trim(); if(input.industry!==undefined) tko_company.industry=input.industry.trim(); if(input.employeeRange!==undefined) tko_company.employeeRange=input.employeeRange.trim(); if(input.country!==undefined) tko_company.country=input.country.trim(); if(input.lifecycleStatus!==undefined) tko_company.lifecycleStatus=input.lifecycleStatus.trim(); if(input.tags!==undefined) tko_company.tags=tko_cleanTags(input.tags); if(input.customFields!==undefined) tko_company.customFields=tko_clone(input.customFields); tko_company.updatedAt=tko_now(); this.tko_companies.set(tko_company.id,tko_company); await this.tko_emit(actor,"crm.company_updated.v1","crm.company",{companyId:tko_company.id},"crm.company.updated","crm_company",tko_company.id,input.correlationId); return tko_clone(tko_company); }
  async updateContact(actor: PlatformActor, input: UpdateContactInput) { const tko_contact=this.tko_contacts.get(input.contactId); if(!tko_contact||tko_contact.tenantId!==actor.tenantId) throw new Error("CRM_CONTACT_NOT_FOUND"); if(input.companyId!==undefined&&input.companyId&&!(await this.getCompany(actor.tenantId,input.companyId))) throw new Error("CRM_COMPANY_NOT_FOUND"); if(input.ownerMemberId!==undefined&&input.ownerMemberId.trim()) tko_contact.ownerMemberId=input.ownerMemberId.trim(); if(input.companyId!==undefined) tko_contact.companyId=input.companyId; if(input.firstName!==undefined) tko_contact.firstName=input.firstName.trim(); if(input.lastName!==undefined) tko_contact.lastName=input.lastName.trim(); if(input.title!==undefined) tko_contact.title=input.title.trim(); if(input.emails!==undefined) tko_contact.emails=Array.from(new Set(input.emails.map(v=>v.trim().toLowerCase()).filter(Boolean))); if(input.phones!==undefined) tko_contact.phones=Array.from(new Set(input.phones.map(v=>v.trim()).filter(Boolean))); if(input.tags!==undefined) tko_contact.tags=tko_cleanTags(input.tags); if(input.customFields!==undefined) tko_contact.customFields=tko_clone(input.customFields); tko_contact.updatedAt=tko_now(); this.tko_contacts.set(tko_contact.id,tko_contact); await this.tko_emit(actor,"crm.contact_updated.v1","crm.contact",{contactId:tko_contact.id,companyId:tko_contact.companyId},"crm.contact.updated","crm_contact",tko_contact.id,input.correlationId); return tko_clone(tko_contact); }
  async addActivity(actor: PlatformActor,input: { entityType: CRMActivity["entityType"]; entityId: string; activityType: CRMActivity["activityType"]; subject?: string; body?: string; metadata?: Record<string, unknown>; correlationId: string }) { const tko_activity:CRMActivity={id:crypto.randomUUID(),tenantId:actor.tenantId,type:"crm_activity",visibility:"internal",entityType:input.entityType,entityId:input.entityId,activityType:input.activityType,subject:input.subject?.trim()??"",body:input.body?.trim()??"",metadata:tko_clone(input.metadata??{}),createdByMemberId:actor.memberId,createdAt:tko_now()}; this.tko_activities.set(tko_activity.id,tko_activity); await this.tko_emit(actor,"crm.activity_created.v1","crm.activity",{activityId:tko_activity.id,entityType:tko_activity.entityType,entityId:tko_activity.entityId},"crm.activity.created","crm_activity",tko_activity.id,input.correlationId); return tko_clone(tko_activity); }
  async linkEntity(actor: PlatformActor,input: { sourceType: CRMEntityLink["sourceType"]; sourceId: string; targetType: CRMEntityLink["targetType"]; targetId: string; relationType: CRMEntityLink["relationType"]; correlationId: string }) { const tko_key=[actor.tenantId,input.sourceType,input.sourceId,input.targetType,input.targetId,input.relationType].join(":"); const tko_existing=this.tko_links.get(tko_key); if(tko_existing) return tko_clone(tko_existing); const tko_link:CRMEntityLink={id:crypto.randomUUID(),tenantId:actor.tenantId,type:"crm_entity_link",visibility:"internal",sourceType:input.sourceType,sourceId:input.sourceId,targetType:input.targetType,targetId:input.targetId,relationType:input.relationType,createdAt:tko_now()}; this.tko_links.set(tko_key,tko_link); await this.tko_emit(actor,"crm.entity_linked.v1","crm.link",{sourceType:tko_link.sourceType,sourceId:tko_link.sourceId,targetType:tko_link.targetType,targetId:tko_link.targetId},"crm.entity.linked","crm_entity_link",tko_link.id,input.correlationId); return tko_clone(tko_link); }
  async ensureDealHandoff(actor: PlatformActor, input: { dealId: string; correlationId: string }) { const tko_deal = await this.getDeal(actor.tenantId, input.dealId); if (!tko_deal) throw new Error("CRM_DEAL_NOT_FOUND"); if (!tko_deal.wonAt) throw new Error("CRM_DEAL_NOT_WON"); const tko_existing = this.tko_handoffs.get(tko_deal.id); if (tko_existing) return tko_clone(tko_existing); const tko_handoff: CRMDealHandoff = { id: tko_deal.id, dealId: tko_deal.id, tenantId: actor.tenantId, type: "crm_deal_handoff", visibility: "internal", deliveryProjectId: null, deliveryChannelId: null, status: "pending", createdAt: tko_now(), completedAt: null }; this.tko_handoffs.set(tko_deal.id, tko_handoff); await this.tko_emit(actor, "crm.deal_handoff_requested.v1", "crm.deal", { dealId: tko_deal.id }, "crm.deal.handoff.requested", "crm_deal", tko_deal.id, input.correlationId); return tko_clone(tko_handoff); }
  async completeDealHandoff(actor: PlatformActor, input: { dealId: string; deliveryProjectId: string; deliveryChannelId: string; correlationId: string }) { const tko_handoff = await this.ensureDealHandoff(actor, input); if (tko_handoff.status === "completed") return tko_handoff; const tko_completed: CRMDealHandoff = { ...tko_handoff, deliveryProjectId: input.deliveryProjectId, deliveryChannelId: input.deliveryChannelId, status: "completed", completedAt: tko_now() }; this.tko_handoffs.set(input.dealId, tko_completed); await this.tko_emit(actor, "crm.deal_handoff_completed.v1", "crm.deal", { dealId: input.dealId, deliveryProjectId: input.deliveryProjectId, deliveryChannelId: input.deliveryChannelId }, "crm.deal.handoff.completed", "crm_deal", input.dealId, input.correlationId); return tko_clone(tko_completed); }
  async convertLead(input: ConvertLeadInput): Promise<CRMConversionResult> { const tko_lead=this.tko_leads.get(input.leadId); if(!tko_lead||tko_lead.tenantId!==input.actor.tenantId) throw new Error("CRM_LEAD_NOT_FOUND"); if(tko_lead.convertedAt){const tko_company=tko_lead.convertedCompanyId?this.tko_companies.get(tko_lead.convertedCompanyId):undefined;const tko_contact=tko_lead.convertedContactId?this.tko_contacts.get(tko_lead.convertedContactId):undefined;const tko_deal=tko_lead.convertedDealId?this.tko_deals.get(tko_lead.convertedDealId):undefined;if(!tko_company||!tko_contact)throw new Error("CRM_CONVERSION_INTEGRITY_ERROR");return {lead:tko_clone(tko_lead),company:tko_clone(tko_company),contact:tko_clone(tko_contact),deal:tko_deal?tko_clone(tko_deal):null,activities:await this.listActivities(tko_lead.tenantId,"lead",tko_lead.id),idempotent:true};} if(tko_lead.status!=="qualified")throw new Error("CRM_LEAD_NOT_QUALIFIED"); const tko_company=input.companyId?await this.getCompany(tko_lead.tenantId,input.companyId):await this.createCompany(input.actor,{name:tko_lead.companyName||`${tko_lead.firstName} ${tko_lead.lastName} Company`,website:tko_lead.website,country:tko_lead.country,correlationId:input.correlationId}); if(!tko_company)throw new Error("CRM_COMPANY_NOT_FOUND"); const tko_contact=input.contactId?(await this.listContacts(tko_lead.tenantId)).find(c=>c.id===input.contactId)??null:await this.createContact(input.actor,{companyId:tko_company.id,firstName:tko_lead.firstName,lastName:tko_lead.lastName,title:tko_lead.jobTitle,emails:tko_lead.email?[tko_lead.email]:[],phones:tko_lead.phone?[tko_lead.phone]:[],tags:tko_lead.tags,correlationId:input.correlationId}); if(!tko_contact)throw new Error("CRM_CONTACT_NOT_FOUND"); const tko_deal=input.createDeal?await this.createDeal(input.actor,{companyId:tko_company.id,pipelineId:input.pipelineId??"",stageId:input.stageId??"",name:input.dealName??`${tko_company.name} opportunity`,amountCents:input.dealAmountCents,source:tko_lead.source,correlationId:input.correlationId}):null; tko_lead.status="converted";tko_lead.convertedAt=tko_now();tko_lead.convertedCompanyId=tko_company.id;tko_lead.convertedContactId=tko_contact.id;tko_lead.convertedDealId=tko_deal?.id??null;tko_lead.conversionKey=input.conversionKey;tko_lead.updatedAt=tko_now();this.tko_leads.set(tko_lead.id,tko_lead);const tko_activities=await this.listActivities(tko_lead.tenantId,"lead",tko_lead.id);await this.tko_emit(input.actor,"crm.lead_converted.v1","crm.lead",{leadId:tko_lead.id,companyId:tko_company.id,contactId:tko_contact.id,dealId:tko_deal?.id??null},"crm.lead.converted","crm_lead",tko_lead.id,input.correlationId);return {lead:tko_clone(tko_lead),company: tko_company,contact: tko_contact,deal: tko_deal,activities: tko_activities,idempotent:false}; }
  private async tko_emit(actor:PlatformActor,eventType:string,topic:string,payload:Record<string,unknown>,auditAction:string,resourceType:string,resourceId:string,correlationId:string){await getPlatformStore().writeDurableMutation({actor,tenantId:actor.tenantId,eventType,topic,payload,auditAction,resourceType,resourceId,correlationId});}
}

let tko_crmStore: CRMStore | null = null;
export function getCRMStore(): CRMStore { if(!tko_crmStore) tko_crmStore=tko_config.postgresUrl?new PostgresCRMStore(tko_config.postgresUrl):new MemoryCRMStore(); return tko_crmStore; }
export function setCRMStoreForTests(store: CRMStore | null): void { tko_crmStore=store; }
