import type { PlatformActor } from "../../contracts/src/platform";
import type { CRMActivity, CRMCompany, CRMContact, CRMConversionResult, CRMDeal, CRMDealBoard, CRMDealHandoff, CRMEntityLink, CRMLead, CRMPipeline, CRMPipelineStage, ConvertLeadInput, CreateLeadInput } from "../../contracts/src/crm";
import { tko_config } from "../../config/src/tasko-config";
import { getPlatformStore } from "./platform-store";
import { PostgresCRMStore } from "./postgres-crm-store";

export interface CRMStore {
  listLeads(tenantId: string): Promise<CRMLead[]>;
  getLead(tenantId: string, leadId: string): Promise<CRMLead | null>;
  createLead(input: CreateLeadInput): Promise<CRMLead>;
  listCompanies(tenantId: string): Promise<CRMCompany[]>;
  getCompany(tenantId: string, companyId: string): Promise<CRMCompany | null>;
  createCompany(actor: PlatformActor, input: { name: string; domain?: string; website?: string; industry?: string; employeeRange?: string; country?: string; lifecycleStatus?: string; tags?: string[]; correlationId: string }): Promise<CRMCompany>;
  listContacts(tenantId: string, companyId?: string): Promise<CRMContact[]>;
  createContact(actor: PlatformActor, input: { companyId?: string | null; firstName: string; lastName: string; title?: string; emails?: string[]; phones?: string[]; tags?: string[]; correlationId: string }): Promise<CRMContact>;
  listPipelines(tenantId: string): Promise<CRMPipeline[]>;
  listStages(tenantId: string, pipelineId: string): Promise<CRMPipelineStage[]>;
  createPipeline(actor: PlatformActor, input: { name: string; stages?: Array<{ name: string; probabilityDefault: number; category: CRMPipelineStage["category"] }>; correlationId: string }): Promise<{ pipeline: CRMPipeline; stages: CRMPipelineStage[] }>;
  listDeals(tenantId: string, pipelineId?: string): Promise<CRMDeal[]>;
  getDeal(tenantId: string, dealId: string): Promise<CRMDeal | null>;
  createDeal(actor: PlatformActor, input: { companyId?: string | null; pipelineId: string; stageId: string; name: string; amountCents?: number | null; currency?: string; probability?: number; expectedCloseDate?: Date | null; source?: string; nextStep?: string; correlationId: string }): Promise<CRMDeal>;
  moveDeal(actor: PlatformActor, input: { dealId: string; stageId: string; correlationId: string }): Promise<CRMDeal>;
  dealBoard(tenantId: string, pipelineId: string): Promise<CRMDealBoard>;
  addActivity(actor: PlatformActor, input: { entityType: CRMActivity["entityType"]; entityId: string; activityType: CRMActivity["activityType"]; subject?: string; body?: string; metadata?: Record<string, unknown>; correlationId: string }): Promise<CRMActivity>;
  listActivities(tenantId: string, entityType: CRMActivity["entityType"], entityId: string): Promise<CRMActivity[]>;
  linkEntity(actor: PlatformActor, input: { sourceType: CRMEntityLink["sourceType"]; sourceId: string; targetType: CRMEntityLink["targetType"]; targetId: string; relationType: CRMEntityLink["relationType"]; correlationId: string }): Promise<CRMEntityLink>;
  listLinks(tenantId: string, sourceType: CRMEntityLink["sourceType"], sourceId: string): Promise<CRMEntityLink[]>;
  getDealHandoff(tenantId: string, dealId: string): Promise<CRMDealHandoff | null>;
  ensureDealHandoff(actor: PlatformActor, input: { dealId: string; correlationId: string }): Promise<CRMDealHandoff>;
  completeDealHandoff(actor: PlatformActor, input: { dealId: string; deliveryProjectId: string; deliveryChannelId: string; correlationId: string }): Promise<CRMDealHandoff>;
  convertLead(input: ConvertLeadInput): Promise<CRMConversionResult>;
}

const tko_clone = <T>(value: T): T => structuredClone(value);
const tko_now = () => new Date();
const tko_cleanTags = (tags: string[] = []) => Array.from(new Set(tags.map(tag => tag.trim()).filter(Boolean))).slice(0, 50);

export class MemoryCRMStore implements CRMStore {
  private readonly tko_leads = new Map<string, CRMLead>();
  private readonly tko_companies = new Map<string, CRMCompany>();
  private readonly tko_contacts = new Map<string, CRMContact>();
  private readonly tko_pipelines = new Map<string, CRMPipeline>();
  private readonly tko_stages = new Map<string, CRMPipelineStage>();
  private readonly tko_deals = new Map<string, CRMDeal>();
  private readonly tko_activities = new Map<string, CRMActivity>();
  private readonly tko_links = new Map<string, CRMEntityLink>();
  private readonly tko_handoffs = new Map<string, CRMDealHandoff>();

  async listLeads(tenantId: string) { return Array.from(this.tko_leads.values()).filter(item => item.tenantId === tenantId).sort((a, b) => b.updatedAt.getTime() - a.updatedAt.getTime()).map(tko_clone); }
  async getLead(tenantId: string, leadId: string) { const item = this.tko_leads.get(leadId); return item?.tenantId === tenantId ? tko_clone(item) : null; }
  async listCompanies(tenantId: string) { return Array.from(this.tko_companies.values()).filter(item => item.tenantId === tenantId).sort((a, b) => a.name.localeCompare(b.name)).map(tko_clone); }
  async getCompany(tenantId: string, companyId: string) { const item = this.tko_companies.get(companyId); return item?.tenantId === tenantId ? tko_clone(item) : null; }
  async listContacts(tenantId: string, companyId?: string) { return Array.from(this.tko_contacts.values()).filter(item => item.tenantId === tenantId && (!companyId || item.companyId === companyId)).map(tko_clone); }
  async listPipelines(tenantId: string) { return Array.from(this.tko_pipelines.values()).filter(item => item.tenantId === tenantId && item.active).map(tko_clone); }
  async listStages(tenantId: string, pipelineId: string) { return Array.from(this.tko_stages.values()).filter(item => item.tenantId === tenantId && item.pipelineId === pipelineId).sort((a,b) => a.sortOrder-b.sortOrder).map(tko_clone); }
  async listDeals(tenantId: string, pipelineId?: string) { return Array.from(this.tko_deals.values()).filter(item => item.tenantId === tenantId && (!pipelineId || item.pipelineId === pipelineId)).map(tko_clone); }
  async getDeal(tenantId: string, dealId: string) { const item = this.tko_deals.get(dealId); return item?.tenantId === tenantId ? tko_clone(item) : null; }
  async listActivities(tenantId: string, entityType: CRMActivity["entityType"], entityId: string) { return Array.from(this.tko_activities.values()).filter(item => item.tenantId === tenantId && item.entityType === entityType && item.entityId === entityId).sort((a,b) => b.createdAt.getTime()-a.createdAt.getTime()).map(tko_clone); }
  async listLinks(tenantId: string, sourceType: CRMEntityLink["sourceType"], sourceId: string) { return Array.from(this.tko_links.values()).filter(item => item.tenantId === tenantId && item.sourceType === sourceType && item.sourceId === sourceId).map(tko_clone); }
  async getDealHandoff(tenantId: string, dealId: string) { const item = this.tko_handoffs.get(dealId); return item?.tenantId === tenantId ? tko_clone(item) : null; }

  async createLead(input: CreateLeadInput) {
    const now = tko_now(); const lead: CRMLead = { id: crypto.randomUUID(), tenantId: input.actor.tenantId, type: "crm_lead", visibility: "internal", ownerMemberId: input.actor.memberId, firstName: input.firstName.trim(), lastName: input.lastName.trim(), companyName: input.companyName?.trim() ?? "", jobTitle: input.jobTitle?.trim() ?? "", email: input.email?.trim().toLowerCase() ?? "", phone: input.phone?.trim() ?? "", website: input.website?.trim() ?? "", country: input.country?.trim() ?? "", source: input.source?.trim() ?? "", status: input.status ?? "new", score: input.score ?? null, tags: tko_cleanTags(input.tags), notes: input.notes?.trim() ?? "", nextFollowUpAt: input.nextFollowUpAt ?? null, customFields: tko_clone(input.customFields ?? {}), convertedAt: null, convertedCompanyId: null, convertedContactId: null, convertedDealId: null, conversionKey: null, createdAt: now, updatedAt: now };
    this.tko_leads.set(lead.id, lead); await this.tko_emit(input.actor, "crm.lead_created.v1", "crm.lead", { leadId: lead.id }, "crm.lead.created", "crm_lead", lead.id, input.correlationId); return tko_clone(lead);
  }
  async createCompany(actor: PlatformActor, input: { name: string; domain?: string; website?: string; industry?: string; employeeRange?: string; country?: string; lifecycleStatus?: string; tags?: string[]; correlationId: string }) {
    const existing = Array.from(this.tko_companies.values()).find(item => item.tenantId === actor.tenantId && item.name.toLowerCase() === input.name.trim().toLowerCase()); if (existing) return tko_clone(existing);
    const now = tko_now(); const company: CRMCompany = { id: crypto.randomUUID(), tenantId: actor.tenantId, type: "crm_company", visibility: "internal", name: input.name.trim(), domain: input.domain?.trim().toLowerCase() ?? "", website: input.website?.trim() ?? "", industry: input.industry?.trim() ?? "", employeeRange: input.employeeRange?.trim() ?? "", country: input.country?.trim() ?? "", ownerMemberId: actor.memberId, lifecycleStatus: input.lifecycleStatus?.trim() ?? "prospect", tags: tko_cleanTags(input.tags), customFields: {}, createdAt: now, updatedAt: now };
    this.tko_companies.set(company.id, company); await this.tko_emit(actor, "crm.company_created.v1", "crm.company", { companyId: company.id }, "crm.company.created", "crm_company", company.id, input.correlationId); return tko_clone(company);
  }
  async createContact(actor: PlatformActor, input: { companyId?: string | null; firstName: string; lastName: string; title?: string; emails?: string[]; phones?: string[]; tags?: string[]; correlationId: string }) {
    if (input.companyId && !(await this.getCompany(actor.tenantId, input.companyId))) throw new Error("CRM_COMPANY_NOT_FOUND"); const now = tko_now(); const item: CRMContact = { id: crypto.randomUUID(), tenantId: actor.tenantId, type: "crm_contact", visibility: "internal", companyId: input.companyId ?? null, firstName: input.firstName.trim(), lastName: input.lastName.trim(), title: input.title?.trim() ?? "", emails: Array.from(new Set((input.emails ?? []).map(v => v.trim().toLowerCase()).filter(Boolean))), phones: Array.from(new Set((input.phones ?? []).map(v => v.trim()).filter(Boolean))), ownerMemberId: actor.memberId, tags: tko_cleanTags(input.tags), customFields: {}, createdAt: now, updatedAt: now };
    this.tko_contacts.set(item.id,item); await this.tko_emit(actor,"crm.contact_created.v1","crm.contact",{contactId:item.id,companyId:item.companyId},"crm.contact.created","crm_contact",item.id,input.correlationId); return tko_clone(item);
  }
  async createPipeline(actor: PlatformActor, input: { name: string; stages?: Array<{ name: string; probabilityDefault: number; category: CRMPipelineStage["category"] }>; correlationId: string }) {
    const pipeline: CRMPipeline = { id: crypto.randomUUID(), tenantId: actor.tenantId, type: "crm_pipeline", visibility: "internal", name: input.name.trim(), active: true, createdAt: tko_now() }; this.tko_pipelines.set(pipeline.id,pipeline);
    const template = input.stages ?? [{name:"Discovery",probabilityDefault:20,category:"open" as const},{name:"Proposal",probabilityDefault:60,category:"open" as const},{name:"Won",probabilityDefault:100,category:"won" as const},{name:"Lost",probabilityDefault:0,category:"lost" as const}];
    const stages = template.map((stage,index): CRMPipelineStage => ({id:crypto.randomUUID(),tenantId:actor.tenantId,type:"crm_pipeline_stage",visibility:"internal",pipelineId:pipeline.id,name:stage.name.trim(),sortOrder:(index+1)*100,probabilityDefault:stage.probabilityDefault,category:stage.category})); stages.forEach(stage=>this.tko_stages.set(stage.id,stage)); await this.tko_emit(actor,"crm.pipeline_created.v1","crm.pipeline",{pipelineId:pipeline.id},"crm.pipeline.created","crm_pipeline",pipeline.id,input.correlationId); return { pipeline:tko_clone(pipeline),stages:stages.map(tko_clone) };
  }
  async createDeal(actor: PlatformActor, input: { companyId?: string | null; pipelineId: string; stageId: string; name: string; amountCents?: number | null; currency?: string; probability?: number; expectedCloseDate?: Date | null; source?: string; nextStep?: string; correlationId: string }) {
    const pipeline = this.tko_pipelines.get(input.pipelineId); const stage = this.tko_stages.get(input.stageId); if (!pipeline || pipeline.tenantId !== actor.tenantId || !stage || stage.pipelineId !== pipeline.id) throw new Error("CRM_PIPELINE_STAGE_NOT_FOUND"); if (input.companyId && !(await this.getCompany(actor.tenantId,input.companyId))) throw new Error("CRM_COMPANY_NOT_FOUND"); const now=tko_now(); const deal: CRMDeal={id:crypto.randomUUID(),tenantId:actor.tenantId,type:"crm_deal",visibility:"internal",companyId:input.companyId??null,pipelineId:pipeline.id,stageId:stage.id,name:input.name.trim(),amountCents:input.amountCents??null,currency:(input.currency??"USD").toUpperCase(),probability:input.probability??stage.probabilityDefault,ownerMemberId:actor.memberId,expectedCloseDate:input.expectedCloseDate??null,source:input.source?.trim()??"",nextStep:input.nextStep?.trim()??"",wonAt:stage.category==="won"?now:null,lostAt:stage.category==="lost"?now:null,lossReason:"",customFields:{},createdAt:now,updatedAt:now}; this.tko_deals.set(deal.id,deal); await this.tko_emit(actor,"crm.deal_created.v1","crm.deal",{dealId:deal.id,pipelineId:deal.pipelineId,stageId:deal.stageId},"crm.deal.created","crm_deal",deal.id,input.correlationId); return tko_clone(deal);
  }
  async moveDeal(actor: PlatformActor, input: { dealId: string; stageId: string; correlationId: string }) { const deal=this.tko_deals.get(input.dealId); const stage=this.tko_stages.get(input.stageId); if(!deal||deal.tenantId!==actor.tenantId||!stage||stage.tenantId!==actor.tenantId||stage.pipelineId!==deal.pipelineId) throw new Error("CRM_DEAL_OR_STAGE_NOT_FOUND"); const before=deal.stageId; const now=tko_now(); deal.stageId=stage.id; deal.probability=stage.probabilityDefault; deal.wonAt=stage.category==="won"?now:null; deal.lostAt=stage.category==="lost"?now:null; deal.updatedAt=now; this.tko_deals.set(deal.id,deal); await this.addActivity(actor,{entityType:"deal",entityId:deal.id,activityType:"status_change",subject:`Moved to ${stage.name}`,metadata:{beforeStageId:before,afterStageId:stage.id},correlationId:input.correlationId}); await this.tko_emit(actor,stage.category==="won"?"crm.deal_won.v1":"crm.deal_stage_changed.v1","crm.deal",{dealId:deal.id,beforeStageId:before,afterStageId:stage.id,pipelineId:deal.pipelineId},stage.category==="won"?"crm.deal.won":"crm.deal.stage_changed","crm_deal",deal.id,input.correlationId); return tko_clone(deal); }
  async dealBoard(tenantId: string,pipelineId: string) { const pipeline=this.tko_pipelines.get(pipelineId); if(!pipeline||pipeline.tenantId!==tenantId) throw new Error("CRM_PIPELINE_NOT_FOUND"); const stages=await this.listStages(tenantId,pipelineId); const deals=await this.listDeals(tenantId,pipelineId); const totalsByStage=Object.fromEntries(stages.map(stage=>[stage.id,{amountCents:0,weightedAmountCents:0}])); for(const deal of deals){const total=totalsByStage[deal.stageId]; if(total&&deal.amountCents!==null){total.amountCents+=deal.amountCents; total.weightedAmountCents+=Math.round(deal.amountCents*deal.probability/100);}} return {pipeline:tko_clone(pipeline),stages,deals,totalsByStage}; }
  async addActivity(actor: PlatformActor,input: { entityType: CRMActivity["entityType"]; entityId: string; activityType: CRMActivity["activityType"]; subject?: string; body?: string; metadata?: Record<string, unknown>; correlationId: string }) { const activity:CRMActivity={id:crypto.randomUUID(),tenantId:actor.tenantId,type:"crm_activity",visibility:"internal",entityType:input.entityType,entityId:input.entityId,activityType:input.activityType,subject:input.subject?.trim()??"",body:input.body?.trim()??"",metadata:tko_clone(input.metadata??{}),createdByMemberId:actor.memberId,createdAt:tko_now()}; this.tko_activities.set(activity.id,activity); await this.tko_emit(actor,"crm.activity_created.v1","crm.activity",{activityId:activity.id,entityType:activity.entityType,entityId:activity.entityId},"crm.activity.created","crm_activity",activity.id,input.correlationId); return tko_clone(activity); }
  async linkEntity(actor: PlatformActor,input: { sourceType: CRMEntityLink["sourceType"]; sourceId: string; targetType: CRMEntityLink["targetType"]; targetId: string; relationType: CRMEntityLink["relationType"]; correlationId: string }) { const key=[actor.tenantId,input.sourceType,input.sourceId,input.targetType,input.targetId,input.relationType].join(":"); const existing=this.tko_links.get(key); if(existing) return tko_clone(existing); const link:CRMEntityLink={id:crypto.randomUUID(),tenantId:actor.tenantId,type:"crm_entity_link",visibility:"internal",sourceType:input.sourceType,sourceId:input.sourceId,targetType:input.targetType,targetId:input.targetId,relationType:input.relationType,createdAt:tko_now()}; this.tko_links.set(key,link); await this.tko_emit(actor,"crm.entity_linked.v1","crm.link",{sourceType:link.sourceType,sourceId:link.sourceId,targetType:link.targetType,targetId:link.targetId},"crm.entity.linked","crm_entity_link",link.id,input.correlationId); return tko_clone(link); }
  async ensureDealHandoff(actor: PlatformActor, input: { dealId: string; correlationId: string }) { const deal = await this.getDeal(actor.tenantId, input.dealId); if (!deal) throw new Error("CRM_DEAL_NOT_FOUND"); if (!deal.wonAt) throw new Error("CRM_DEAL_NOT_WON"); const existing = this.tko_handoffs.get(deal.id); if (existing) return tko_clone(existing); const handoff: CRMDealHandoff = { id: deal.id, dealId: deal.id, tenantId: actor.tenantId, type: "crm_deal_handoff", visibility: "internal", deliveryProjectId: null, deliveryChannelId: null, status: "pending", createdAt: tko_now(), completedAt: null }; this.tko_handoffs.set(deal.id, handoff); await this.tko_emit(actor, "crm.deal_handoff_requested.v1", "crm.deal", { dealId: deal.id }, "crm.deal.handoff.requested", "crm_deal", deal.id, input.correlationId); return tko_clone(handoff); }
  async completeDealHandoff(actor: PlatformActor, input: { dealId: string; deliveryProjectId: string; deliveryChannelId: string; correlationId: string }) { const handoff = await this.ensureDealHandoff(actor, input); if (handoff.status === "completed") return handoff; const completed: CRMDealHandoff = { ...handoff, deliveryProjectId: input.deliveryProjectId, deliveryChannelId: input.deliveryChannelId, status: "completed", completedAt: tko_now() }; this.tko_handoffs.set(input.dealId, completed); await this.tko_emit(actor, "crm.deal_handoff_completed.v1", "crm.deal", { dealId: input.dealId, deliveryProjectId: input.deliveryProjectId, deliveryChannelId: input.deliveryChannelId }, "crm.deal.handoff.completed", "crm_deal", input.dealId, input.correlationId); return tko_clone(completed); }
  async convertLead(input: ConvertLeadInput): Promise<CRMConversionResult> { const lead=this.tko_leads.get(input.leadId); if(!lead||lead.tenantId!==input.actor.tenantId) throw new Error("CRM_LEAD_NOT_FOUND"); if(lead.convertedAt){const company=lead.convertedCompanyId?this.tko_companies.get(lead.convertedCompanyId):undefined;const contact=lead.convertedContactId?this.tko_contacts.get(lead.convertedContactId):undefined;const deal=lead.convertedDealId?this.tko_deals.get(lead.convertedDealId):undefined;if(!company||!contact)throw new Error("CRM_CONVERSION_INTEGRITY_ERROR");return {lead:tko_clone(lead),company:tko_clone(company),contact:tko_clone(contact),deal:deal?tko_clone(deal):null,activities:await this.listActivities(lead.tenantId,"lead",lead.id),idempotent:true};} if(lead.status!=="qualified")throw new Error("CRM_LEAD_NOT_QUALIFIED"); const company=input.companyId?await this.getCompany(lead.tenantId,input.companyId):await this.createCompany(input.actor,{name:lead.companyName||`${lead.firstName} ${lead.lastName} Company`,website:lead.website,country:lead.country,correlationId:input.correlationId}); if(!company)throw new Error("CRM_COMPANY_NOT_FOUND"); const contact=input.contactId?(await this.listContacts(lead.tenantId)).find(c=>c.id===input.contactId)??null:await this.createContact(input.actor,{companyId:company.id,firstName:lead.firstName,lastName:lead.lastName,title:lead.jobTitle,emails:lead.email?[lead.email]:[],phones:lead.phone?[lead.phone]:[],tags:lead.tags,correlationId:input.correlationId}); if(!contact)throw new Error("CRM_CONTACT_NOT_FOUND"); const deal=input.createDeal?await this.createDeal(input.actor,{companyId:company.id,pipelineId:input.pipelineId??"",stageId:input.stageId??"",name:input.dealName??`${company.name} opportunity`,amountCents:input.dealAmountCents,source:lead.source,correlationId:input.correlationId}):null; lead.status="converted";lead.convertedAt=tko_now();lead.convertedCompanyId=company.id;lead.convertedContactId=contact.id;lead.convertedDealId=deal?.id??null;lead.conversionKey=input.conversionKey;lead.updatedAt=tko_now();this.tko_leads.set(lead.id,lead);const activities=await this.listActivities(lead.tenantId,"lead",lead.id);await this.tko_emit(input.actor,"crm.lead_converted.v1","crm.lead",{leadId:lead.id,companyId:company.id,contactId:contact.id,dealId:deal?.id??null},"crm.lead.converted","crm_lead",lead.id,input.correlationId);return {lead:tko_clone(lead),company,contact,deal,activities,idempotent:false}; }
  private async tko_emit(actor:PlatformActor,eventType:string,topic:string,payload:Record<string,unknown>,auditAction:string,resourceType:string,resourceId:string,correlationId:string){await getPlatformStore().writeDurableMutation({actor,tenantId:actor.tenantId,eventType,topic,payload,auditAction,resourceType,resourceId,correlationId});}
}

let tko_crmStore: CRMStore | null = null;
export function getCRMStore(): CRMStore { if(!tko_crmStore) tko_crmStore=tko_config.postgresUrl?new PostgresCRMStore(tko_config.postgresUrl):new MemoryCRMStore(); return tko_crmStore; }
export function setCRMStoreForTests(store: CRMStore | null): void { tko_crmStore=store; }
