import crypto from "node:crypto";
import pg from "pg";
import { tko_config } from "../../config/src/tasko-config";
import type { PlatformActor } from "../../contracts/src/platform";
import type {
  CreateDeveloperTokenInput,
  CreateWebhookSubscriptionInput,
  DeveloperApiToken,
  ExternalConnection,
  ExternalConnectionProvider,
  ExternalConnectionStatus,
  WebhookDelivery,
  WebhookDeliveryStatus,
  WebhookSubscription,
} from "../../contracts/src/ecosystem";
import { getPlatformStore } from "./platform-store";

type TkoRow = Record<string, unknown>;
const tko_clone = <T>(tko_value: T): T => structuredClone(tko_value);
const tko_json = <T>(tko_value: unknown, tko_fallback: T): T => typeof tko_value === "string" ? JSON.parse(tko_value) as T : (tko_value ?? tko_fallback) as T;
const tko_date = (tko_value: unknown): Date | null => tko_value ? new Date(String(tko_value)) : null;
const tko_hash = (tko_value: string): string => crypto.createHash("sha256").update(tko_value).digest("hex");
const tko_cipherKey = (): Buffer => crypto.createHash("sha256").update(process.env.JWT_SECRET ?? "tasko-development-webhook-key").digest();
const tko_encrypt = (tko_value: string): string => { const tko_iv = crypto.randomBytes(12); const tko_cipher = crypto.createCipheriv("aes-256-gcm", tko_cipherKey(), tko_iv); const tko_body = Buffer.concat([tko_cipher.update(tko_value, "utf8"), tko_cipher.final()]); return [tko_iv.toString("base64"), tko_cipher.getAuthTag().toString("base64"), tko_body.toString("base64")].join("."); };
const tko_decrypt = (tko_value: string): string => { const [tko_iv, tko_tag, tko_body] = tko_value.split("."); if (!tko_iv || !tko_tag || !tko_body) throw new Error("WEBHOOK_SECRET_CIPHERTEXT_INVALID"); const tko_decipher = crypto.createDecipheriv("aes-256-gcm", tko_cipherKey(), Buffer.from(tko_iv, "base64")); tko_decipher.setAuthTag(Buffer.from(tko_tag, "base64")); return Buffer.concat([tko_decipher.update(Buffer.from(tko_body, "base64")), tko_decipher.final()]).toString("utf8"); };

export interface DeveloperTokenAuthentication {
  token: DeveloperApiToken;
  actor: PlatformActor;
}

export interface DeveloperStore {
  createToken(input: CreateDeveloperTokenInput): Promise<{ token: DeveloperApiToken; secret: string }>;
  listTokens(tenantId: string): Promise<DeveloperApiToken[]>;
  revokeToken(actor: PlatformActor, tokenId: string, correlationId: string): Promise<void>;
  authenticateToken(secret: string, correlationId: string): Promise<DeveloperTokenAuthentication | null>;
  createWebhookSubscription(input: CreateWebhookSubscriptionInput): Promise<{ subscription: WebhookSubscription; signingSecret: string }>;
  listWebhookSubscriptions(tenantId: string): Promise<WebhookSubscription[]>;
  getWebhookSecret(tenantId: string, subscriptionId: string): Promise<{ endpointUrl: string; secret: string } | null>;
  createWebhookDelivery(actor: PlatformActor, input: { subscriptionId: string; outboxEventId: string; eventType: string; payload: Record<string, unknown>; correlationId: string }): Promise<WebhookDelivery | null>;
  listWebhookDeliveries(tenantId: string, subscriptionId?: string): Promise<WebhookDelivery[]>;
  updateWebhookDelivery(actor: PlatformActor, input: { deliveryId: string; status: WebhookDeliveryStatus; responseStatus?: number | null; responseError?: string | null; nextAttemptAt?: Date | null; correlationId: string }): Promise<WebhookDelivery>;
  createExternalConnection(actor: PlatformActor, input: { provider: ExternalConnectionProvider; displayName: string; externalAccountId?: string | null; config?: Record<string, unknown>; status?: ExternalConnectionStatus; correlationId: string }): Promise<ExternalConnection>;
  listExternalConnections(tenantId: string): Promise<ExternalConnection[]>;
}

export class MemoryDeveloperStore implements DeveloperStore {
  private readonly tko_tokens = new Map<string, DeveloperApiToken>();
  private readonly tko_tokenActors = new Map<string, PlatformActor>();
  private readonly tko_subscriptions = new Map<string, WebhookSubscription>();
  private readonly tko_webhookSecrets = new Map<string, string>();
  private readonly tko_deliveries = new Map<string, WebhookDelivery>();
  private readonly tko_connections = new Map<string, ExternalConnection>();

  async createToken(tko_input: CreateDeveloperTokenInput): Promise<{ token: DeveloperApiToken; secret: string }> {
    const tko_secret = `tko_${crypto.randomUUID().replaceAll("-", "")}_${crypto.randomUUID().replaceAll("-", "")}`;
    const tko_now = new Date();
    const tko_token: DeveloperApiToken = { id: crypto.randomUUID(), tenantId: tko_input.actor.tenantId, type: "developer_api_token", name: tko_input.name.trim(), tokenPrefix: tko_secret.slice(0, 14), tokenHash: tko_hash(tko_secret), scopes: Array.from(new Set(tko_input.scopes)), createdByMemberId: tko_input.actor.memberId, lastUsedAt: null, expiresAt: tko_input.expiresAt ?? null, revokedAt: null, createdAt: tko_now };
    this.tko_tokens.set(tko_token.id, tko_token);
    this.tko_tokenActors.set(tko_token.id, tko_clone(tko_input.actor));
    await this.tko_emit(tko_input.actor, "ecosystem.developer_token_created.v1", "ecosystem.developer", { tokenId: tko_token.id, scopes: tko_token.scopes }, "ecosystem.developer_token.created", "developer_api_token", tko_token.id, tko_input.correlationId);
    return { token: tko_clone(tko_token), secret: tko_secret };
  }
  async listTokens(tko_tenantId: string): Promise<DeveloperApiToken[]> { return Array.from(this.tko_tokens.values()).filter(tko_token => tko_token.tenantId === tko_tenantId).map(tko_clone); }
  async revokeToken(tko_actor: PlatformActor, tko_tokenId: string, tko_correlationId: string): Promise<void> { const tko_token = this.tko_tokens.get(tko_tokenId); if (!tko_token || tko_token.tenantId !== tko_actor.tenantId) throw new Error("DEVELOPER_TOKEN_NOT_FOUND"); tko_token.revokedAt = new Date(); await this.tko_emit(tko_actor, "ecosystem.developer_token_revoked.v1", "ecosystem.developer", { tokenId: tko_token.id }, "ecosystem.developer_token.revoked", "developer_api_token", tko_token.id, tko_correlationId); }
  async authenticateToken(tko_secret: string, tko_correlationId: string): Promise<DeveloperTokenAuthentication | null> { const tko_token = Array.from(this.tko_tokens.values()).find(tko_item => tko_item.tokenHash === tko_hash(tko_secret)); if (!tko_token || tko_token.revokedAt || (tko_token.expiresAt && tko_token.expiresAt <= new Date())) return null; const tko_actor = this.tko_tokenActors.get(tko_token.id); if (!tko_actor) return null; tko_token.lastUsedAt = new Date(); return { token: tko_clone(tko_token), actor: { ...tko_clone(tko_actor), correlationId: tko_correlationId } }; }
  async createWebhookSubscription(tko_input: CreateWebhookSubscriptionInput): Promise<{ subscription: WebhookSubscription; signingSecret: string }> { const tko_secret = crypto.randomUUID().replaceAll("-", ""); const tko_now = new Date(); const tko_subscription: WebhookSubscription = { id: crypto.randomUUID(), tenantId: tko_input.actor.tenantId, type: "webhook_subscription", name: tko_input.name.trim(), endpointUrl: tko_input.endpointUrl, signingSecretHash: tko_hash(tko_secret), eventTypes: Array.from(new Set(tko_input.eventTypes)), status: "active", consecutiveFailures: 0, createdByMemberId: tko_input.actor.memberId, createdAt: tko_now, updatedAt: tko_now }; this.tko_subscriptions.set(tko_subscription.id, tko_subscription); this.tko_webhookSecrets.set(tko_subscription.id, tko_secret); await this.tko_emit(tko_input.actor, "ecosystem.webhook_subscription_created.v1", "ecosystem.webhook", { subscriptionId: tko_subscription.id, eventTypes: tko_subscription.eventTypes }, "ecosystem.webhook_subscription.created", "webhook_subscription", tko_subscription.id, tko_input.correlationId); return { subscription: tko_clone(tko_subscription), signingSecret: tko_secret }; }
  async listWebhookSubscriptions(tko_tenantId: string): Promise<WebhookSubscription[]> { return Array.from(this.tko_subscriptions.values()).filter(tko_item => tko_item.tenantId === tko_tenantId).map(tko_clone); }
  async getWebhookSecret(tko_tenantId: string, tko_subscriptionId: string): Promise<{ endpointUrl: string; secret: string } | null> { const tko_subscription = this.tko_subscriptions.get(tko_subscriptionId); const tko_secret = this.tko_webhookSecrets.get(tko_subscriptionId); return tko_subscription?.tenantId === tko_tenantId && tko_secret ? { endpointUrl: tko_subscription.endpointUrl, secret: tko_secret } : null; }
  async createWebhookDelivery(tko_actor: PlatformActor, tko_input: Parameters<DeveloperStore["createWebhookDelivery"]>[1]): Promise<WebhookDelivery | null> { const tko_subscription = this.tko_subscriptions.get(tko_input.subscriptionId); if (!tko_subscription || tko_subscription.tenantId !== tko_actor.tenantId || tko_subscription.status !== "active" || !tko_subscription.eventTypes.includes(tko_input.eventType)) return null; const tko_existing = Array.from(this.tko_deliveries.values()).find(tko_item => tko_item.tenantId === tko_actor.tenantId && tko_item.subscriptionId === tko_subscription.id && tko_item.outboxEventId === tko_input.outboxEventId); if (tko_existing) return tko_clone(tko_existing); const tko_delivery: WebhookDelivery = { id: crypto.randomUUID(), tenantId: tko_actor.tenantId, type: "webhook_delivery", subscriptionId: tko_subscription.id, outboxEventId: tko_input.outboxEventId, eventType: tko_input.eventType, payload: tko_clone(tko_input.payload), status: "pending", attempts: 0, responseStatus: null, responseError: null, nextAttemptAt: new Date(), createdAt: new Date(), deliveredAt: null }; this.tko_deliveries.set(tko_delivery.id, tko_delivery); await this.tko_emit(tko_actor, "ecosystem.webhook_delivery_queued.v1", "ecosystem.webhook", { deliveryId: tko_delivery.id, eventType: tko_delivery.eventType }, "ecosystem.webhook_delivery.queued", "webhook_delivery", tko_delivery.id, tko_input.correlationId); return tko_clone(tko_delivery); }
  async listWebhookDeliveries(tko_tenantId: string, tko_subscriptionId?: string): Promise<WebhookDelivery[]> { return Array.from(this.tko_deliveries.values()).filter(tko_item => tko_item.tenantId === tko_tenantId && (!tko_subscriptionId || tko_item.subscriptionId === tko_subscriptionId)).map(tko_clone); }
  async updateWebhookDelivery(tko_actor: PlatformActor, tko_input: Parameters<DeveloperStore["updateWebhookDelivery"]>[1]): Promise<WebhookDelivery> { const tko_delivery = this.tko_deliveries.get(tko_input.deliveryId); if (!tko_delivery || tko_delivery.tenantId !== tko_actor.tenantId) throw new Error("WEBHOOK_DELIVERY_NOT_FOUND"); tko_delivery.status = tko_input.status; tko_delivery.attempts += 1; tko_delivery.responseStatus = tko_input.responseStatus ?? null; tko_delivery.responseError = tko_input.responseError ?? null; tko_delivery.nextAttemptAt = tko_input.nextAttemptAt ?? null; tko_delivery.deliveredAt = tko_input.status === "delivered" ? new Date() : null; await this.tko_emit(tko_actor, "ecosystem.webhook_delivery_updated.v1", "ecosystem.webhook", { deliveryId: tko_delivery.id, status: tko_delivery.status }, "ecosystem.webhook_delivery.updated", "webhook_delivery", tko_delivery.id, tko_input.correlationId); return tko_clone(tko_delivery); }
  async createExternalConnection(tko_actor: PlatformActor, tko_input: Parameters<DeveloperStore["createExternalConnection"]>[1]): Promise<ExternalConnection> { const tko_now = new Date(); const tko_connection: ExternalConnection = { id: crypto.randomUUID(), tenantId: tko_actor.tenantId, type: "external_connection", provider: tko_input.provider, status: tko_input.status ?? "pending", displayName: tko_input.displayName.trim(), externalAccountId: tko_input.externalAccountId ?? null, encryptedSecretRef: null, config: tko_clone(tko_input.config ?? {}), createdByMemberId: tko_actor.memberId, createdAt: tko_now, updatedAt: tko_now }; this.tko_connections.set(tko_connection.id, tko_connection); await this.tko_emit(tko_actor, "ecosystem.external_connection_created.v1", "ecosystem.integration", { connectionId: tko_connection.id, provider: tko_connection.provider }, "ecosystem.external_connection.created", "external_connection", tko_connection.id, tko_input.correlationId); return tko_clone(tko_connection); }
  async listExternalConnections(tko_tenantId: string): Promise<ExternalConnection[]> { return Array.from(this.tko_connections.values()).filter(tko_item => tko_item.tenantId === tko_tenantId).map(tko_clone); }
  private async tko_emit(tko_actor: PlatformActor, tko_eventType: string, tko_topic: string, tko_payload: Record<string, unknown>, tko_action: string, tko_resourceType: string, tko_resourceId: string, tko_correlationId: string): Promise<void> { await getPlatformStore().writeDurableMutation({ actor: tko_actor, tenantId: tko_actor.tenantId, eventType: tko_eventType, topic: tko_topic, payload: tko_payload, auditAction: tko_action, resourceType: tko_resourceType, resourceId: tko_resourceId, correlationId: tko_correlationId }); }
}

export class PostgresDeveloperStore implements DeveloperStore {
  private readonly tko_pool: pg.Pool;
  constructor(tko_url: string) { this.tko_pool = new pg.Pool({ connectionString: tko_url, max: 10 }); }
  async createToken(tko_input: CreateDeveloperTokenInput): Promise<{ token: DeveloperApiToken; secret: string }> { const tko_secret = `tko_${crypto.randomUUID().replaceAll("-", "")}_${crypto.randomUUID().replaceAll("-", "")}`; const tko_token = await this.tko_tx(tko_input.actor.tenantId, async tko_client => { const tko_result = await tko_client.query("insert into developer_api_tokens(id,tenant_id,name,token_prefix,token_hash,scopes_json,created_by_member_id,expires_at) values($1,$2,$3,$4,$5,$6::jsonb,$7,$8) returning *", [crypto.randomUUID(), tko_input.actor.tenantId, tko_input.name.trim(), tko_secret.slice(0, 14), tko_hash(tko_secret), JSON.stringify(Array.from(new Set(tko_input.scopes))), tko_input.actor.memberId, tko_input.expiresAt ?? null]); const tko_value = this.tko_tokenRow(tko_result.rows[0]); await this.tko_emit(tko_client, tko_input.actor, "ecosystem.developer_token_created.v1", "ecosystem.developer", { tokenId: tko_value.id, scopes: tko_value.scopes }, "ecosystem.developer_token.created", "developer_api_token", tko_value.id, tko_input.correlationId); return tko_value; }); return { token: tko_token, secret: tko_secret }; }
  async listTokens(tko_tenantId: string): Promise<DeveloperApiToken[]> { return this.tko_read(tko_tenantId, async tko_client => (await tko_client.query("select * from developer_api_tokens where tenant_id=$1 order by created_at desc", [tko_tenantId])).rows.map(this.tko_tokenRow)); }
  async revokeToken(tko_actor: PlatformActor, tko_tokenId: string, tko_correlationId: string): Promise<void> { await this.tko_tx(tko_actor.tenantId, async tko_client => { const tko_result = await tko_client.query("update developer_api_tokens set revoked_at=now() where tenant_id=$1 and id=$2 and revoked_at is null returning *", [tko_actor.tenantId, tko_tokenId]); if (!tko_result.rowCount) throw new Error("DEVELOPER_TOKEN_NOT_FOUND"); await this.tko_emit(tko_client, tko_actor, "ecosystem.developer_token_revoked.v1", "ecosystem.developer", { tokenId: tko_tokenId }, "ecosystem.developer_token.revoked", "developer_api_token", tko_tokenId, tko_correlationId); }); }
  async authenticateToken(tko_secret: string, tko_correlationId: string): Promise<DeveloperTokenAuthentication | null> { const tko_client = await this.tko_pool.connect(); try { const tko_result = await tko_client.query("select t.*,m.id as member_id,m.role as member_role,m.status as member_status,u.auth_subject,ten.slug as tenant_slug from developer_api_tokens t join tenant_members m on m.id=t.created_by_member_id join users u on u.id=m.user_id join tenants ten on ten.id=t.tenant_id where t.token_hash=$1 and t.revoked_at is null and (t.expires_at is null or t.expires_at>now()) and m.status='active'", [tko_hash(tko_secret)]); if (!tko_result.rowCount) return null; const tko_row = tko_result.rows[0] as TkoRow; await tko_client.query("update developer_api_tokens set last_used_at=now() where id=$1", [tko_row.id]); return { token: this.tko_tokenRow(tko_row), actor: { authSubject: `api-token:${String(tko_row.id)}`, tenantId: String(tko_row.tenant_id), tenantSlug: String(tko_row.tenant_slug), memberId: String(tko_row.member_id), role: String(tko_row.member_role) as PlatformActor["role"], membershipStatus: "active", correlationId: tko_correlationId } }; } finally { tko_client.release(); } }
  async createWebhookSubscription(tko_input: CreateWebhookSubscriptionInput): Promise<{ subscription: WebhookSubscription; signingSecret: string }> { const tko_secret = crypto.randomUUID().replaceAll("-", ""); const tko_subscription = await this.tko_tx(tko_input.actor.tenantId, async tko_client => { const tko_result = await tko_client.query("insert into webhook_subscriptions(id,tenant_id,name,endpoint_url,signing_secret_hash,signing_secret_ciphertext,event_types_json,status,created_by_member_id) values($1,$2,$3,$4,$5,$6,$7::jsonb,'active',$8) returning *", [crypto.randomUUID(), tko_input.actor.tenantId, tko_input.name.trim(), tko_input.endpointUrl, tko_hash(tko_secret), tko_encrypt(tko_secret), JSON.stringify(Array.from(new Set(tko_input.eventTypes))), tko_input.actor.memberId]); const tko_value = this.tko_subscriptionRow(tko_result.rows[0]); await this.tko_emit(tko_client, tko_input.actor, "ecosystem.webhook_subscription_created.v1", "ecosystem.webhook", { subscriptionId: tko_value.id, eventTypes: tko_value.eventTypes }, "ecosystem.webhook_subscription.created", "webhook_subscription", tko_value.id, tko_input.correlationId); return tko_value; }); return { subscription: tko_subscription, signingSecret: tko_secret }; }
  async listWebhookSubscriptions(tko_tenantId: string): Promise<WebhookSubscription[]> { return this.tko_read(tko_tenantId, async tko_client => (await tko_client.query("select * from webhook_subscriptions where tenant_id=$1 order by created_at desc", [tko_tenantId])).rows.map(this.tko_subscriptionRow)); }
  async getWebhookSecret(tko_tenantId: string, tko_subscriptionId: string): Promise<{ endpointUrl: string; secret: string } | null> { return this.tko_read(tko_tenantId, async tko_client => { const tko_result = await tko_client.query("select endpoint_url,signing_secret_ciphertext from webhook_subscriptions where tenant_id=$1 and id=$2 and status='active'", [tko_tenantId, tko_subscriptionId]); if (!tko_result.rowCount) return null; return { endpointUrl: String(tko_result.rows[0].endpoint_url), secret: tko_decrypt(String(tko_result.rows[0].signing_secret_ciphertext)) }; }); }
  async createWebhookDelivery(tko_actor: PlatformActor, tko_input: Parameters<DeveloperStore["createWebhookDelivery"]>[1]): Promise<WebhookDelivery | null> { return this.tko_tx(tko_actor.tenantId, async tko_client => { const tko_subscription = await tko_client.query("select * from webhook_subscriptions where tenant_id=$1 and id=$2 and status='active'", [tko_actor.tenantId, tko_input.subscriptionId]); if (!tko_subscription.rowCount || !tko_json<string[]>(tko_subscription.rows[0].event_types_json, []).includes(tko_input.eventType)) return null; const tko_result = await tko_client.query("insert into webhook_deliveries(id,tenant_id,subscription_id,outbox_event_id,event_type,payload_json,status,next_attempt_at) values($1,$2,$3,$4,$5,$6::jsonb,'pending',now()) on conflict(tenant_id,subscription_id,outbox_event_id) do update set event_type=excluded.event_type returning *", [crypto.randomUUID(), tko_actor.tenantId, tko_input.subscriptionId, tko_input.outboxEventId, tko_input.eventType, JSON.stringify(tko_input.payload)]); const tko_value = this.tko_deliveryRow(tko_result.rows[0]); await this.tko_emit(tko_client, tko_actor, "ecosystem.webhook_delivery_queued.v1", "ecosystem.webhook", { deliveryId: tko_value.id, eventType: tko_value.eventType }, "ecosystem.webhook_delivery.queued", "webhook_delivery", tko_value.id, tko_input.correlationId); return tko_value; }); }
  async listWebhookDeliveries(tko_tenantId: string, tko_subscriptionId?: string): Promise<WebhookDelivery[]> { return this.tko_read(tko_tenantId, async tko_client => (await tko_client.query("select * from webhook_deliveries where tenant_id=$1 and ($2::uuid is null or subscription_id=$2) order by created_at desc", [tko_tenantId, tko_subscriptionId ?? null])).rows.map(this.tko_deliveryRow)); }
  async updateWebhookDelivery(tko_actor: PlatformActor, tko_input: Parameters<DeveloperStore["updateWebhookDelivery"]>[1]): Promise<WebhookDelivery> { return this.tko_tx(tko_actor.tenantId, async tko_client => { const tko_result = await tko_client.query("update webhook_deliveries set status=$3,attempts=attempts+1,response_status=$4,response_error=$5,next_attempt_at=$6,delivered_at=case when $3='delivered' then now() else null end where tenant_id=$1 and id=$2 returning *", [tko_actor.tenantId, tko_input.deliveryId, tko_input.status, tko_input.responseStatus ?? null, tko_input.responseError ?? null, tko_input.nextAttemptAt ?? null]); if (!tko_result.rowCount) throw new Error("WEBHOOK_DELIVERY_NOT_FOUND"); const tko_value = this.tko_deliveryRow(tko_result.rows[0]); await this.tko_emit(tko_client, tko_actor, "ecosystem.webhook_delivery_updated.v1", "ecosystem.webhook", { deliveryId: tko_value.id, status: tko_value.status }, "ecosystem.webhook_delivery.updated", "webhook_delivery", tko_value.id, tko_input.correlationId); return tko_value; }); }
  async createExternalConnection(tko_actor: PlatformActor, tko_input: Parameters<DeveloperStore["createExternalConnection"]>[1]): Promise<ExternalConnection> { return this.tko_tx(tko_actor.tenantId, async tko_client => { const tko_result = await tko_client.query("insert into external_connections(id,tenant_id,provider,status,display_name,external_account_id,config_json,created_by_member_id) values($1,$2,$3,$4,$5,$6,$7::jsonb,$8) returning *", [crypto.randomUUID(), tko_actor.tenantId, tko_input.provider, tko_input.status ?? "pending", tko_input.displayName.trim(), tko_input.externalAccountId ?? null, JSON.stringify(tko_input.config ?? {}), tko_actor.memberId]); const tko_value = this.tko_connectionRow(tko_result.rows[0]); await this.tko_emit(tko_client, tko_actor, "ecosystem.external_connection_created.v1", "ecosystem.integration", { connectionId: tko_value.id, provider: tko_value.provider }, "ecosystem.external_connection.created", "external_connection", tko_value.id, tko_input.correlationId); return tko_value; }); }
  async listExternalConnections(tko_tenantId: string): Promise<ExternalConnection[]> { return this.tko_read(tko_tenantId, async tko_client => (await tko_client.query("select * from external_connections where tenant_id=$1 order by created_at desc", [tko_tenantId])).rows.map(this.tko_connectionRow)); }
  private async tko_read<T>(tko_tenantId: string, tko_operation: (tko_client: pg.PoolClient) => Promise<T>): Promise<T> { const tko_client = await this.tko_pool.connect(); try { await tko_client.query("begin"); await tko_client.query("select set_config('app.tenant_id',$1,true)", [tko_tenantId]); const tko_value = await tko_operation(tko_client); await tko_client.query("commit"); return tko_value; } catch (tko_error) { await tko_client.query("rollback"); throw tko_error; } finally { tko_client.release(); } }
  private async tko_tx<T>(tko_tenantId: string, tko_operation: (tko_client: pg.PoolClient) => Promise<T>): Promise<T> { return this.tko_read(tko_tenantId, tko_operation); }
  private async tko_emit(tko_client: pg.PoolClient, tko_actor: PlatformActor, tko_eventType: string, tko_topic: string, tko_payload: Record<string, unknown>, tko_action: string, tko_resourceType: string, tko_resourceId: string, tko_correlationId: string): Promise<void> { await tko_client.query("insert into audit_logs(id,tenant_id,actor_auth_subject,action,resource_type,resource_id,correlation_id,metadata_json) values(gen_random_uuid(),$1,$2,$3,$4,$5,$6,'{}'::jsonb)", [tko_actor.tenantId, tko_actor.authSubject, tko_action, tko_resourceType, tko_resourceId, tko_correlationId]); await tko_client.query("insert into outbox(id,event_id,tenant_id,topic,event_type,payload_json,actor_auth_subject,correlation_id,status,attempts,available_at) values($1,$2,$3,$4,$5,$6::jsonb,$7,$8,'pending',0,now())", [crypto.randomUUID(), crypto.randomUUID(), tko_actor.tenantId, tko_topic, tko_eventType, JSON.stringify(tko_payload), tko_actor.authSubject, tko_correlationId]); }
  private tko_tokenRow = (tko_row: TkoRow): DeveloperApiToken => ({ id: String(tko_row.id), tenantId: String(tko_row.tenant_id), type: "developer_api_token", name: String(tko_row.name), tokenPrefix: String(tko_row.token_prefix), tokenHash: String(tko_row.token_hash), scopes: tko_json(tko_row.scopes_json, []), createdByMemberId: String(tko_row.created_by_member_id), lastUsedAt: tko_date(tko_row.last_used_at), expiresAt: tko_date(tko_row.expires_at), revokedAt: tko_date(tko_row.revoked_at), createdAt: new Date(String(tko_row.created_at)) });
  private tko_subscriptionRow = (tko_row: TkoRow): WebhookSubscription => ({ id: String(tko_row.id), tenantId: String(tko_row.tenant_id), type: "webhook_subscription", name: String(tko_row.name), endpointUrl: String(tko_row.endpoint_url), signingSecretHash: String(tko_row.signing_secret_hash), eventTypes: tko_json(tko_row.event_types_json, []), status: tko_row.status as WebhookSubscription["status"], consecutiveFailures: Number(tko_row.consecutive_failures), createdByMemberId: String(tko_row.created_by_member_id), createdAt: new Date(String(tko_row.created_at)), updatedAt: new Date(String(tko_row.updated_at)) });
  private tko_deliveryRow = (tko_row: TkoRow): WebhookDelivery => ({ id: String(tko_row.id), tenantId: String(tko_row.tenant_id), type: "webhook_delivery", subscriptionId: String(tko_row.subscription_id), outboxEventId: String(tko_row.outbox_event_id), eventType: String(tko_row.event_type), payload: tko_json(tko_row.payload_json, {}), status: tko_row.status as WebhookDeliveryStatus, attempts: Number(tko_row.attempts), responseStatus: tko_row.response_status === null ? null : Number(tko_row.response_status), responseError: tko_row.response_error ? String(tko_row.response_error) : null, nextAttemptAt: tko_date(tko_row.next_attempt_at), createdAt: new Date(String(tko_row.created_at)), deliveredAt: tko_date(tko_row.delivered_at) });
  private tko_connectionRow = (tko_row: TkoRow): ExternalConnection => ({ id: String(tko_row.id), tenantId: String(tko_row.tenant_id), type: "external_connection", provider: tko_row.provider as ExternalConnectionProvider, status: tko_row.status as ExternalConnectionStatus, displayName: String(tko_row.display_name), externalAccountId: tko_row.external_account_id ? String(tko_row.external_account_id) : null, encryptedSecretRef: tko_row.encrypted_secret_ref ? String(tko_row.encrypted_secret_ref) : null, config: tko_json(tko_row.config_json, {}), createdByMemberId: String(tko_row.created_by_member_id), createdAt: new Date(String(tko_row.created_at)), updatedAt: new Date(String(tko_row.updated_at)) });
}

let tko_store: DeveloperStore | null = null;
export function getDeveloperStore(): DeveloperStore { if (tko_store) return tko_store; tko_store = tko_config.postgresUrl ? new PostgresDeveloperStore(tko_config.postgresUrl) : new MemoryDeveloperStore(); return tko_store; }
export function setDeveloperStoreForTests(tko_next: DeveloperStore | null): void { tko_store = tko_next; }
