import pg, { type PoolClient } from "pg";
import { tko_config } from "../../config/src/tasko-config";
import type { PlatformActor } from "../../contracts/src/platform";
import type { CreateImportJobInput, ImportBatch, ImportFieldMapping, ImportJob, ImportJobStatus, ImportMapping, ImportRecordStatus, ImportSourceMapping, ImportStagingRecord, ImportTargetKind } from "../../contracts/src/ecosystem";
import { getPlatformStore } from "./platform-store";

type TkoRow = Record<string, unknown>;
const tko_clone = <T>(tko_value: T): T => structuredClone(tko_value);
const tko_json = <T>(tko_value: unknown, tko_fallback: T): T => typeof tko_value === "string" ? JSON.parse(tko_value) as T : (tko_value ?? tko_fallback) as T;
const tko_date = (tko_value: unknown): Date | null => tko_value ? new Date(String(tko_value)) : null;

export interface StageImportRecordInput {
  sourceRecordId: string;
  sourceType: string;
  payload: Record<string, unknown>;
  status?: Extract<ImportRecordStatus, "staged" | "valid" | "warning" | "error">;
  validation?: Record<string, unknown>;
  targetKind?: ImportTargetKind | null;
  sourceUpdatedAt?: Date | null;
}

export interface EcosystemStore {
  createImportJob(tko_input: CreateImportJobInput): Promise<ImportJob>;
  listImportJobs(tko_tenantId: string): Promise<ImportJob[]>;
  getImportJob(tko_tenantId: string, tko_jobId: string): Promise<ImportJob | null>;
  setImportJobStatus(tko_actor: PlatformActor, tko_input: { jobId: string; status: ImportJobStatus; cursor?: string | null; correlationId: string }): Promise<ImportJob>;
  stageImportRecords(tko_actor: PlatformActor, tko_input: { jobId: string; records: StageImportRecordInput[]; correlationId: string }): Promise<ImportStagingRecord[]>;
  listStagingRecords(tko_tenantId: string, tko_jobId: string): Promise<ImportStagingRecord[]>;
  saveImportMapping(tko_actor: PlatformActor, tko_input: { jobId: string; sourceType: string; targetKind: ImportTargetKind; duplicateStrategy: ImportMapping["duplicateStrategy"]; ownerMemberId?: string | null; fields: ImportFieldMapping[]; correlationId: string }): Promise<ImportMapping>;
  listImportMappings(tko_tenantId: string, tko_jobId: string): Promise<ImportMapping[]>;
  createImportBatch(tko_actor: PlatformActor, tko_input: { jobId: string; idempotencyKey: string; recordIds: string[]; correlationId: string }): Promise<ImportBatch>;
  listImportBatches(tko_tenantId: string, tko_jobId: string): Promise<ImportBatch[]>;
  getImportBatch(tko_tenantId: string, tko_batchId: string): Promise<ImportBatch | null>;
  completeImportBatch(tko_actor: PlatformActor, tko_input: { batchId: string; imported: Array<{ stagingRecordId: string; targetKind: ImportTargetKind; targetEntityId: string }>; warnings: number; correlationId: string }): Promise<ImportBatch>;
  listSourceMappings(tko_tenantId: string, tko_jobId: string): Promise<ImportSourceMapping[]>;
}

export class MemoryEcosystemStore implements EcosystemStore {
  private readonly tko_jobs = new Map<string, ImportJob>();
  private readonly tko_records = new Map<string, ImportStagingRecord>();
  private readonly tko_mappings = new Map<string, ImportMapping>();
  private readonly tko_batches = new Map<string, ImportBatch>();
  private readonly tko_sourceMappings = new Map<string, ImportSourceMapping>();

  async createImportJob(tko_input: CreateImportJobInput): Promise<ImportJob> {
    const tko_existing = Array.from(this.tko_jobs.values()).find(tko_job => tko_job.tenantId === tko_input.actor.tenantId && tko_job.idempotencyKey === tko_input.idempotencyKey);
    if (tko_existing) return tko_clone(tko_existing);
    const tko_now = new Date();
    const tko_job: ImportJob = { id: crypto.randomUUID(), tenantId: tko_input.actor.tenantId, type: "import_job", source: tko_input.source, status: "draft", name: tko_input.name.trim(), sourceObjectKey: tko_input.sourceObjectKey ?? null, createdByMemberId: tko_input.actor.memberId, idempotencyKey: tko_input.idempotencyKey, totalRecords: 0, importedRecords: 0, warningCount: 0, errorCount: 0, cursor: null, createdAt: tko_now, updatedAt: tko_now, completedAt: null };
    this.tko_jobs.set(tko_job.id, tko_job); await this.tko_emit(tko_input.actor, "ecosystem.import_job_created.v1", "ecosystem.import", { importJobId: tko_job.id, source: tko_job.source }, "ecosystem.import_job.created", "import_job", tko_job.id, tko_input.correlationId); return tko_clone(tko_job);
  }
  async listImportJobs(tko_tenantId: string): Promise<ImportJob[]> { return Array.from(this.tko_jobs.values()).filter(tko_job => tko_job.tenantId === tko_tenantId).sort((a, b) => b.updatedAt.getTime() - a.updatedAt.getTime()).map(tko_clone); }
  async getImportJob(tko_tenantId: string, tko_jobId: string): Promise<ImportJob | null> { const tko_job = this.tko_jobs.get(tko_jobId); return tko_job?.tenantId === tko_tenantId ? tko_clone(tko_job) : null; }
  async setImportJobStatus(tko_actor: PlatformActor, tko_input: { jobId: string; status: ImportJobStatus; cursor?: string | null; correlationId: string }): Promise<ImportJob> { const tko_job = this.tko_jobs.get(tko_input.jobId); if (!tko_job || tko_job.tenantId !== tko_actor.tenantId) throw new Error("IMPORT_JOB_NOT_FOUND"); tko_job.status = tko_input.status; tko_job.cursor = tko_input.cursor ?? tko_job.cursor; tko_job.updatedAt = new Date(); tko_job.completedAt = ["completed", "failed", "cancelled"].includes(tko_job.status) ? new Date() : null; await this.tko_emit(tko_actor, "ecosystem.import_job_status_changed.v1", "ecosystem.import", { importJobId: tko_job.id, status: tko_job.status }, "ecosystem.import_job.status_changed", "import_job", tko_job.id, tko_input.correlationId); return tko_clone(tko_job); }
  async stageImportRecords(tko_actor: PlatformActor, tko_input: { jobId: string; records: StageImportRecordInput[]; correlationId: string }): Promise<ImportStagingRecord[]> { const tko_job = this.tko_jobs.get(tko_input.jobId); if (!tko_job || tko_job.tenantId !== tko_actor.tenantId) throw new Error("IMPORT_JOB_NOT_FOUND"); const tko_output: ImportStagingRecord[] = []; for (const tko_inputRecord of tko_input.records) { const tko_existing = Array.from(this.tko_records.values()).find(tko_record => tko_record.tenantId === tko_actor.tenantId && tko_record.importJobId === tko_job.id && tko_record.sourceRecordId === tko_inputRecord.sourceRecordId); const tko_now = new Date(); const tko_record: ImportStagingRecord = tko_existing ?? { id: crypto.randomUUID(), tenantId: tko_actor.tenantId, type: "import_staging_record", importJobId: tko_job.id, sourceRecordId: tko_inputRecord.sourceRecordId, sourceType: tko_inputRecord.sourceType, status: tko_inputRecord.status ?? "staged", payload: tko_clone(tko_inputRecord.payload), validation: tko_clone(tko_inputRecord.validation ?? {}), targetKind: tko_inputRecord.targetKind ?? null, targetEntityId: null, sourceUpdatedAt: tko_inputRecord.sourceUpdatedAt ?? null, createdAt: tko_now, updatedAt: tko_now }; if (tko_existing) { tko_record.status = tko_inputRecord.status ?? tko_record.status; tko_record.payload = tko_clone(tko_inputRecord.payload); tko_record.validation = tko_clone(tko_inputRecord.validation ?? {}); tko_record.targetKind = tko_inputRecord.targetKind ?? tko_record.targetKind; tko_record.sourceUpdatedAt = tko_inputRecord.sourceUpdatedAt ?? tko_record.sourceUpdatedAt; tko_record.updatedAt = tko_now; } this.tko_records.set(tko_record.id, tko_record); tko_output.push(tko_clone(tko_record)); } tko_job.totalRecords = Array.from(this.tko_records.values()).filter(tko_record => tko_record.importJobId === tko_job.id).length; tko_job.status = "parsed"; tko_job.updatedAt = new Date(); await this.tko_emit(tko_actor, "ecosystem.import_records_staged.v1", "ecosystem.import", { importJobId: tko_job.id, count: tko_output.length }, "ecosystem.import_records.staged", "import_job", tko_job.id, tko_input.correlationId); return tko_output; }
  async listStagingRecords(tko_tenantId: string, tko_jobId: string): Promise<ImportStagingRecord[]> { return Array.from(this.tko_records.values()).filter(tko_record => tko_record.tenantId === tko_tenantId && tko_record.importJobId === tko_jobId).sort((a, b) => a.createdAt.getTime() - b.createdAt.getTime()).map(tko_clone); }
  async saveImportMapping(tko_actor: PlatformActor, tko_input: Parameters<EcosystemStore["saveImportMapping"]>[1]): Promise<ImportMapping> { if (!await this.getImportJob(tko_actor.tenantId, tko_input.jobId)) throw new Error("IMPORT_JOB_NOT_FOUND"); const tko_key = `${tko_actor.tenantId}:${tko_input.jobId}:${tko_input.sourceType}`; const tko_now = new Date(); const tko_existing = this.tko_mappings.get(tko_key); const tko_mapping: ImportMapping = { id: tko_existing?.id ?? crypto.randomUUID(), tenantId: tko_actor.tenantId, type: "import_mapping", importJobId: tko_input.jobId, sourceType: tko_input.sourceType, targetKind: tko_input.targetKind, duplicateStrategy: tko_input.duplicateStrategy, ownerMemberId: tko_input.ownerMemberId ?? null, fields: tko_clone(tko_input.fields), createdAt: tko_existing?.createdAt ?? tko_now, updatedAt: tko_now }; this.tko_mappings.set(tko_key, tko_mapping); await this.tko_emit(tko_actor, "ecosystem.import_mapping_saved.v1", "ecosystem.import", { importJobId: tko_mapping.importJobId, sourceType: tko_mapping.sourceType, targetKind: tko_mapping.targetKind }, "ecosystem.import_mapping.saved", "import_mapping", tko_mapping.id, tko_input.correlationId); return tko_clone(tko_mapping); }
  async listImportMappings(tko_tenantId: string, tko_jobId: string): Promise<ImportMapping[]> { return Array.from(this.tko_mappings.values()).filter(tko_mapping => tko_mapping.tenantId === tko_tenantId && tko_mapping.importJobId === tko_jobId).map(tko_clone); }
  async createImportBatch(tko_actor: PlatformActor, tko_input: Parameters<EcosystemStore["createImportBatch"]>[1]): Promise<ImportBatch> { const tko_existing = Array.from(this.tko_batches.values()).find(tko_batch => tko_batch.tenantId === tko_actor.tenantId && tko_batch.importJobId === tko_input.jobId && tko_batch.idempotencyKey === tko_input.idempotencyKey); if (tko_existing) return tko_clone(tko_existing); if (!await this.getImportJob(tko_actor.tenantId, tko_input.jobId)) throw new Error("IMPORT_JOB_NOT_FOUND"); const tko_sequence = Array.from(this.tko_batches.values()).filter(tko_batch => tko_batch.tenantId === tko_actor.tenantId && tko_batch.importJobId === tko_input.jobId).length + 1; const tko_batch: ImportBatch = { id: crypto.randomUUID(), tenantId: tko_actor.tenantId, type: "import_batch", importJobId: tko_input.jobId, sequence: tko_sequence, status: "queued", idempotencyKey: tko_input.idempotencyKey, recordIds: [...tko_input.recordIds], processedCount: 0, warningCount: 0, error: null, createdAt: new Date(), completedAt: null }; this.tko_batches.set(tko_batch.id, tko_batch); await this.tko_emit(tko_actor, "ecosystem.import_batch_queued.v1", "ecosystem.import", { importJobId: tko_batch.importJobId, batchId: tko_batch.id, sequence: tko_batch.sequence }, "ecosystem.import_batch.queued", "import_batch", tko_batch.id, tko_input.correlationId); return tko_clone(tko_batch); }
  async listImportBatches(tko_tenantId: string, tko_jobId: string): Promise<ImportBatch[]> { return Array.from(this.tko_batches.values()).filter(tko_batch => tko_batch.tenantId === tko_tenantId && tko_batch.importJobId === tko_jobId).sort((a, b) => a.sequence - b.sequence).map(tko_clone); }
  async getImportBatch(tko_tenantId: string, tko_batchId: string): Promise<ImportBatch | null> { const tko_batch = this.tko_batches.get(tko_batchId); return tko_batch?.tenantId === tko_tenantId ? tko_clone(tko_batch) : null; }
  async completeImportBatch(tko_actor: PlatformActor, tko_input: Parameters<EcosystemStore["completeImportBatch"]>[1]): Promise<ImportBatch> { const tko_batch = this.tko_batches.get(tko_input.batchId); if (!tko_batch || tko_batch.tenantId !== tko_actor.tenantId) throw new Error("IMPORT_BATCH_NOT_FOUND"); if (tko_batch.status === "completed") return tko_clone(tko_batch); for (const tko_imported of tko_input.imported) { const tko_record = this.tko_records.get(tko_imported.stagingRecordId); if (!tko_record || tko_record.tenantId !== tko_actor.tenantId) continue; tko_record.status = "imported"; tko_record.targetKind = tko_imported.targetKind; tko_record.targetEntityId = tko_imported.targetEntityId; tko_record.updatedAt = new Date(); const tko_mappingKey = `${tko_actor.tenantId}:${tko_batch.importJobId}:${tko_record.sourceRecordId}`; if (!this.tko_sourceMappings.has(tko_mappingKey)) this.tko_sourceMappings.set(tko_mappingKey, { id: crypto.randomUUID(), tenantId: tko_actor.tenantId, type: "import_source_mapping", importJobId: tko_batch.importJobId, sourceRecordId: tko_record.sourceRecordId, targetKind: tko_imported.targetKind, targetEntityId: tko_imported.targetEntityId, createdAt: new Date() }); }
    tko_batch.status = "completed"; tko_batch.processedCount = tko_input.imported.length; tko_batch.warningCount = tko_input.warnings; tko_batch.completedAt = new Date(); const tko_job = this.tko_jobs.get(tko_batch.importJobId); if (tko_job) { tko_job.importedRecords += tko_batch.processedCount; tko_job.warningCount += tko_batch.warningCount; tko_job.status = tko_job.importedRecords >= tko_job.totalRecords ? "completed" : "executing"; tko_job.updatedAt = new Date(); if (tko_job.status === "completed") tko_job.completedAt = new Date(); } await this.tko_emit(tko_actor, "ecosystem.import_batch_completed.v1", "ecosystem.import", { importJobId: tko_batch.importJobId, batchId: tko_batch.id, processedCount: tko_batch.processedCount }, "ecosystem.import_batch.completed", "import_batch", tko_batch.id, tko_input.correlationId); return tko_clone(tko_batch); }
  async listSourceMappings(tko_tenantId: string, tko_jobId: string): Promise<ImportSourceMapping[]> { return Array.from(this.tko_sourceMappings.values()).filter(tko_mapping => tko_mapping.tenantId === tko_tenantId && tko_mapping.importJobId === tko_jobId).map(tko_clone); }
  private async tko_emit(tko_actor: PlatformActor, tko_eventType: string, tko_topic: string, tko_payload: Record<string, unknown>, tko_action: string, tko_resourceType: string, tko_resourceId: string, tko_correlationId: string): Promise<void> { await getPlatformStore().writeDurableMutation({ actor: tko_actor, tenantId: tko_actor.tenantId, eventType: tko_eventType, topic: tko_topic, payload: tko_payload, auditAction: tko_action, resourceType: tko_resourceType, resourceId: tko_resourceId, correlationId: tko_correlationId }); }
}

export class PostgresEcosystemStore implements EcosystemStore {
  private readonly tko_pool: pg.Pool;
  constructor(tko_url: string) { this.tko_pool = new pg.Pool({ connectionString: tko_url, max: 10 }); }
  async createImportJob(tko_input: CreateImportJobInput): Promise<ImportJob> { return this.tko_tx(tko_input.actor.tenantId, async tko_client => { const tko_existing = await tko_client.query("select * from import_jobs where tenant_id=$1 and idempotency_key=$2", [tko_input.actor.tenantId, tko_input.idempotencyKey]); if (tko_existing.rowCount) return this.tko_jobRow(tko_existing.rows[0]); const tko_result = await tko_client.query("insert into import_jobs(id,tenant_id,source,status,name,source_object_key,created_by_member_id,idempotency_key) values($1,$2,$3,'draft',$4,$5,$6,$7) returning *", [crypto.randomUUID(), tko_input.actor.tenantId, tko_input.source, tko_input.name.trim(), tko_input.sourceObjectKey ?? null, tko_input.actor.memberId, tko_input.idempotencyKey]); const tko_job = this.tko_jobRow(tko_result.rows[0]); await this.tko_emit(tko_client, tko_input.actor, "ecosystem.import_job_created.v1", "ecosystem.import", { importJobId: tko_job.id, source: tko_job.source }, "ecosystem.import_job.created", "import_job", tko_job.id, tko_input.correlationId); return tko_job; }); }
  async listImportJobs(tko_tenantId: string): Promise<ImportJob[]> { return this.tko_read(tko_tenantId, async tko_client => (await tko_client.query("select * from import_jobs where tenant_id=$1 order by updated_at desc", [tko_tenantId])).rows.map(this.tko_jobRow)); }
  async getImportJob(tko_tenantId: string, tko_jobId: string): Promise<ImportJob | null> { return this.tko_read(tko_tenantId, async tko_client => { const tko_result = await tko_client.query("select * from import_jobs where tenant_id=$1 and id=$2", [tko_tenantId, tko_jobId]); return tko_result.rowCount ? this.tko_jobRow(tko_result.rows[0]) : null; }); }
  async setImportJobStatus(tko_actor: PlatformActor, tko_input: Parameters<EcosystemStore["setImportJobStatus"]>[1]): Promise<ImportJob> { return this.tko_tx(tko_actor.tenantId, async tko_client => { const tko_result = await tko_client.query("update import_jobs set status=$3,cursor=coalesce($4,cursor),updated_at=now(),completed_at=case when $3 in ('completed','failed','cancelled') then now() else null end where tenant_id=$1 and id=$2 returning *", [tko_actor.tenantId, tko_input.jobId, tko_input.status, tko_input.cursor ?? null]); if (!tko_result.rowCount) throw new Error("IMPORT_JOB_NOT_FOUND"); const tko_job = this.tko_jobRow(tko_result.rows[0]); await this.tko_emit(tko_client, tko_actor, "ecosystem.import_job_status_changed.v1", "ecosystem.import", { importJobId: tko_job.id, status: tko_job.status }, "ecosystem.import_job.status_changed", "import_job", tko_job.id, tko_input.correlationId); return tko_job; }); }
  async stageImportRecords(tko_actor: PlatformActor, tko_input: Parameters<EcosystemStore["stageImportRecords"]>[1]): Promise<ImportStagingRecord[]> { return this.tko_tx(tko_actor.tenantId, async tko_client => { const tko_job = await tko_client.query("select id from import_jobs where tenant_id=$1 and id=$2", [tko_actor.tenantId, tko_input.jobId]); if (!tko_job.rowCount) throw new Error("IMPORT_JOB_NOT_FOUND"); const tko_output: ImportStagingRecord[] = []; for (const tko_record of tko_input.records) { const tko_result = await tko_client.query("insert into import_staging_records(id,tenant_id,import_job_id,source_record_id,source_type,status,payload_json,validation_json,target_kind,source_updated_at) values($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9,$10) on conflict(tenant_id,import_job_id,source_record_id) do update set source_type=excluded.source_type,status=excluded.status,payload_json=excluded.payload_json,validation_json=excluded.validation_json,target_kind=excluded.target_kind,source_updated_at=excluded.source_updated_at,updated_at=now() returning *", [crypto.randomUUID(), tko_actor.tenantId, tko_input.jobId, tko_record.sourceRecordId, tko_record.sourceType, tko_record.status ?? "staged", JSON.stringify(tko_record.payload), JSON.stringify(tko_record.validation ?? {}), tko_record.targetKind ?? null, tko_record.sourceUpdatedAt ?? null]); tko_output.push(this.tko_recordRow(tko_result.rows[0])); } await tko_client.query("update import_jobs set total_records=(select count(*) from import_staging_records where tenant_id=$1 and import_job_id=$2),status='parsed',updated_at=now() where tenant_id=$1 and id=$2", [tko_actor.tenantId, tko_input.jobId]); await this.tko_emit(tko_client, tko_actor, "ecosystem.import_records_staged.v1", "ecosystem.import", { importJobId: tko_input.jobId, count: tko_output.length }, "ecosystem.import_records.staged", "import_job", tko_input.jobId, tko_input.correlationId); return tko_output; }); }
  async listStagingRecords(tko_tenantId: string, tko_jobId: string): Promise<ImportStagingRecord[]> { return this.tko_read(tko_tenantId, async tko_client => (await tko_client.query("select * from import_staging_records where tenant_id=$1 and import_job_id=$2 order by created_at", [tko_tenantId, tko_jobId])).rows.map(this.tko_recordRow)); }
  async saveImportMapping(tko_actor: PlatformActor, tko_input: Parameters<EcosystemStore["saveImportMapping"]>[1]): Promise<ImportMapping> { return this.tko_tx(tko_actor.tenantId, async tko_client => { const tko_result = await tko_client.query("insert into import_mappings(id,tenant_id,import_job_id,source_type,target_kind,duplicate_strategy,owner_member_id,fields_json) values($1,$2,$3,$4,$5,$6,$7,$8::jsonb) on conflict(tenant_id,import_job_id,source_type) do update set target_kind=excluded.target_kind,duplicate_strategy=excluded.duplicate_strategy,owner_member_id=excluded.owner_member_id,fields_json=excluded.fields_json,updated_at=now() returning *", [crypto.randomUUID(), tko_actor.tenantId, tko_input.jobId, tko_input.sourceType, tko_input.targetKind, tko_input.duplicateStrategy, tko_input.ownerMemberId ?? null, JSON.stringify(tko_input.fields)]); const tko_mapping = this.tko_mappingRow(tko_result.rows[0]); await this.tko_emit(tko_client, tko_actor, "ecosystem.import_mapping_saved.v1", "ecosystem.import", { importJobId: tko_mapping.importJobId, sourceType: tko_mapping.sourceType, targetKind: tko_mapping.targetKind }, "ecosystem.import_mapping.saved", "import_mapping", tko_mapping.id, tko_input.correlationId); return tko_mapping; }); }
  async listImportMappings(tko_tenantId: string, tko_jobId: string): Promise<ImportMapping[]> { return this.tko_read(tko_tenantId, async tko_client => (await tko_client.query("select * from import_mappings where tenant_id=$1 and import_job_id=$2 order by created_at", [tko_tenantId, tko_jobId])).rows.map(this.tko_mappingRow)); }
  async createImportBatch(tko_actor: PlatformActor, tko_input: Parameters<EcosystemStore["createImportBatch"]>[1]): Promise<ImportBatch> { return this.tko_tx(tko_actor.tenantId, async tko_client => { const tko_existing = await tko_client.query("select * from import_batches where tenant_id=$1 and import_job_id=$2 and idempotency_key=$3", [tko_actor.tenantId, tko_input.jobId, tko_input.idempotencyKey]); if (tko_existing.rowCount) return this.tko_batchRow(tko_existing.rows[0]); const tko_sequenceResult = await tko_client.query("select coalesce(max(sequence),0)+1 as next_sequence from import_batches where tenant_id=$1 and import_job_id=$2", [tko_actor.tenantId, tko_input.jobId]); const tko_result = await tko_client.query("insert into import_batches(id,tenant_id,import_job_id,sequence,status,idempotency_key,record_ids_json) values($1,$2,$3,$4,'queued',$5,$6::jsonb) returning *", [crypto.randomUUID(), tko_actor.tenantId, tko_input.jobId, Number(tko_sequenceResult.rows[0].next_sequence), tko_input.idempotencyKey, JSON.stringify(tko_input.recordIds)]); const tko_batch = this.tko_batchRow(tko_result.rows[0]); await this.tko_emit(tko_client, tko_actor, "ecosystem.import_batch_queued.v1", "ecosystem.import", { importJobId: tko_batch.importJobId, batchId: tko_batch.id, sequence: tko_batch.sequence }, "ecosystem.import_batch.queued", "import_batch", tko_batch.id, tko_input.correlationId); return tko_batch; }); }
  async listImportBatches(tko_tenantId: string, tko_jobId: string): Promise<ImportBatch[]> { return this.tko_read(tko_tenantId, async tko_client => (await tko_client.query("select * from import_batches where tenant_id=$1 and import_job_id=$2 order by sequence", [tko_tenantId, tko_jobId])).rows.map(this.tko_batchRow)); }
  async getImportBatch(tko_tenantId: string, tko_batchId: string): Promise<ImportBatch | null> { return this.tko_read(tko_tenantId, async tko_client => { const tko_result = await tko_client.query("select * from import_batches where tenant_id=$1 and id=$2", [tko_tenantId, tko_batchId]); return tko_result.rowCount ? this.tko_batchRow(tko_result.rows[0]) : null; }); }
  async completeImportBatch(tko_actor: PlatformActor, tko_input: Parameters<EcosystemStore["completeImportBatch"]>[1]): Promise<ImportBatch> { return this.tko_tx(tko_actor.tenantId, async tko_client => { const tko_existing = await tko_client.query("select * from import_batches where tenant_id=$1 and id=$2 for update", [tko_actor.tenantId, tko_input.batchId]); if (!tko_existing.rowCount) throw new Error("IMPORT_BATCH_NOT_FOUND"); if (String(tko_existing.rows[0].status) === "completed") return this.tko_batchRow(tko_existing.rows[0]); for (const tko_imported of tko_input.imported) { const tko_recordResult = await tko_client.query("update import_staging_records set status='imported',target_kind=$3,target_entity_id=$4,updated_at=now() where tenant_id=$1 and id=$2 returning source_record_id", [tko_actor.tenantId, tko_imported.stagingRecordId, tko_imported.targetKind, tko_imported.targetEntityId]); if (tko_recordResult.rowCount) await tko_client.query("insert into import_source_mappings(id,tenant_id,import_job_id,source_record_id,target_kind,target_entity_id) values($1,$2,$3,$4,$5,$6) on conflict(tenant_id,import_job_id,source_record_id) do nothing", [crypto.randomUUID(), tko_actor.tenantId, String(tko_existing.rows[0].import_job_id), String(tko_recordResult.rows[0].source_record_id), tko_imported.targetKind, tko_imported.targetEntityId]); }
    const tko_result = await tko_client.query("update import_batches set status='completed',processed_count=$3,warning_count=$4,completed_at=now() where tenant_id=$1 and id=$2 returning *", [tko_actor.tenantId, tko_input.batchId, tko_input.imported.length, tko_input.warnings]); const tko_batch = this.tko_batchRow(tko_result.rows[0]); await tko_client.query("update import_jobs set imported_records=imported_records+$3,warning_count=warning_count+$4,status=case when imported_records+$3 >= total_records then 'completed' else 'executing' end,updated_at=now(),completed_at=case when imported_records+$3 >= total_records then now() else completed_at end where tenant_id=$1 and id=$2", [tko_actor.tenantId, tko_batch.importJobId, tko_batch.processedCount, tko_batch.warningCount]); await this.tko_emit(tko_client, tko_actor, "ecosystem.import_batch_completed.v1", "ecosystem.import", { importJobId: tko_batch.importJobId, batchId: tko_batch.id, processedCount: tko_batch.processedCount }, "ecosystem.import_batch.completed", "import_batch", tko_batch.id, tko_input.correlationId); return tko_batch; }); }
  async listSourceMappings(tko_tenantId: string, tko_jobId: string): Promise<ImportSourceMapping[]> { return this.tko_read(tko_tenantId, async tko_client => (await tko_client.query("select * from import_source_mappings where tenant_id=$1 and import_job_id=$2 order by created_at", [tko_tenantId, tko_jobId])).rows.map(this.tko_sourceMappingRow)); }
  private async tko_read<T>(tko_tenantId: string, tko_operation: (tko_client: PoolClient) => Promise<T>): Promise<T> { const tko_client = await this.tko_pool.connect(); try { await tko_client.query("begin"); await tko_client.query("select set_config('app.tenant_id',$1,true)", [tko_tenantId]); const tko_value = await tko_operation(tko_client); await tko_client.query("commit"); return tko_value; } catch (tko_error) { await tko_client.query("rollback"); throw tko_error; } finally { tko_client.release(); } }
  private async tko_tx<T>(tko_tenantId: string, tko_operation: (tko_client: PoolClient) => Promise<T>): Promise<T> { return this.tko_read(tko_tenantId, tko_operation); }
  private async tko_emit(tko_client: PoolClient, tko_actor: PlatformActor, tko_eventType: string, tko_topic: string, tko_payload: Record<string, unknown>, tko_action: string, tko_resourceType: string, tko_resourceId: string, tko_correlationId: string): Promise<void> { await tko_client.query("insert into audit_logs(id,tenant_id,actor_auth_subject,action,resource_type,resource_id,correlation_id,metadata_json) values(gen_random_uuid(),$1,$2,$3,$4,$5,$6,'{}'::jsonb)", [tko_actor.tenantId, tko_actor.authSubject, tko_action, tko_resourceType, tko_resourceId, tko_correlationId]); await tko_client.query("insert into outbox(id,event_id,tenant_id,topic,event_type,payload_json,actor_auth_subject,correlation_id,status,attempts,available_at) values($1,$2,$3,$4,$5,$6::jsonb,$7,$8,'pending',0,now())", [crypto.randomUUID(), crypto.randomUUID(), tko_actor.tenantId, tko_topic, tko_eventType, JSON.stringify(tko_payload), tko_actor.authSubject, tko_correlationId]); }
  private tko_jobRow = (tko_row: TkoRow): ImportJob => ({ id: String(tko_row.id), tenantId: String(tko_row.tenant_id), type: "import_job", source: tko_row.source as ImportJob["source"], status: tko_row.status as ImportJobStatus, name: String(tko_row.name), sourceObjectKey: tko_row.source_object_key ? String(tko_row.source_object_key) : null, createdByMemberId: String(tko_row.created_by_member_id), idempotencyKey: String(tko_row.idempotency_key), totalRecords: Number(tko_row.total_records), importedRecords: Number(tko_row.imported_records), warningCount: Number(tko_row.warning_count), errorCount: Number(tko_row.error_count), cursor: tko_row.cursor ? String(tko_row.cursor) : null, createdAt: new Date(String(tko_row.created_at)), updatedAt: new Date(String(tko_row.updated_at)), completedAt: tko_date(tko_row.completed_at) });
  private tko_recordRow = (tko_row: TkoRow): ImportStagingRecord => ({ id: String(tko_row.id), tenantId: String(tko_row.tenant_id), type: "import_staging_record", importJobId: String(tko_row.import_job_id), sourceRecordId: String(tko_row.source_record_id), sourceType: String(tko_row.source_type), status: tko_row.status as ImportRecordStatus, payload: tko_json(tko_row.payload_json, {}), validation: tko_json(tko_row.validation_json, {}), targetKind: tko_row.target_kind as ImportTargetKind | null, targetEntityId: tko_row.target_entity_id ? String(tko_row.target_entity_id) : null, sourceUpdatedAt: tko_date(tko_row.source_updated_at), createdAt: new Date(String(tko_row.created_at)), updatedAt: new Date(String(tko_row.updated_at)) });
  private tko_mappingRow = (tko_row: TkoRow): ImportMapping => ({ id: String(tko_row.id), tenantId: String(tko_row.tenant_id), type: "import_mapping", importJobId: String(tko_row.import_job_id), sourceType: String(tko_row.source_type), targetKind: tko_row.target_kind as ImportTargetKind, duplicateStrategy: tko_row.duplicate_strategy as ImportMapping["duplicateStrategy"], ownerMemberId: tko_row.owner_member_id ? String(tko_row.owner_member_id) : null, fields: tko_json(tko_row.fields_json, []), createdAt: new Date(String(tko_row.created_at)), updatedAt: new Date(String(tko_row.updated_at)) });
  private tko_batchRow = (tko_row: TkoRow): ImportBatch => ({ id: String(tko_row.id), tenantId: String(tko_row.tenant_id), type: "import_batch", importJobId: String(tko_row.import_job_id), sequence: Number(tko_row.sequence), status: tko_row.status as ImportBatch["status"], idempotencyKey: String(tko_row.idempotency_key), recordIds: tko_json(tko_row.record_ids_json, []), processedCount: Number(tko_row.processed_count), warningCount: Number(tko_row.warning_count), error: tko_row.error ? String(tko_row.error) : null, createdAt: new Date(String(tko_row.created_at)), completedAt: tko_date(tko_row.completed_at) });
  private tko_sourceMappingRow = (tko_row: TkoRow): ImportSourceMapping => ({ id: String(tko_row.id), tenantId: String(tko_row.tenant_id), type: "import_source_mapping", importJobId: String(tko_row.import_job_id), sourceRecordId: String(tko_row.source_record_id), targetKind: tko_row.target_kind as ImportTargetKind, targetEntityId: String(tko_row.target_entity_id), createdAt: new Date(String(tko_row.created_at)) });
}

let tko_ecosystemStore: EcosystemStore | null = null;
export function getEcosystemStore(): EcosystemStore { if (!tko_ecosystemStore) tko_ecosystemStore = tko_config.postgresUrl ? new PostgresEcosystemStore(tko_config.postgresUrl) : new MemoryEcosystemStore(); return tko_ecosystemStore; }
export function setEcosystemStoreForTests(tko_store: EcosystemStore | null): void { tko_ecosystemStore = tko_store; }
