import { randomUUID } from "node:crypto";
import { Pool, type PoolClient } from "pg";
import type { PlatformActor } from "../../contracts/src/platform";
import type { BackupManifest, PlatformOperationalSnapshot, RestoreDrill, SaaSPlan, TenantEntitlement, TenantUsageRecord } from "../../contracts/src/saas";
import { tko_config } from "../../config/src/tasko-config";
import { getPlatformStore } from "./platform-store";

export interface SaaSStore {
  listPlans(): Promise<SaaSPlan[]>;
  getEntitlement(tko_tenantId: string): Promise<TenantEntitlement | null>;
  listUsage(tko_tenantId: string, tko_metric: string): Promise<TenantUsageRecord[]>;
  recordUsage(tko_actor: PlatformActor, tko_input: { metric: string; amount: number; idempotencyKey: string; correlationId: string }): Promise<{ record: TenantUsageRecord; created: boolean }>;
  createBackupManifest(tko_actor: PlatformActor, tko_input: { schemaVersion: string; checksum: string; objectKey: string | null; resourceCounts: Record<string, number>; correlationId: string }): Promise<BackupManifest>;
  listBackupManifests(tko_tenantId: string): Promise<BackupManifest[]>;
  getBackupManifest(tko_tenantId: string, tko_manifestId: string): Promise<BackupManifest | null>;
  createRestoreDrill(tko_actor: PlatformActor, tko_input: { backupManifestId: string; validation: Record<string, unknown>; correlationId: string }): Promise<RestoreDrill>;
  getOperationalSnapshot(): Promise<PlatformOperationalSnapshot>;
}

const tko_defaultPlans: SaaSPlan[] = [
  { key: "starter", name: "Starter", description: "Controlled pilot plan", entitlements: { automation: true, forms: true, exports: true }, quotas: { work_items: 5000, automation_executions: 1000, form_submissions: 2500 }, active: true },
  { key: "growth", name: "Growth", description: "Multi-team operations plan", entitlements: { automation: true, forms: true, exports: true, advanced_reporting: true }, quotas: { work_items: 25000, automation_executions: 10000, form_submissions: 25000 }, active: true },
];

function tko_clone<T>(tko_value: T): T { return structuredClone(tko_value); }
function tko_date(tko_value: unknown): Date { return new Date(String(tko_value)); }
function tko_json(tko_value: unknown): Record<string, unknown> { if (typeof tko_value === "string") { try { return JSON.parse(tko_value) as Record<string, unknown>; } catch { return {}; } } return (tko_value ?? {}) as Record<string, unknown>; }

export class MemorySaaSStore implements SaaSStore {
  readonly mode = "memory" as const;
  private readonly tko_plans: SaaSPlan[];
  private readonly tko_entitlements = new Map<string, TenantEntitlement>();
  private readonly tko_usage = new Map<string, TenantUsageRecord>();
  private readonly tko_backups = new Map<string, BackupManifest>();
  private readonly tko_drills = new Map<string, RestoreDrill>();

  constructor(tko_options: { plans?: SaaSPlan[] } = {}) { this.tko_plans = (tko_options.plans ?? tko_defaultPlans).map(tko_clone); }
  async listPlans(): Promise<SaaSPlan[]> { return this.tko_plans.map(tko_clone); }
  async getEntitlement(tko_tenantId: string): Promise<TenantEntitlement | null> {
    const tko_existing = this.tko_entitlements.get(tko_tenantId); if (tko_existing) return tko_clone(tko_existing);
    const tko_starter = this.tko_plans[0];
    const tko_next: TenantEntitlement = { tenantId: tko_tenantId, planKey: tko_starter.key, status: "trialing", entitlements: { ...tko_starter.entitlements }, quotas: { ...tko_starter.quotas }, billingCustomerRef: null, billingSubscriptionRef: null, updatedAt: new Date() };
    this.tko_entitlements.set(tko_tenantId, tko_next); return tko_clone(tko_next);
  }
  async listUsage(tko_tenantId: string, tko_metric: string): Promise<TenantUsageRecord[]> { return Array.from(this.tko_usage.values()).filter(tko_record => tko_record.tenantId === tko_tenantId && tko_record.metric === tko_metric).map(tko_clone); }
  async recordUsage(tko_actor: PlatformActor, tko_input: { metric: string; amount: number; idempotencyKey: string; correlationId: string }): Promise<{ record: TenantUsageRecord; created: boolean }> {
    const tko_key = `${tko_actor.tenantId}:${tko_input.metric}:${tko_input.idempotencyKey}`; const tko_existing = this.tko_usage.get(tko_key); if (tko_existing) return { record: tko_clone(tko_existing), created: false };
    const tko_record: TenantUsageRecord = { id: randomUUID(), tenantId: tko_actor.tenantId, metric: tko_input.metric, amount: tko_input.amount, idempotencyKey: tko_input.idempotencyKey, occurredAt: new Date() }; this.tko_usage.set(tko_key, tko_record);
    await getPlatformStore().writeDurableMutation({ actor: tko_actor, tenantId: tko_actor.tenantId, eventType: "saas.usage_recorded.v1", topic: "saas.usage", payload: { metric: tko_record.metric, amount: tko_record.amount, usageId: tko_record.id }, auditAction: "saas.usage.recorded", resourceType: "tenant_usage", resourceId: tko_record.id, correlationId: tko_input.correlationId });
    return { record: tko_clone(tko_record), created: true };
  }
  async createBackupManifest(tko_actor: PlatformActor, tko_input: { schemaVersion: string; checksum: string; objectKey: string | null; resourceCounts: Record<string, number>; correlationId: string }): Promise<BackupManifest> {
    const tko_manifest: BackupManifest = { id: randomUUID(), tenantId: tko_actor.tenantId, schemaVersion: tko_input.schemaVersion, checksum: tko_input.checksum, objectKey: tko_input.objectKey, status: "verified", resourceCounts: { ...tko_input.resourceCounts }, createdAt: new Date() }; this.tko_backups.set(tko_manifest.id, tko_manifest);
    await getPlatformStore().writeDurableMutation({ actor: tko_actor, tenantId: tko_actor.tenantId, eventType: "saas.backup_verified.v1", topic: "saas.backup", payload: { backupManifestId: tko_manifest.id, checksum: tko_manifest.checksum }, auditAction: "saas.backup.verified", resourceType: "tenant_backup_archive", resourceId: tko_manifest.id, correlationId: tko_input.correlationId }); return tko_clone(tko_manifest);
  }
  async listBackupManifests(tko_tenantId: string): Promise<BackupManifest[]> { return Array.from(this.tko_backups.values()).filter(tko_manifest => tko_manifest.tenantId === tko_tenantId).sort((tko_left, tko_right) => tko_right.createdAt.getTime() - tko_left.createdAt.getTime()).map(tko_clone); }
  async getBackupManifest(tko_tenantId: string, tko_manifestId: string): Promise<BackupManifest | null> { const tko_manifest = this.tko_backups.get(tko_manifestId); return tko_manifest?.tenantId === tko_tenantId ? tko_clone(tko_manifest) : null; }
  async createRestoreDrill(tko_actor: PlatformActor, tko_input: { backupManifestId: string; validation: Record<string, unknown>; correlationId: string }): Promise<RestoreDrill> {
    const tko_backup = await this.getBackupManifest(tko_actor.tenantId, tko_input.backupManifestId); if (!tko_backup) throw new Error("TASKO_BACKUP_NOT_FOUND");
    const tko_drill: RestoreDrill = { id: randomUUID(), tenantId: tko_actor.tenantId, backupManifestId: tko_backup.id, status: "verified", validation: { ...tko_input.validation }, createdAt: new Date(), completedAt: new Date() }; this.tko_drills.set(tko_drill.id, tko_drill);
    await getPlatformStore().writeDurableMutation({ actor: tko_actor, tenantId: tko_actor.tenantId, eventType: "saas.restore_verified.v1", topic: "saas.backup", payload: { restoreDrillId: tko_drill.id, backupManifestId: tko_backup.id }, auditAction: "saas.restore.verified", resourceType: "tenant_restore_drill", resourceId: tko_drill.id, correlationId: tko_input.correlationId }); return tko_clone(tko_drill);
  }
  async getOperationalSnapshot(): Promise<PlatformOperationalSnapshot> { const tko_tenants = await getPlatformStore().listTenants(); const tko_outbox = await getPlatformStore().listOutbox(); return { deploymentProfile: tko_config.deploymentProfile, tenants: { total: tko_tenants.length, active: tko_tenants.filter(tko_tenant => tko_tenant.status === "active").length, suspended: tko_tenants.filter(tko_tenant => tko_tenant.status === "suspended").length }, outbox: { pending: tko_outbox.filter(tko_row => tko_row.status === "pending").length, processing: tko_outbox.filter(tko_row => tko_row.status === "processing").length, deadLetter: tko_outbox.filter(tko_row => tko_row.status === "dead_letter").length }, generatedAt: new Date() }; }
}

export class PostgresSaaSStore implements SaaSStore {
  readonly mode = "postgres" as const;
  private readonly tko_pool: Pool;
  constructor(tko_connectionString: string) { this.tko_pool = new Pool({ connectionString: tko_connectionString }); }
  async listPlans(): Promise<SaaSPlan[]> { return (await this.tko_pool.query("select plan_key,name,description,entitlements_json,quotas_json,active from saas_plans where active=true order by plan_key")).rows.map(tko_row => ({ key: tko_row.plan_key, name: tko_row.name, description: tko_row.description, entitlements: tko_json(tko_row.entitlements_json) as Record<string, boolean>, quotas: tko_json(tko_row.quotas_json) as Record<string, number>, active: tko_row.active })); }
  async getEntitlement(tko_tenantId: string): Promise<TenantEntitlement | null> { const tko_result = await this.tko_pool.query("select * from tenant_entitlements where tenant_id=$1", [tko_tenantId]); const tko_row = tko_result.rows[0]; return tko_row ? { tenantId: tko_row.tenant_id, planKey: tko_row.plan_key, status: tko_row.status, entitlements: tko_json(tko_row.entitlements_json) as Record<string, boolean>, quotas: tko_json(tko_row.quotas_json) as Record<string, number>, billingCustomerRef: tko_row.billing_customer_ref, billingSubscriptionRef: tko_row.billing_subscription_ref, updatedAt: tko_date(tko_row.updated_at) } : null; }
  async listUsage(tko_tenantId: string, tko_metric: string): Promise<TenantUsageRecord[]> { return (await this.tko_pool.query("select * from tenant_usage_ledger where tenant_id=$1 and metric=$2 order by occurred_at", [tko_tenantId, tko_metric])).rows.map(tko_row => ({ id: tko_row.id, tenantId: tko_row.tenant_id, metric: tko_row.metric, amount: Number(tko_row.amount), idempotencyKey: tko_row.idempotency_key, occurredAt: tko_date(tko_row.occurred_at) })); }
  async recordUsage(tko_actor: PlatformActor, tko_input: { metric: string; amount: number; idempotencyKey: string; correlationId: string }): Promise<{ record: TenantUsageRecord; created: boolean }> {
    const tko_client = await this.tko_pool.connect(); try { await tko_client.query("BEGIN"); await tko_client.query("select set_config('app.tenant_id',$1,true)", [tko_actor.tenantId]); const tko_existing = await tko_client.query("select * from tenant_usage_ledger where tenant_id=$1 and metric=$2 and idempotency_key=$3", [tko_actor.tenantId, tko_input.metric, tko_input.idempotencyKey]); if (tko_existing.rowCount) { await tko_client.query("COMMIT"); return { record: { id: tko_existing.rows[0].id, tenantId: tko_actor.tenantId, metric: tko_input.metric, amount: Number(tko_existing.rows[0].amount), idempotencyKey: tko_input.idempotencyKey, occurredAt: tko_date(tko_existing.rows[0].occurred_at) }, created: false }; } const tko_record: TenantUsageRecord = { id: randomUUID(), tenantId: tko_actor.tenantId, metric: tko_input.metric, amount: tko_input.amount, idempotencyKey: tko_input.idempotencyKey, occurredAt: new Date() }; await tko_client.query("insert into tenant_usage_ledger(id,tenant_id,metric,amount,idempotency_key) values($1,$2,$3,$4,$5)", [tko_record.id, tko_record.tenantId, tko_record.metric, tko_record.amount, tko_record.idempotencyKey]); await this.tko_durable(tko_client, tko_actor, "saas.usage", "saas.usage_recorded.v1", { usageId: tko_record.id, metric: tko_record.metric, amount: tko_record.amount }, "saas.usage.recorded", "tenant_usage", tko_record.id, tko_input.correlationId); await tko_client.query("COMMIT"); return { record: tko_record, created: true }; } catch (tko_error) { await tko_client.query("ROLLBACK"); throw tko_error; } finally { tko_client.release(); }
  }
  async createBackupManifest(tko_actor: PlatformActor, tko_input: { schemaVersion: string; checksum: string; objectKey: string | null; resourceCounts: Record<string, number>; correlationId: string }): Promise<BackupManifest> { const tko_manifest: BackupManifest = { id: randomUUID(), tenantId: tko_actor.tenantId, schemaVersion: tko_input.schemaVersion, checksum: tko_input.checksum, objectKey: tko_input.objectKey, status: "verified", resourceCounts: tko_input.resourceCounts, createdAt: new Date() }; const tko_client = await this.tko_pool.connect(); try { await tko_client.query("BEGIN"); await tko_client.query("select set_config('app.tenant_id',$1,true)", [tko_actor.tenantId]); await tko_client.query("insert into tenant_backup_archives(id,tenant_id,schema_version,checksum,object_key,status,resource_counts_json) values($1,$2,$3,$4,$5,$6,$7::jsonb)", [tko_manifest.id, tko_manifest.tenantId, tko_manifest.schemaVersion, tko_manifest.checksum, tko_manifest.objectKey, tko_manifest.status, JSON.stringify(tko_manifest.resourceCounts)]); await this.tko_durable(tko_client, tko_actor, "saas.backup", "saas.backup_verified.v1", { backupManifestId: tko_manifest.id, checksum: tko_manifest.checksum }, "saas.backup.verified", "tenant_backup_archive", tko_manifest.id, tko_input.correlationId); await tko_client.query("COMMIT"); return tko_manifest; } catch (tko_error) { await tko_client.query("ROLLBACK"); throw tko_error; } finally { tko_client.release(); } }
  async listBackupManifests(tko_tenantId: string): Promise<BackupManifest[]> { return (await this.tko_pool.query("select * from tenant_backup_archives where tenant_id=$1 order by created_at desc", [tko_tenantId])).rows.map(tko_row => ({ id: tko_row.id, tenantId: tko_row.tenant_id, schemaVersion: tko_row.schema_version, checksum: tko_row.checksum, objectKey: tko_row.object_key, status: tko_row.status, resourceCounts: tko_json(tko_row.resource_counts_json) as Record<string, number>, createdAt: tko_date(tko_row.created_at) })); }
  async getBackupManifest(tko_tenantId: string, tko_manifestId: string): Promise<BackupManifest | null> { const tko_result = await this.tko_pool.query("select * from tenant_backup_archives where tenant_id=$1 and id=$2", [tko_tenantId, tko_manifestId]); const tko_row = tko_result.rows[0]; return tko_row ? { id: tko_row.id, tenantId: tko_row.tenant_id, schemaVersion: tko_row.schema_version, checksum: tko_row.checksum, objectKey: tko_row.object_key, status: tko_row.status, resourceCounts: tko_json(tko_row.resource_counts_json) as Record<string, number>, createdAt: tko_date(tko_row.created_at) } : null; }
  async createRestoreDrill(tko_actor: PlatformActor, tko_input: { backupManifestId: string; validation: Record<string, unknown>; correlationId: string }): Promise<RestoreDrill> { const tko_backup = await this.getBackupManifest(tko_actor.tenantId, tko_input.backupManifestId); if (!tko_backup) throw new Error("TASKO_BACKUP_NOT_FOUND"); const tko_drill: RestoreDrill = { id: randomUUID(), tenantId: tko_actor.tenantId, backupManifestId: tko_backup.id, status: "verified", validation: tko_input.validation, createdAt: new Date(), completedAt: new Date() }; const tko_client = await this.tko_pool.connect(); try { await tko_client.query("BEGIN"); await tko_client.query("select set_config('app.tenant_id',$1,true)", [tko_actor.tenantId]); await tko_client.query("insert into tenant_restore_drills(id,tenant_id,backup_manifest_id,status,validation_json,completed_at) values($1,$2,$3,$4,$5::jsonb,now())", [tko_drill.id, tko_drill.tenantId, tko_drill.backupManifestId, tko_drill.status, JSON.stringify(tko_drill.validation)]); await this.tko_durable(tko_client, tko_actor, "saas.backup", "saas.restore_verified.v1", { restoreDrillId: tko_drill.id, backupManifestId: tko_backup.id }, "saas.restore.verified", "tenant_restore_drill", tko_drill.id, tko_input.correlationId); await tko_client.query("COMMIT"); return tko_drill; } catch (tko_error) { await tko_client.query("ROLLBACK"); throw tko_error; } finally { tko_client.release(); } }
  async getOperationalSnapshot(): Promise<PlatformOperationalSnapshot> { const tko_tenants = await this.tko_pool.query("select status,count(*)::int as count from tenants group by status"); const tko_outbox = await this.tko_pool.query("select status,count(*)::int as count from outbox group by status"); const tko_tenantCount = (tko_status: string) => Number(tko_tenants.rows.find(tko_row => tko_row.status === tko_status)?.count ?? 0); const tko_outboxCount = (tko_status: string) => Number(tko_outbox.rows.find(tko_row => tko_row.status === tko_status)?.count ?? 0); return { deploymentProfile: tko_config.deploymentProfile, tenants: { total: tko_tenants.rows.reduce((tko_sum, tko_row) => tko_sum + Number(tko_row.count), 0), active: tko_tenantCount("active"), suspended: tko_tenantCount("suspended") }, outbox: { pending: tko_outboxCount("pending"), processing: tko_outboxCount("processing"), deadLetter: tko_outboxCount("dead_letter") }, generatedAt: new Date() }; }
  private async tko_durable(tko_client: PoolClient, tko_actor: PlatformActor, tko_topic: string, tko_eventType: string, tko_payload: Record<string, unknown>, tko_action: string, tko_resourceType: string, tko_resourceId: string, tko_correlationId: string): Promise<void> { await tko_client.query("insert into audit_logs(id,tenant_id,actor_auth_subject,action,resource_type,resource_id,correlation_id,metadata_json) values(gen_random_uuid(),$1,$2,$3,$4,$5,$6,'{}'::jsonb)", [tko_actor.tenantId, tko_actor.authSubject, tko_action, tko_resourceType, tko_resourceId, tko_correlationId]); await tko_client.query("insert into outbox(id,event_id,tenant_id,topic,event_type,payload_json,actor_auth_subject,correlation_id,status,attempts,available_at) values($1,$2,$3,$4,$5,$6::jsonb,$7,$8,'pending',0,now())", [randomUUID(), randomUUID(), tko_actor.tenantId, tko_topic, tko_eventType, JSON.stringify(tko_payload), tko_actor.authSubject, tko_correlationId]); }
}

let tko_saasStore: SaaSStore | null = null;
export function getSaaSStore(): SaaSStore { if (!tko_saasStore) tko_saasStore = tko_config.postgresUrl ? new PostgresSaaSStore(tko_config.postgresUrl) : new MemorySaaSStore(); return tko_saasStore; }
export function setSaaSStoreForTests(tko_store: SaaSStore | null): void { tko_saasStore = tko_store; }
