import type { PlatformActor } from "../../../packages/contracts/src/platform";
import type { ChannelNotificationLevel, ChatAttachmentUpload, CreateChannelInput, SaveMessageInput, SendMessageInput } from "../../../packages/contracts/src/chat";
import { getChatStore } from "../../../packages/database/src/chat-store";
import { getRedisAdapter } from "../../../packages/redis/src/redis-adapter";
import { getTenantAttachmentDownloadUrl, uploadTenantAttachment } from "../../attachments/src/attachment-storage";
import { requireCapability } from "../../permissions/src/authorization";

async function tko_channelFor(tko_actor: PlatformActor, tko_channelId: string) {
  const tko_channel = await getChatStore().getChannel(tko_actor.tenantId, tko_channelId);
  if (!tko_channel) throw new Error("CHAT_CHANNEL_NOT_FOUND");
  requireCapability(tko_actor, "chat.channel.read", tko_channel);
  return tko_channel;
}

export async function listChannels(tko_actor: PlatformActor) { requireCapability(tko_actor, "chat.channel.read", { tenantId: tko_actor.tenantId, type: "channel_directory", id: "directory", visibility: "internal" }); return getChatStore().listChannels(tko_actor.tenantId, tko_actor.memberId); }
export async function messages(tko_actor: PlatformActor, tko_channelId: string, tko_afterSeq?: number) { await tko_channelFor(tko_actor, tko_channelId); requireCapability(tko_actor, "chat.message.read", { tenantId: tko_actor.tenantId, type: "channel", id: tko_channelId, visibility: "internal" }); return getChatStore().listMessages(tko_actor.tenantId, tko_channelId, tko_afterSeq); }
export async function createChannel(tko_actor: PlatformActor, tko_input: Omit<CreateChannelInput, "tenantId">) { requireCapability(tko_actor, "chat.channel.manage", { tenantId: tko_actor.tenantId, type: "channel", id: "new", visibility: tko_input.visibility ?? "internal", explicitMemberIds: tko_input.memberIds }); return getChatStore().createChannel(tko_actor, { ...tko_input, tenantId: tko_actor.tenantId }); }
export async function sendMessage(tko_actor: PlatformActor, tko_input: Omit<SendMessageInput, "tenantId" | "authorMemberId" | "attachments"> & { attachments?: ChatAttachmentUpload[] }, tko_correlationId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_input.channelId); requireCapability(tko_actor, "chat.message.send", tko_channel); const tko_mentions = Array.from(new Set(tko_input.body.mentions ?? [])); if (tko_mentions.some(tko_memberId => tko_memberId === tko_actor.memberId || !tko_channel.memberIds.includes(tko_memberId))) throw new Error("CHAT_MENTION_MEMBER_NOT_IN_CHANNEL"); const tko_attachments = await Promise.all((tko_input.attachments ?? []).map(async tko_attachment => { const tko_bytes = Buffer.from(tko_attachment.dataBase64, "base64"); if (!tko_bytes.length || tko_bytes.length > 5_000_000 || !/^[a-z0-9][a-z0-9.+-]*\/[a-z0-9.+-]+$/i.test(tko_attachment.contentType)) throw new Error("CHAT_ATTACHMENT_INVALID"); return uploadTenantAttachment({ actor: tko_actor, filename: tko_attachment.filename, contentType: tko_attachment.contentType, bytes: tko_bytes }); })); return getChatStore().sendMessage(tko_actor, { ...tko_input, tenantId: tko_actor.tenantId, authorMemberId: tko_actor.memberId, attachments: tko_attachments }, tko_correlationId); }
export async function editMessage(tko_actor: PlatformActor, tko_messageId: string, tko_text: string, tko_correlationId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); const tko_action = tko_message.authorMemberId === tko_actor.memberId ? "chat.message.edit_own" : "chat.message.moderate"; requireCapability(tko_actor, tko_action, { tenantId: tko_actor.tenantId, type: "message", id: tko_messageId, visibility: "internal" }); return getChatStore().editMessage(tko_actor, tko_messageId, tko_text, tko_correlationId); }
export async function deleteMessage(tko_actor: PlatformActor, tko_messageId: string, tko_correlationId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); const tko_action = tko_message.authorMemberId === tko_actor.memberId ? "chat.message.delete_own" : "chat.message.moderate"; requireCapability(tko_actor, tko_action, { tenantId: tko_actor.tenantId, type: "message", id: tko_messageId, visibility: "internal" }); return getChatStore().deleteMessage(tko_actor, tko_messageId, tko_correlationId); }
export async function toggleReaction(tko_actor: PlatformActor, tko_messageId: string, tko_emoji: string, tko_correlationId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); requireCapability(tko_actor, "chat.reaction.toggle", { tenantId: tko_actor.tenantId, type: "message", id: tko_messageId, visibility: "internal" }); return getChatStore().toggleReaction(tko_actor, tko_messageId, tko_emoji, tko_correlationId); }
export async function readStates(tko_actor: PlatformActor) { requireCapability(tko_actor, "chat.channel.read", { tenantId: tko_actor.tenantId, type: "channel_directory", id: "directory", visibility: "internal" }); return getChatStore().listReadStates(tko_actor.tenantId, tko_actor.memberId); }
export async function markRead(tko_actor: PlatformActor, tko_channelId: string, tko_lastReadSeq: number) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); requireCapability(tko_actor, "chat.read_cursor.update", tko_channel); return getChatStore().updateReadState(tko_actor, tko_channelId, tko_lastReadSeq); }
export async function setNotificationPreference(tko_actor: PlatformActor, tko_channelId: string, tko_notificationLevel: ChannelNotificationLevel, tko_correlationId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); requireCapability(tko_actor, "chat.notification.manage", tko_channel); return getChatStore().setNotificationPreference(tko_actor, tko_channelId, tko_notificationLevel, tko_correlationId); }
export async function savedMessages(tko_actor: PlatformActor) { requireCapability(tko_actor, "chat.saved_message.manage", { tenantId: tko_actor.tenantId, type: "saved_messages", id: tko_actor.memberId, visibility: "internal", explicitMemberIds: [tko_actor.memberId] }); return getChatStore().listSavedMessages(tko_actor.tenantId, tko_actor.memberId); }
export async function saveMessage(tko_actor: PlatformActor, tko_messageId: string, tko_input: SaveMessageInput, tko_correlationId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); await tko_channelFor(tko_actor, tko_message.channelId); requireCapability(tko_actor, "chat.saved_message.manage", { tenantId: tko_actor.tenantId, type: "message", id: tko_messageId, visibility: "internal" }); return getChatStore().saveMessage(tko_actor, tko_messageId, tko_input, tko_correlationId); }
export async function search(tko_actor: PlatformActor, tko_query: string) { requireCapability(tko_actor, "chat.search", { tenantId: tko_actor.tenantId, type: "search", id: "chat", visibility: "internal" }); return getChatStore().search(tko_actor.tenantId, tko_actor.memberId, tko_query); }
export async function linkWorkItem(tko_actor: PlatformActor, tko_messageId: string, tko_workItemId: string, tko_correlationId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); requireCapability(tko_actor, "chat.message.send", { tenantId: tko_actor.tenantId, type: "message", id: tko_messageId, visibility: "internal" }); return getChatStore().linkWorkItem(tko_actor, tko_messageId, tko_workItemId, tko_correlationId); }
export async function attachmentUrl(tko_actor: PlatformActor, tko_messageId: string, tko_attachmentId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); await tko_channelFor(tko_actor, tko_message.channelId); const tko_attachment = tko_message.attachments.find(tko_item => tko_item.id === tko_attachmentId); if (!tko_attachment) throw new Error("CHAT_ATTACHMENT_NOT_FOUND"); return { url: await getTenantAttachmentDownloadUrl(tko_actor, tko_attachment) }; }
export async function setPresence(tko_actor: PlatformActor, tko_status: "online" | "away" | "offline") { const tko_redis = getRedisAdapter(); const tko_limit = await tko_redis.takeRateLimit(`chat:presence:${tko_actor.tenantId}:${tko_actor.memberId}`, 30, 60_000); if (!tko_limit.allowed) throw new Error("CHAT_PRESENCE_RATE_LIMITED"); const tko_payload = { memberId: tko_actor.memberId, status: tko_status, expiresAt: Date.now() + 90_000 }; await tko_redis.setCache(`chat:presence:${tko_actor.tenantId}:${tko_actor.memberId}`, JSON.stringify(tko_payload), 90_000); await tko_redis.publishTenant({ tenantId: tko_actor.tenantId, eventId: crypto.randomUUID(), eventType: "chat.presence_updated.v1", payload: tko_payload }); return tko_payload; }
export async function presence(tko_actor: PlatformActor, tko_channelId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); const tko_redis = getRedisAdapter(); const tko_statuses = await Promise.all(tko_channel.memberIds.map(async tko_memberId => { const tko_cached = await tko_redis.getCache(`chat:presence:${tko_actor.tenantId}:${tko_memberId}`); if (!tko_cached) return { memberId: tko_memberId, status: "offline" as const, expiresAt: 0 }; try { const tko_value = JSON.parse(tko_cached); return { memberId: tko_memberId, status: tko_value.status === "away" || tko_value.status === "online" ? tko_value.status : "offline", expiresAt: Number(tko_value.expiresAt) || 0 } as const; } catch { return { memberId: tko_memberId, status: "offline" as const, expiresAt: 0 }; } })); return tko_statuses; }
export async function setTyping(tko_actor: PlatformActor, tko_channelId: string, tko_isTyping: boolean) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); requireCapability(tko_actor, "chat.message.send", tko_channel); const tko_redis = getRedisAdapter(); const tko_limit = await tko_redis.takeRateLimit(`chat:typing:${tko_actor.tenantId}:${tko_actor.memberId}`, 120, 60_000); if (!tko_limit.allowed) throw new Error("CHAT_TYPING_RATE_LIMITED"); const tko_payload = { channelId: tko_channelId, memberId: tko_actor.memberId, isTyping: tko_isTyping, expiresAt: Date.now() + 8_000 }; await tko_redis.setCache(`chat:typing:${tko_actor.tenantId}:${tko_channelId}:${tko_actor.memberId}`, JSON.stringify(tko_payload), 8_000); await tko_redis.publishTenant({ tenantId: tko_actor.tenantId, eventId: crypto.randomUUID(), eventType: "chat.typing_updated.v1", payload: tko_payload }); return tko_payload; }
export async function typing(tko_actor: PlatformActor, tko_channelId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); const tko_redis = getRedisAdapter(); const tko_indicators = await Promise.all(tko_channel.memberIds.filter(tko_memberId => tko_memberId !== tko_actor.memberId).map(async tko_memberId => { const tko_cached = await tko_redis.getCache(`chat:typing:${tko_actor.tenantId}:${tko_channelId}:${tko_memberId}`); if (!tko_cached) return null; try { const tko_value = JSON.parse(tko_cached); return tko_value.isTyping && Number(tko_value.expiresAt) > Date.now() ? { channelId: tko_channelId, memberId: tko_memberId, isTyping: true, expiresAt: Number(tko_value.expiresAt) } : null; } catch { return null; } })); return tko_indicators.filter((tko_value): tko_value is NonNullable<typeof tko_value> => Boolean(tko_value)); }
export function seedDemo(tko_actor: PlatformActor) { return getChatStore().seedDemo(tko_actor); }
