import type { PlatformActor } from "../../../packages/contracts/src/platform";
import type { ChannelNotificationLevel, ChatAttachmentUpload, CreateChannelInput, SaveMessageInput, SendMessageInput, UpdateChannelInput } from "../../../packages/contracts/src/chat";
import { getChatStore } from "../../../packages/database/src/chat-store";
import { getPlatformStore } from "../../../packages/database/src/platform-store";
import { getRedisAdapter } from "../../../packages/redis/src/redis-adapter";
import { getTenantAttachmentDownloadUrl, uploadTenantAttachment } from "../../attachments/src/attachment-storage";
import { requireCapability } from "../../permissions/src/authorization";

async function tko_channelFor(tko_actor: PlatformActor, tko_channelId: string) {
  const tko_channel = await getChatStore().getChannel(tko_actor.tenantId, tko_channelId);
  if (!tko_channel || tko_channel.archivedAt) throw new Error("CHAT_CHANNEL_NOT_FOUND");
  requireCapability(tko_actor, "chat.channel.read", tko_channel);
  return tko_channel;
}

export async function listChannels(tko_actor: PlatformActor) { requireCapability(tko_actor, "chat.channel.read", { tenantId: tko_actor.tenantId, type: "channel_directory", id: "directory", visibility: "internal" }); return getChatStore().listChannels(tko_actor.tenantId, tko_actor.memberId); }
export async function messages(tko_actor: PlatformActor, tko_channelId: string, tko_afterSeq?: number) { await tko_channelFor(tko_actor, tko_channelId); requireCapability(tko_actor, "chat.message.read", { tenantId: tko_actor.tenantId, type: "channel", id: tko_channelId, visibility: "internal" }); return getChatStore().listMessages(tko_actor.tenantId, tko_channelId, tko_afterSeq); }
export async function createChannel(tko_actor: PlatformActor, tko_input: Omit<CreateChannelInput, "tenantId">) { const tko_memberIds = tko_input.kind === "private" || tko_input.kind === "group_dm" ? Array.from(new Set([tko_actor.memberId, ...tko_input.memberIds])) : tko_input.memberIds; requireCapability(tko_actor, "chat.channel.manage", { tenantId: tko_actor.tenantId, type: "channel", id: "new", visibility: tko_input.visibility ?? "internal", explicitMemberIds: tko_memberIds }); return getChatStore().createChannel(tko_actor, { ...tko_input, memberIds: tko_memberIds, tenantId: tko_actor.tenantId }); }
async function tko_activeChannelMembers(tko_actor: PlatformActor, tko_channelId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); const tko_members = await getPlatformStore().listTenantMembers(tko_actor.tenantId); return tko_members.filter(tko_member => tko_channel.memberIds.includes(tko_member.id)); }
export async function channelMemberCandidates(tko_actor: PlatformActor, tko_channelId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); requireCapability(tko_actor, "chat.channel.manage", tko_channel); const tko_members = await getPlatformStore().listTenantMembers(tko_actor.tenantId); return tko_members.map(tko_member => ({ id: tko_member.id, displayName: tko_member.displayName, role: tko_member.role, isInChannel: tko_channel.memberIds.includes(tko_member.id) })); }
export async function updateChannel(tko_actor: PlatformActor, tko_channelId: string, tko_input: UpdateChannelInput, tko_correlationId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); if (tko_channel.kind !== "public" && tko_channel.kind !== "private") throw new Error("CHAT_CHANNEL_MANAGEMENT_UNSUPPORTED"); requireCapability(tko_actor, "chat.channel.manage", tko_channel); return getChatStore().updateChannel(tko_actor, tko_channelId, tko_input, tko_correlationId); }
export async function archiveChannel(tko_actor: PlatformActor, tko_channelId: string, tko_correlationId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); if (tko_channel.kind !== "public" && tko_channel.kind !== "private") throw new Error("CHAT_CHANNEL_MANAGEMENT_UNSUPPORTED"); requireCapability(tko_actor, "chat.channel.manage", tko_channel); return getChatStore().archiveChannel(tko_actor, tko_channelId, tko_correlationId); }
export async function deleteChannel(tko_actor: PlatformActor, tko_channelId: string, tko_correlationId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); if (tko_channel.kind !== "public" && tko_channel.kind !== "private") throw new Error("CHAT_CHANNEL_MANAGEMENT_UNSUPPORTED"); requireCapability(tko_actor, "chat.channel.manage", tko_channel); return getChatStore().deleteChannel(tko_actor, tko_channelId, tko_correlationId); }
export async function addChannelMembers(tko_actor: PlatformActor, tko_channelId: string, tko_memberIds: string[], tko_correlationId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); if (tko_channel.kind !== "private" && tko_channel.kind !== "group_dm") throw new Error("CHAT_CHANNEL_MEMBERSHIP_MANAGEMENT_UNSUPPORTED"); requireCapability(tko_actor, "chat.channel.manage", tko_channel); const tko_activeMemberIds = new Set((await getPlatformStore().listTenantMembers(tko_actor.tenantId)).map(tko_member => tko_member.id)); if (tko_memberIds.some(tko_memberId => !tko_activeMemberIds.has(tko_memberId))) throw new Error("CHAT_CHANNEL_MEMBER_NOT_FOUND"); return getChatStore().addChannelMembers(tko_actor, tko_channelId, Array.from(new Set(tko_memberIds)), tko_correlationId); }
export async function removeChannelMember(tko_actor: PlatformActor, tko_channelId: string, tko_memberId: string, tko_correlationId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); if (tko_channel.kind !== "private" && tko_channel.kind !== "group_dm") throw new Error("CHAT_CHANNEL_MEMBERSHIP_MANAGEMENT_UNSUPPORTED"); requireCapability(tko_actor, "chat.channel.manage", tko_channel); if (!tko_channel.memberIds.includes(tko_memberId)) throw new Error("CHAT_CHANNEL_MEMBER_NOT_FOUND"); return getChatStore().removeChannelMember(tko_actor, tko_channelId, tko_memberId, tko_correlationId); }
export async function sendMessage(tko_actor: PlatformActor, tko_input: Omit<SendMessageInput, "tenantId" | "authorMemberId" | "attachments"> & { attachments?: ChatAttachmentUpload[] }, tko_correlationId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_input.channelId); requireCapability(tko_actor, "chat.message.send", tko_channel); const tko_explicitMentions = Array.from(new Set(tko_input.body.mentions ?? [])); if (tko_explicitMentions.some(tko_memberId => tko_memberId === tko_actor.memberId || !tko_channel.memberIds.includes(tko_memberId))) throw new Error("CHAT_MENTION_MEMBER_NOT_IN_CHANNEL"); let tko_broadcastMentions: string[] = []; if (tko_input.body.broadcastMention === "channel") tko_broadcastMentions = (await tko_activeChannelMembers(tko_actor, tko_channel.id)).map(tko_member => tko_member.id).filter(tko_memberId => tko_memberId !== tko_actor.memberId); if (tko_input.body.broadcastMention === "here") { const tko_members = await tko_activeChannelMembers(tko_actor, tko_channel.id); const tko_redis = getRedisAdapter(); const tko_online = await Promise.all(tko_members.map(async tko_member => ({ id: tko_member.id, value: await tko_redis.getCache(`chat:presence:${tko_actor.tenantId}:${tko_member.id}`) }))); tko_broadcastMentions = tko_online.filter(tko_entry => tko_entry.id !== tko_actor.memberId && Boolean(tko_entry.value) && (() => { try { return JSON.parse(tko_entry.value!).status === "online"; } catch { return false; } })()).map(tko_entry => tko_entry.id); } let tko_parentMessageId = tko_input.parentMessageId ?? null; if (tko_parentMessageId) { const tko_parent = await getChatStore().getMessage(tko_actor.tenantId, tko_parentMessageId); if (!tko_parent || tko_parent.channelId !== tko_channel.id) throw new Error("CHAT_THREAD_PARENT_NOT_FOUND"); tko_parentMessageId = tko_parent.parentMessageId ?? tko_parent.id; } if (tko_input.body.quotedMessageId) { const tko_quote = await getChatStore().getMessage(tko_actor.tenantId, tko_input.body.quotedMessageId); if (!tko_quote || tko_quote.channelId !== tko_channel.id) throw new Error("CHAT_QUOTED_MESSAGE_NOT_FOUND"); } const tko_attachments = await Promise.all((tko_input.attachments ?? []).map(async tko_attachment => { const tko_bytes = Buffer.from(tko_attachment.dataBase64, "base64"); if (!tko_bytes.length || tko_bytes.length > 5_000_000 || !/^[a-z0-9][a-z0-9.+-]*\/[a-z0-9.+-]+$/i.test(tko_attachment.contentType)) throw new Error("CHAT_ATTACHMENT_INVALID"); return uploadTenantAttachment({ actor: tko_actor, filename: tko_attachment.filename, contentType: tko_attachment.contentType, bytes: tko_bytes }); })); return getChatStore().sendMessage(tko_actor, { ...tko_input, parentMessageId: tko_parentMessageId, body: { ...tko_input.body, mentions: Array.from(new Set([...tko_explicitMentions, ...tko_broadcastMentions])) }, tenantId: tko_actor.tenantId, authorMemberId: tko_actor.memberId, attachments: tko_attachments }, tko_correlationId); }
export async function editMessage(tko_actor: PlatformActor, tko_messageId: string, tko_text: string, tko_correlationId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); const tko_action = tko_message.authorMemberId === tko_actor.memberId ? "chat.message.edit_own" : "chat.message.moderate"; requireCapability(tko_actor, tko_action, { tenantId: tko_actor.tenantId, type: "message", id: tko_messageId, visibility: "internal" }); return getChatStore().editMessage(tko_actor, tko_messageId, tko_text, tko_correlationId); }
export async function deleteMessage(tko_actor: PlatformActor, tko_messageId: string, tko_correlationId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); const tko_action = tko_message.authorMemberId === tko_actor.memberId ? "chat.message.delete_own" : "chat.message.moderate"; requireCapability(tko_actor, tko_action, { tenantId: tko_actor.tenantId, type: "message", id: tko_messageId, visibility: "internal" }); return getChatStore().deleteMessage(tko_actor, tko_messageId, tko_correlationId); }
export async function toggleReaction(tko_actor: PlatformActor, tko_messageId: string, tko_emoji: string, tko_correlationId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); requireCapability(tko_actor, "chat.reaction.toggle", { tenantId: tko_actor.tenantId, type: "message", id: tko_messageId, visibility: "internal" }); return getChatStore().toggleReaction(tko_actor, tko_messageId, tko_emoji, tko_correlationId); }
export async function readStates(tko_actor: PlatformActor) { requireCapability(tko_actor, "chat.channel.read", { tenantId: tko_actor.tenantId, type: "channel_directory", id: "directory", visibility: "internal" }); return getChatStore().listReadStates(tko_actor.tenantId, tko_actor.memberId); }
export async function markRead(tko_actor: PlatformActor, tko_channelId: string, tko_lastReadSeq: number) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); requireCapability(tko_actor, "chat.read_cursor.update", tko_channel); return getChatStore().updateReadState(tko_actor, tko_channelId, tko_lastReadSeq); }
export async function setNotificationPreference(tko_actor: PlatformActor, tko_channelId: string, tko_notificationLevel: ChannelNotificationLevel, tko_correlationId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); requireCapability(tko_actor, "chat.notification.manage", tko_channel); return getChatStore().setNotificationPreference(tko_actor, tko_channelId, tko_notificationLevel, tko_correlationId); }
export async function savedMessages(tko_actor: PlatformActor) { requireCapability(tko_actor, "chat.saved_message.manage", { tenantId: tko_actor.tenantId, type: "saved_messages", id: tko_actor.memberId, visibility: "internal", explicitMemberIds: [tko_actor.memberId] }); return getChatStore().listSavedMessages(tko_actor.tenantId, tko_actor.memberId); }
export async function saveMessage(tko_actor: PlatformActor, tko_messageId: string, tko_input: SaveMessageInput, tko_correlationId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); await tko_channelFor(tko_actor, tko_message.channelId); requireCapability(tko_actor, "chat.saved_message.manage", { tenantId: tko_actor.tenantId, type: "message", id: tko_messageId, visibility: "internal" }); return getChatStore().saveMessage(tko_actor, tko_messageId, tko_input, tko_correlationId); }
export async function search(tko_actor: PlatformActor, tko_query: string) { requireCapability(tko_actor, "chat.search", { tenantId: tko_actor.tenantId, type: "search", id: "chat", visibility: "internal" }); return getChatStore().search(tko_actor.tenantId, tko_actor.memberId, tko_query); }
export async function linkWorkItem(tko_actor: PlatformActor, tko_messageId: string, tko_workItemId: string, tko_correlationId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); requireCapability(tko_actor, "chat.message.send", { tenantId: tko_actor.tenantId, type: "message", id: tko_messageId, visibility: "internal" }); return getChatStore().linkWorkItem(tko_actor, tko_messageId, tko_workItemId, tko_correlationId); }
export async function attachmentUrl(tko_actor: PlatformActor, tko_messageId: string, tko_attachmentId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); await tko_channelFor(tko_actor, tko_message.channelId); const tko_attachment = tko_message.attachments.find(tko_item => tko_item.id === tko_attachmentId); if (!tko_attachment) throw new Error("CHAT_ATTACHMENT_NOT_FOUND"); return { url: await getTenantAttachmentDownloadUrl(tko_actor, tko_attachment) }; }
export async function setPresence(tko_actor: PlatformActor, tko_status: "online" | "away" | "offline") { const tko_redis = getRedisAdapter(); const tko_limit = await tko_redis.takeRateLimit(`chat:presence:${tko_actor.tenantId}:${tko_actor.memberId}`, 30, 60_000); if (!tko_limit.allowed) throw new Error("CHAT_PRESENCE_RATE_LIMITED"); const tko_payload = { memberId: tko_actor.memberId, status: tko_status, expiresAt: Date.now() + 90_000 }; await tko_redis.setCache(`chat:presence:${tko_actor.tenantId}:${tko_actor.memberId}`, JSON.stringify(tko_payload), 90_000); await tko_redis.publishTenant({ tenantId: tko_actor.tenantId, eventId: crypto.randomUUID(), eventType: "chat.presence_updated.v1", payload: tko_payload }); return tko_payload; }
export async function presence(tko_actor: PlatformActor, tko_channelId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); const tko_redis = getRedisAdapter(); const tko_statuses = await Promise.all(tko_channel.memberIds.map(async tko_memberId => { const tko_cached = await tko_redis.getCache(`chat:presence:${tko_actor.tenantId}:${tko_memberId}`); if (!tko_cached) return { memberId: tko_memberId, status: "offline" as const, expiresAt: 0 }; try { const tko_value = JSON.parse(tko_cached); return { memberId: tko_memberId, status: tko_value.status === "away" || tko_value.status === "online" ? tko_value.status : "offline", expiresAt: Number(tko_value.expiresAt) || 0 } as const; } catch { return { memberId: tko_memberId, status: "offline" as const, expiresAt: 0 }; } })); return tko_statuses; }
export async function setTyping(tko_actor: PlatformActor, tko_channelId: string, tko_isTyping: boolean) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); requireCapability(tko_actor, "chat.message.send", tko_channel); const tko_redis = getRedisAdapter(); const tko_limit = await tko_redis.takeRateLimit(`chat:typing:${tko_actor.tenantId}:${tko_actor.memberId}`, 120, 60_000); if (!tko_limit.allowed) throw new Error("CHAT_TYPING_RATE_LIMITED"); const tko_payload = { channelId: tko_channelId, memberId: tko_actor.memberId, isTyping: tko_isTyping, expiresAt: Date.now() + 8_000 }; await tko_redis.setCache(`chat:typing:${tko_actor.tenantId}:${tko_channelId}:${tko_actor.memberId}`, JSON.stringify(tko_payload), 8_000); await tko_redis.publishTenant({ tenantId: tko_actor.tenantId, eventId: crypto.randomUUID(), eventType: "chat.typing_updated.v1", payload: tko_payload }); return tko_payload; }
export async function typing(tko_actor: PlatformActor, tko_channelId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); const tko_redis = getRedisAdapter(); const tko_indicators = await Promise.all(tko_channel.memberIds.filter(tko_memberId => tko_memberId !== tko_actor.memberId).map(async tko_memberId => { const tko_cached = await tko_redis.getCache(`chat:typing:${tko_actor.tenantId}:${tko_channelId}:${tko_memberId}`); if (!tko_cached) return null; try { const tko_value = JSON.parse(tko_cached); return tko_value.isTyping && Number(tko_value.expiresAt) > Date.now() ? { channelId: tko_channelId, memberId: tko_memberId, isTyping: true, expiresAt: Number(tko_value.expiresAt) } : null; } catch { return null; } })); return tko_indicators.filter((tko_value): tko_value is NonNullable<typeof tko_value> => Boolean(tko_value)); }
export function seedDemo(tko_actor: PlatformActor) { return getChatStore().seedDemo(tko_actor); }
