import type { PlatformActor } from "../../../packages/contracts/src/platform";
import type { ChannelNotificationLevel, ChatAttachmentUpload, ChatAuthor, ChatMessage, ChatSearchFilters, ChatTeamSummary, CreateChannelInput, MemberNotificationPrefs, SaveMessageInput, SendMessageInput, UpdateChannelInput } from "../../../packages/contracts/src/chat";
import type { ChatChannelCreationRole } from "../../../packages/contracts/src/platform";
import { getChatStore } from "../../../packages/database/src/chat-store";
import { getPlatformStore } from "../../../packages/database/src/platform-store";
import { tko_config } from "../../../packages/config/src/tasko-config";
import { getRedisAdapter } from "../../../packages/redis/src/redis-adapter";
import { getTenantAttachmentDownloadUrl, uploadTenantAttachment } from "../../attachments/src/attachment-storage";
import { requireCapability } from "../../permissions/src/authorization";
import { createHeartbeatJob, deleteHeartbeatJob, updateHeartbeatJob } from "../../../server/_core/heartbeat";

const tko_channelCreationRoles = new Set<ChatChannelCreationRole>(["owner", "admin", "member"]);
const tko_channelCreationResource = (tko_actor: PlatformActor) => ({ tenantId: tko_actor.tenantId, type: "tenant", id: tko_actor.tenantId, visibility: "internal" as const });
const tko_reminderCron = (tko_when: Date) => `0 ${tko_when.getUTCMinutes()} ${tko_when.getUTCHours()} ${tko_when.getUTCDate()} ${tko_when.getUTCMonth() + 1} *`;
async function tko_scheduleReminder(tko_actor: PlatformActor, tko_reminder: Awaited<ReturnType<ReturnType<typeof getChatStore>["createReminder"]>>, tko_sessionToken: string) {
  if (!tko_sessionToken || !tko_config.isProduction) return tko_reminder;
  const tko_job = { cron: tko_reminderCron(tko_reminder.reminderAt), path: "/api/scheduled/chat-reminder-push" as const, description: `Tasko reminder: ${tko_reminder.title.slice(0, 120)}` };
  if (tko_reminder.scheduleCronTaskUid) {
    await updateHeartbeatJob(tko_reminder.scheduleCronTaskUid, tko_job, tko_sessionToken);
    return getChatStore().setReminderSchedule(tko_actor, tko_reminder.id, tko_reminder.scheduleCronTaskUid);
  }
  const tko_created = await createHeartbeatJob({ name: `tasko-reminder-${tko_reminder.id}`, ...tko_job }, tko_sessionToken);
  return getChatStore().setReminderSchedule(tko_actor, tko_reminder.id, tko_created.taskUid);
}

async function tko_requireCanCreateChannel(tko_actor: PlatformActor) {
  requireCapability(tko_actor, "chat.channel.create", { tenantId: tko_actor.tenantId, type: "channel", id: "new", visibility: "internal" });
  const tko_settings = await getPlatformStore().getTenantSettings(tko_actor.tenantId);
  if (tko_actor.role !== "service_account" && (!tko_channelCreationRoles.has(tko_actor.role as ChatChannelCreationRole) || !tko_settings.chatChannelCreationRoles.includes(tko_actor.role as ChatChannelCreationRole))) throw new Error("CHAT_CHANNEL_CREATION_DISABLED_FOR_ROLE");
  return tko_settings;
}

async function tko_channelFor(tko_actor: PlatformActor, tko_channelId: string) {
  const tko_channel = await getChatStore().getChannel(tko_actor.tenantId, tko_channelId);
  if (!tko_channel || tko_channel.archivedAt) throw new Error("CHAT_CHANNEL_NOT_FOUND");
  requireCapability(tko_actor, "chat.channel.read", tko_channel);
  return tko_channel;
}

export async function listChannels(tko_actor: PlatformActor) { requireCapability(tko_actor, "chat.channel.read", { tenantId: tko_actor.tenantId, type: "channel_directory", id: "directory", visibility: "internal" }); return getChatStore().listChannels(tko_actor.tenantId, tko_actor.memberId); }
export async function messages(tko_actor: PlatformActor, tko_channelId: string, tko_afterSeq?: number) { await tko_channelFor(tko_actor, tko_channelId); requireCapability(tko_actor, "chat.message.read", { tenantId: tko_actor.tenantId, type: "channel", id: tko_channelId, visibility: "internal" }); return tko_withAuthors(tko_actor, await getChatStore().listMessages(tko_actor.tenantId, tko_channelId, tko_afterSeq)); }
export async function channelCreationPolicy(tko_actor: PlatformActor) {
  requireCapability(tko_actor, "chat.channel.read", { tenantId: tko_actor.tenantId, type: "channel_directory", id: "directory", visibility: "internal" });
  const tko_settings = await getPlatformStore().getTenantSettings(tko_actor.tenantId);
  const tko_allowed = tko_actor.role === "service_account" || (tko_channelCreationRoles.has(tko_actor.role as ChatChannelCreationRole) && tko_settings.chatChannelCreationRoles.includes(tko_actor.role as ChatChannelCreationRole));
  return { ...tko_settings, allowed: tko_allowed, canManage: tko_actor.role === "owner" || tko_actor.role === "admin" };
}

export async function updateChannelCreationPolicy(tko_actor: PlatformActor, tko_roles: ChatChannelCreationRole[], tko_correlationId: string) {
  requireCapability(tko_actor, "workspace.settings.manage", tko_channelCreationResource(tko_actor));
  return getPlatformStore().updateTenantSettings({ actor: tko_actor, tenantId: tko_actor.tenantId, settings: { chatChannelCreationRoles: Array.from(new Set<ChatChannelCreationRole>(["owner", ...tko_roles])) }, correlationId: tko_correlationId });
}

export async function channelCreationCandidates(tko_actor: PlatformActor) {
  await tko_requireCanCreateChannel(tko_actor);
  return (await getPlatformStore().listTenantMembers(tko_actor.tenantId)).map(tko_member => ({ id: tko_member.id, displayName: tko_member.displayName, role: tko_member.role, isActive: true }));
}

export async function createChannel(tko_actor: PlatformActor, tko_input: Omit<CreateChannelInput, "tenantId">) {
  await tko_requireCanCreateChannel(tko_actor);
  const tko_invited = Array.from(new Set(tko_input.memberIds));
  const tko_activeMembers = new Set((await getPlatformStore().listTenantMembers(tko_actor.tenantId)).map(tko_member => tko_member.id));
  if (tko_invited.some(tko_memberId => !tko_activeMembers.has(tko_memberId))) throw new Error("CHAT_CHANNEL_MEMBER_NOT_FOUND");
  const tko_memberIds = tko_input.kind === "private" || tko_input.kind === "group_dm" ? Array.from(new Set([tko_actor.memberId, ...tko_invited])) : tko_invited;
  return getChatStore().createChannel(tko_actor, { ...tko_input, memberIds: tko_memberIds, tenantId: tko_actor.tenantId });
}
async function tko_activeChannelMembers(tko_actor: PlatformActor, tko_channelId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); const tko_members = await getPlatformStore().listTenantMembers(tko_actor.tenantId); return tko_members.filter(tko_member => tko_channel.memberIds.includes(tko_member.id)); }
// Workspace removal is modeled as `suspended`: it leaves audit/history intact but removes the member from every interactive Chat surface.
async function tko_channelRoster(tko_actor: PlatformActor, tko_channelId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); const tko_members = await getPlatformStore().listTenantMembers(tko_actor.tenantId, { includeSuspended: true }); return tko_members.filter(tko_member => tko_channel.memberIds.includes(tko_member.id)); }
async function tko_authors(tko_actor: PlatformActor) { const tko_members = await getPlatformStore().listTenantMembers(tko_actor.tenantId, { includeSuspended: true }); const tko_authorMap = new Map<string, ChatAuthor>(tko_members.map(tko_member => [tko_member.id, { memberId: tko_member.id, displayName: tko_member.status === "active" ? tko_member.displayName : `${tko_member.displayName} (inactive account)`, role: tko_member.role, isActive: tko_member.status === "active" }])); if (!tko_authorMap.has(tko_actor.memberId)) tko_authorMap.set(tko_actor.memberId, { memberId: tko_actor.memberId, displayName: tko_actor.membershipStatus === "active" ? "Tasko member" : "Tasko member (inactive account)", role: tko_actor.role, isActive: tko_actor.membershipStatus === "active" }); return tko_authorMap; }
async function tko_withAuthors(tko_actor: PlatformActor, tko_messages: ChatMessage[]) { const tko_authorMap = await tko_authors(tko_actor); return tko_messages.map(tko_message => ({ ...tko_message, author: tko_authorMap.get(tko_message.authorMemberId) })); }
export async function channelMembers(tko_actor: PlatformActor, tko_channelId: string) {
  const tko_roster = await tko_channelRoster(tko_actor, tko_channelId);
  const tko_redis = getRedisAdapter();
  const tko_presence = new Map(await Promise.all(tko_roster.map(async tko_member => {
    const tko_cached = await tko_redis.getCache(`chat:presence:${tko_actor.tenantId}:${tko_member.id}`);
    if (!tko_cached) return [tko_member.id, "offline"] as const;
    try { const tko_value = JSON.parse(tko_cached); return [tko_member.id, tko_value.status === "online" || tko_value.status === "away" ? tko_value.status : "offline"] as const; } catch { return [tko_member.id, "offline"] as const; }
  })));
  return tko_roster.map(tko_member => ({ id: tko_member.id, displayName: tko_member.status === "active" ? tko_member.displayName : `${tko_member.displayName} (inactive account)`, role: tko_member.role, isActive: tko_member.status === "active", presenceStatus: tko_member.status === "active" ? tko_presence.get(tko_member.id) ?? "offline" : "offline" }));
}
export async function channelMemberCandidates(tko_actor: PlatformActor, tko_channelId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); requireCapability(tko_actor, "chat.channel.manage", tko_channel); const tko_members = await getPlatformStore().listTenantMembers(tko_actor.tenantId); return tko_members.map(tko_member => ({ id: tko_member.id, displayName: tko_member.displayName, role: tko_member.role, isActive: true, isInChannel: tko_channel.memberIds.includes(tko_member.id) })); }
export async function updateChannel(tko_actor: PlatformActor, tko_channelId: string, tko_input: UpdateChannelInput, tko_correlationId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); if (tko_channel.kind !== "public" && tko_channel.kind !== "private") throw new Error("CHAT_CHANNEL_MANAGEMENT_UNSUPPORTED"); requireCapability(tko_actor, "chat.channel.manage", tko_channel); return getChatStore().updateChannel(tko_actor, tko_channelId, tko_input, tko_correlationId); }
export async function archiveChannel(tko_actor: PlatformActor, tko_channelId: string, tko_correlationId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); if (tko_channel.kind !== "public" && tko_channel.kind !== "private") throw new Error("CHAT_CHANNEL_MANAGEMENT_UNSUPPORTED"); requireCapability(tko_actor, "chat.channel.manage", tko_channel); return getChatStore().archiveChannel(tko_actor, tko_channelId, tko_correlationId); }
export async function deleteChannel(tko_actor: PlatformActor, tko_channelId: string, tko_correlationId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); if (tko_channel.kind !== "public" && tko_channel.kind !== "private") throw new Error("CHAT_CHANNEL_MANAGEMENT_UNSUPPORTED"); requireCapability(tko_actor, "chat.channel.manage", tko_channel); return getChatStore().deleteChannel(tko_actor, tko_channelId, tko_correlationId); }
export async function addChannelMembers(tko_actor: PlatformActor, tko_channelId: string, tko_memberIds: string[], tko_correlationId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); if (tko_channel.kind === "dm") throw new Error("CHAT_CHANNEL_MEMBERSHIP_MANAGEMENT_UNSUPPORTED"); requireCapability(tko_actor, "chat.channel.manage", tko_channel); const tko_activeMemberIds = new Set((await getPlatformStore().listTenantMembers(tko_actor.tenantId)).map(tko_member => tko_member.id)); if (tko_memberIds.some(tko_memberId => !tko_activeMemberIds.has(tko_memberId))) throw new Error("CHAT_CHANNEL_MEMBER_NOT_FOUND"); return getChatStore().addChannelMembers(tko_actor, tko_channelId, Array.from(new Set(tko_memberIds)), tko_correlationId); }
export async function removeChannelMember(tko_actor: PlatformActor, tko_channelId: string, tko_memberId: string, tko_correlationId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); if (tko_channel.kind === "dm") throw new Error("CHAT_CHANNEL_MEMBERSHIP_MANAGEMENT_UNSUPPORTED"); requireCapability(tko_actor, "chat.channel.manage", tko_channel); if (!tko_channel.memberIds.includes(tko_memberId)) throw new Error("CHAT_CHANNEL_MEMBER_NOT_FOUND"); return getChatStore().removeChannelMember(tko_actor, tko_channelId, tko_memberId, tko_correlationId); }
export async function sendMessage(tko_actor: PlatformActor, tko_input: Omit<SendMessageInput, "tenantId" | "authorMemberId" | "attachments"> & { attachments?: ChatAttachmentUpload[] }, tko_correlationId: string) {
  const tko_channel = await tko_channelFor(tko_actor, tko_input.channelId);
  requireCapability(tko_actor, "chat.message.send", tko_channel);
  const tko_explicitMentions = Array.from(new Set(tko_input.body.mentions ?? []));
  if (tko_explicitMentions.some(tko_memberId => tko_memberId === tko_actor.memberId || !tko_channel.memberIds.includes(tko_memberId))) throw new Error("CHAT_MENTION_MEMBER_NOT_IN_CHANNEL");
  // @team mentions: validate the team exists (direct store query), then notify team members who are
  // channel members (spec 08 §5). Members outside the channel are silently skipped.
  const tko_teamMentionIds = Array.from(new Set(tko_input.body.teamMentions ?? []));
  const tko_teamMentionMembers: string[] = [];
  for (const tko_teamId of tko_teamMentionIds) {
    const tko_team = await getChatStore().getTeam(tko_actor.tenantId, tko_teamId);
    if (!tko_team) throw new Error("CHAT_TEAM_NOT_FOUND");
    const tko_teamMemberIds = await getChatStore().listTeamMemberIds(tko_actor.tenantId, tko_teamId);
    tko_teamMentionMembers.push(...tko_teamMemberIds.filter(tko_memberId => tko_memberId !== tko_actor.memberId && tko_channel.memberIds.includes(tko_memberId)));
  }
  let tko_broadcastMentions: string[] = []; if (tko_input.body.broadcastMention === "channel") tko_broadcastMentions = (await tko_activeChannelMembers(tko_actor, tko_channel.id)).map(tko_member => tko_member.id).filter(tko_memberId => tko_memberId !== tko_actor.memberId); if (tko_input.body.broadcastMention === "here") { const tko_members = await tko_activeChannelMembers(tko_actor, tko_channel.id); const tko_redis = getRedisAdapter(); const tko_online = await Promise.all(tko_members.map(async tko_member => ({ id: tko_member.id, value: await tko_redis.getCache(`chat:presence:${tko_actor.tenantId}:${tko_member.id}`) }))); tko_broadcastMentions = tko_online.filter(tko_entry => tko_entry.id !== tko_actor.memberId && Boolean(tko_entry.value) && (() => { try { return JSON.parse(tko_entry.value!).status === "online"; } catch { return false; } })()).map(tko_entry => tko_entry.id); } let tko_parentMessageId = tko_input.parentMessageId ?? null; if (tko_parentMessageId) { const tko_parent = await getChatStore().getMessage(tko_actor.tenantId, tko_parentMessageId); if (!tko_parent || tko_parent.channelId !== tko_channel.id) throw new Error("CHAT_THREAD_PARENT_NOT_FOUND"); tko_parentMessageId = tko_parent.parentMessageId ?? tko_parent.id; } if (tko_input.body.quotedMessageId) { const tko_quote = await getChatStore().getMessage(tko_actor.tenantId, tko_input.body.quotedMessageId); if (!tko_quote || tko_quote.channelId !== tko_channel.id) throw new Error("CHAT_QUOTED_MESSAGE_NOT_FOUND"); } const tko_attachments = await Promise.all((tko_input.attachments ?? []).map(async tko_attachment => { const tko_bytes = Buffer.from(tko_attachment.dataBase64, "base64"); if (!tko_bytes.length || tko_bytes.length > 5_000_000 || !/^[a-z0-9][a-z0-9.+-]*\/[a-z0-9.+-]+$/i.test(tko_attachment.contentType)) throw new Error("CHAT_ATTACHMENT_INVALID"); return uploadTenantAttachment({ actor: tko_actor, filename: tko_attachment.filename, contentType: tko_attachment.contentType, bytes: tko_bytes }); }));
  return getChatStore().sendMessage(tko_actor, { ...tko_input, parentMessageId: tko_parentMessageId, body: { ...tko_input.body, mentions: Array.from(new Set([...tko_explicitMentions, ...tko_broadcastMentions, ...tko_teamMentionMembers])), teamMentions: tko_teamMentionIds.length ? tko_teamMentionIds : undefined }, tenantId: tko_actor.tenantId, authorMemberId: tko_actor.memberId, attachments: tko_attachments }, tko_correlationId);
}
export async function editMessage(tko_actor: PlatformActor, tko_messageId: string, tko_text: string, tko_correlationId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); const tko_action = tko_message.authorMemberId === tko_actor.memberId ? "chat.message.edit_own" : "chat.message.moderate"; requireCapability(tko_actor, tko_action, { tenantId: tko_actor.tenantId, type: "message", id: tko_messageId, visibility: "internal" }); return getChatStore().editMessage(tko_actor, tko_messageId, tko_text, tko_correlationId); }
export async function deleteMessage(tko_actor: PlatformActor, tko_messageId: string, tko_correlationId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); const tko_action = tko_message.authorMemberId === tko_actor.memberId ? "chat.message.delete_own" : "chat.message.moderate"; requireCapability(tko_actor, tko_action, { tenantId: tko_actor.tenantId, type: "message", id: tko_messageId, visibility: "internal" }); return getChatStore().deleteMessage(tko_actor, tko_messageId, tko_correlationId); }
export async function toggleReaction(tko_actor: PlatformActor, tko_messageId: string, tko_emoji: string, tko_correlationId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); requireCapability(tko_actor, "chat.reaction.toggle", { tenantId: tko_actor.tenantId, type: "message", id: tko_messageId, visibility: "internal" }); return getChatStore().toggleReaction(tko_actor, tko_messageId, tko_emoji, tko_correlationId); }
export async function readStates(tko_actor: PlatformActor) { requireCapability(tko_actor, "chat.channel.read", { tenantId: tko_actor.tenantId, type: "channel_directory", id: "directory", visibility: "internal" }); return getChatStore().listReadStates(tko_actor.tenantId, tko_actor.memberId); }
export async function markRead(tko_actor: PlatformActor, tko_channelId: string, tko_lastReadSeq: number) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); requireCapability(tko_actor, "chat.read_cursor.update", tko_channel); return getChatStore().updateReadState(tko_actor, tko_channelId, tko_lastReadSeq); }
export async function setNotificationPreference(tko_actor: PlatformActor, tko_channelId: string, tko_notificationLevel: ChannelNotificationLevel, tko_correlationId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); requireCapability(tko_actor, "chat.notification.manage", tko_channel); return getChatStore().setNotificationPreference(tko_actor, tko_channelId, tko_notificationLevel, tko_correlationId); }
export async function savedMessages(tko_actor: PlatformActor) { requireCapability(tko_actor, "chat.saved_message.manage", { tenantId: tko_actor.tenantId, type: "saved_messages", id: tko_actor.memberId, visibility: "internal", explicitMemberIds: [tko_actor.memberId] }); return getChatStore().listSavedMessages(tko_actor.tenantId, tko_actor.memberId); }
export async function savedEntries(tko_actor: PlatformActor) { const tko_saved = await savedMessages(tko_actor); const tko_authorMap = await tko_authors(tko_actor); const tko_entries = await Promise.all(tko_saved.map(async tko_savedItem => { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_savedItem.messageId); if (!tko_message) return null; try { const tko_channel = await tko_channelFor(tko_actor, tko_message.channelId); return { saved: tko_savedItem, message: { ...tko_message, author: tko_authorMap.get(tko_message.authorMemberId) }, channel: { id: tko_channel.id, name: tko_channel.name, kind: tko_channel.kind } }; } catch { return null; } })); return tko_entries.filter((tko_entry): tko_entry is NonNullable<typeof tko_entry> => Boolean(tko_entry)); }
export async function reminders(tko_actor: PlatformActor, tko_includeCompleted = false) { requireCapability(tko_actor, "chat.saved_message.manage", { tenantId: tko_actor.tenantId, type: "saved_messages", id: tko_actor.memberId, visibility: "internal", explicitMemberIds: [tko_actor.memberId] }); return getChatStore().listReminders(tko_actor.tenantId, tko_actor.memberId, tko_includeCompleted); }
export async function createReminder(tko_actor: PlatformActor, tko_input: { title: string; note?: string | null; reminderAt: Date; messageId?: string | null }, tko_correlationId: string, tko_sessionToken = "") { requireCapability(tko_actor, "chat.saved_message.manage", { tenantId: tko_actor.tenantId, type: "saved_messages", id: tko_actor.memberId, visibility: "internal", explicitMemberIds: [tko_actor.memberId] }); if (tko_input.messageId) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_input.messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); await tko_channelFor(tko_actor, tko_message.channelId); } return tko_scheduleReminder(tko_actor, await getChatStore().createReminder(tko_actor, tko_input, tko_correlationId), tko_sessionToken); }
export async function setReminderStatus(tko_actor: PlatformActor, tko_reminderId: string, tko_status: "open" | "done" | "dismissed", tko_correlationId: string, tko_sessionToken = "") { requireCapability(tko_actor, "chat.saved_message.manage", { tenantId: tko_actor.tenantId, type: "saved_messages", id: tko_actor.memberId, visibility: "internal", explicitMemberIds: [tko_actor.memberId] }); const tko_existing = (await getChatStore().listReminders(tko_actor.tenantId, tko_actor.memberId, true)).find(tko_reminder => tko_reminder.id === tko_reminderId); const tko_result = await getChatStore().setReminderStatus(tko_actor, tko_reminderId, tko_status, tko_correlationId); if (tko_sessionToken && tko_existing?.scheduleCronTaskUid && tko_status !== "open") await deleteHeartbeatJob(tko_existing.scheduleCronTaskUid, tko_sessionToken).catch(() => undefined); return tko_result; }
export async function snoozeReminder(tko_actor: PlatformActor, tko_reminderId: string, tko_reminderAt: Date, tko_correlationId: string, tko_sessionToken = "") { requireCapability(tko_actor, "chat.saved_message.manage", { tenantId: tko_actor.tenantId, type: "saved_messages", id: tko_actor.memberId, visibility: "internal", explicitMemberIds: [tko_actor.memberId] }); if (tko_reminderAt.getTime() <= Date.now()) throw new Error("CHAT_REMINDER_SNOOZE_MUST_BE_FUTURE"); return tko_scheduleReminder(tko_actor, await getChatStore().snoozeReminder(tko_actor, tko_reminderId, tko_reminderAt, tko_correlationId), tko_sessionToken); }
export async function upsertPushSubscription(tko_actor: PlatformActor, tko_input: { endpoint: string; p256dh: string; auth: string; userAgent?: string | null }, tko_correlationId: string) { requireCapability(tko_actor, "chat.saved_message.manage", { tenantId: tko_actor.tenantId, type: "saved_messages", id: tko_actor.memberId, visibility: "internal", explicitMemberIds: [tko_actor.memberId] }); return getChatStore().upsertPushSubscription(tko_actor, tko_input, tko_correlationId); }
export async function mentionedMessages(tko_actor: PlatformActor) { const tko_channels = await listChannels(tko_actor); const tko_messages = (await Promise.all(tko_channels.map(tko_channel => getChatStore().listMessages(tko_actor.tenantId, tko_channel.id)))).flat().filter(tko_message => tko_message.body.mentions?.includes(tko_actor.memberId)).sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime()); const tko_authorMap = await tko_authors(tko_actor); return tko_messages.slice(0, 100).map(tko_message => { const tko_channel = tko_channels.find(tko_item => tko_item.id === tko_message.channelId)!; return { message: { ...tko_message, author: tko_authorMap.get(tko_message.authorMemberId) }, channel: { id: tko_channel.id, name: tko_channel.name, kind: tko_channel.kind } }; }); }
export async function pinnedMessages(tko_actor: PlatformActor, tko_channelId: string) { await tko_channelFor(tko_actor, tko_channelId); const tko_pins = await getChatStore().listPinnedMessages(tko_actor.tenantId, tko_channelId); const tko_authorMap = await tko_authors(tko_actor); const tko_entries = await Promise.all(tko_pins.map(async tko_pin => { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_pin.messageId); return tko_message ? { pin: tko_pin, message: { ...tko_message, author: tko_authorMap.get(tko_message.authorMemberId) } } : null; })); return tko_entries.filter((tko_entry): tko_entry is NonNullable<typeof tko_entry> => Boolean(tko_entry)); }
export async function saveMessage(tko_actor: PlatformActor, tko_messageId: string, tko_input: SaveMessageInput, tko_correlationId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); await tko_channelFor(tko_actor, tko_message.channelId); requireCapability(tko_actor, "chat.saved_message.manage", { tenantId: tko_actor.tenantId, type: "message", id: tko_messageId, visibility: "internal" }); return getChatStore().saveMessage(tko_actor, tko_messageId, tko_input, tko_correlationId); }
export async function forwardMessage(tko_actor: PlatformActor, tko_input: { messageId: string; targetChannelId: string; note?: string }, tko_correlationId: string) {
  const tko_source = await getChatStore().getMessage(tko_actor.tenantId, tko_input.messageId);
  if (!tko_source || tko_source.deletedAt) throw new Error("CHAT_MESSAGE_NOT_FOUND");
  const tko_sourceChannel = await tko_channelFor(tko_actor, tko_source.channelId);
  const tko_targetChannel = await tko_channelFor(tko_actor, tko_input.targetChannelId);
  requireCapability(tko_actor, "chat.message.send", tko_targetChannel);
  const tko_sourceLabel = tko_sourceChannel.name ? `#${tko_sourceChannel.name}` : "một tin nhắn trực tiếp";
  const tko_forwardBody = [tko_input.note?.trim(), `Chuyển tiếp từ ${tko_sourceLabel}`, tko_source.body.text].filter(Boolean).join("\n\n");
  return getChatStore().sendMessage(tko_actor, {
    tenantId: tko_actor.tenantId,
    channelId: tko_targetChannel.id,
    authorMemberId: tko_actor.memberId,
    clientMessageId: crypto.randomUUID(),
    body: { type: "text", text: tko_forwardBody, mentions: [] },
    attachments: tko_source.attachments,
  }, tko_correlationId);
}
export async function togglePin(tko_actor: PlatformActor, tko_messageId: string, tko_correlationId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); const tko_channel = await tko_channelFor(tko_actor, tko_message.channelId); requireCapability(tko_actor, "chat.channel.manage", tko_channel); return getChatStore().togglePin(tko_actor, tko_messageId, tko_correlationId); }
export async function search(tko_actor: PlatformActor, tko_query: string, tko_filters?: ChatSearchFilters) { requireCapability(tko_actor, "chat.search", { tenantId: tko_actor.tenantId, type: "search", id: "chat", visibility: "internal" }); const tko_results = await getChatStore().search(tko_actor.tenantId, tko_actor.memberId, tko_query, tko_filters); const tko_authorMap = await tko_authors(tko_actor); return tko_results.map(tko_result => ({ ...tko_result, message: { ...tko_result.message, author: tko_authorMap.get(tko_result.message.authorMemberId) } })); }
export async function message(tko_actor: PlatformActor, tko_messageId: string) {
  const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId);
  if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND");
  await tko_channelFor(tko_actor, tko_message.channelId);
  requireCapability(tko_actor, "chat.message.read", { tenantId: tko_actor.tenantId, type: "channel", id: tko_message.channelId, visibility: "internal" });
  const tko_authorMap = await tko_authors(tko_actor);
  return { ...tko_message, author: tko_authorMap.get(tko_message.authorMemberId) };
}
export async function memberNotificationPrefs(tko_actor: PlatformActor) { requireCapability(tko_actor, "chat.notification.manage", { tenantId: tko_actor.tenantId, type: "notification_prefs", id: tko_actor.memberId, visibility: "internal", explicitMemberIds: [tko_actor.memberId] }); return getChatStore().getMemberNotificationPrefs(tko_actor.tenantId, tko_actor.memberId); }
export async function updateMemberNotificationPrefs(tko_actor: PlatformActor, tko_prefs: MemberNotificationPrefs, tko_correlationId: string) { requireCapability(tko_actor, "chat.notification.manage", { tenantId: tko_actor.tenantId, type: "notification_prefs", id: tko_actor.memberId, visibility: "internal", explicitMemberIds: [tko_actor.memberId] }); return getChatStore().setMemberNotificationPrefs(tko_actor, tko_prefs, tko_correlationId); }
export async function listMentionableTeams(tko_actor: PlatformActor) { requireCapability(tko_actor, "chat.message.send", { tenantId: tko_actor.tenantId, type: "team_directory", id: "mention-teams", visibility: "internal" }); return getChatStore().listListableTeams(tko_actor.tenantId); }
export async function linkWorkItem(tko_actor: PlatformActor, tko_messageId: string, tko_workItemId: string, tko_correlationId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); requireCapability(tko_actor, "chat.message.send", { tenantId: tko_actor.tenantId, type: "message", id: tko_messageId, visibility: "internal" }); return getChatStore().linkWorkItem(tko_actor, tko_messageId, tko_workItemId, tko_correlationId); }
export async function attachmentUrl(tko_actor: PlatformActor, tko_messageId: string, tko_attachmentId: string) { const tko_message = await getChatStore().getMessage(tko_actor.tenantId, tko_messageId); if (!tko_message) throw new Error("CHAT_MESSAGE_NOT_FOUND"); await tko_channelFor(tko_actor, tko_message.channelId); const tko_attachment = tko_message.attachments.find(tko_item => tko_item.id === tko_attachmentId); if (!tko_attachment) throw new Error("CHAT_ATTACHMENT_NOT_FOUND"); return { url: await getTenantAttachmentDownloadUrl(tko_actor, tko_attachment) }; }
export async function setPresence(tko_actor: PlatformActor, tko_status: "online" | "away" | "offline") { const tko_redis = getRedisAdapter(); const tko_limit = await tko_redis.takeRateLimit(`chat:presence:${tko_actor.tenantId}:${tko_actor.memberId}`, 30, 60_000); if (!tko_limit.allowed) throw new Error("CHAT_PRESENCE_RATE_LIMITED"); const tko_payload = { memberId: tko_actor.memberId, status: tko_status, expiresAt: Date.now() + 90_000 }; await tko_redis.setCache(`chat:presence:${tko_actor.tenantId}:${tko_actor.memberId}`, JSON.stringify(tko_payload), 90_000); await tko_redis.publishTenant({ tenantId: tko_actor.tenantId, eventId: crypto.randomUUID(), eventType: "chat.presence_updated.v1", payload: tko_payload }); return tko_payload; }
export async function presence(tko_actor: PlatformActor, tko_channelId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); const tko_redis = getRedisAdapter(); const tko_statuses = await Promise.all(tko_channel.memberIds.map(async tko_memberId => { const tko_cached = await tko_redis.getCache(`chat:presence:${tko_actor.tenantId}:${tko_memberId}`); if (!tko_cached) return { memberId: tko_memberId, status: "offline" as const, expiresAt: 0 }; try { const tko_value = JSON.parse(tko_cached); return { memberId: tko_memberId, status: tko_value.status === "away" || tko_value.status === "online" ? tko_value.status : "offline", expiresAt: Number(tko_value.expiresAt) || 0 } as const; } catch { return { memberId: tko_memberId, status: "offline" as const, expiresAt: 0 }; } })); return tko_statuses; }
export async function setTyping(tko_actor: PlatformActor, tko_channelId: string, tko_isTyping: boolean) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); requireCapability(tko_actor, "chat.message.send", tko_channel); const tko_redis = getRedisAdapter(); const tko_limit = await tko_redis.takeRateLimit(`chat:typing:${tko_actor.tenantId}:${tko_actor.memberId}`, 120, 60_000); if (!tko_limit.allowed) throw new Error("CHAT_TYPING_RATE_LIMITED"); const tko_payload = { channelId: tko_channelId, memberId: tko_actor.memberId, isTyping: tko_isTyping, expiresAt: Date.now() + 8_000 }; await tko_redis.setCache(`chat:typing:${tko_actor.tenantId}:${tko_channelId}:${tko_actor.memberId}`, JSON.stringify(tko_payload), 8_000); await tko_redis.publishTenant({ tenantId: tko_actor.tenantId, eventId: crypto.randomUUID(), eventType: "chat.typing_updated.v1", payload: tko_payload }); return tko_payload; }
export async function typing(tko_actor: PlatformActor, tko_channelId: string) { const tko_channel = await tko_channelFor(tko_actor, tko_channelId); const tko_redis = getRedisAdapter(); const tko_indicators = await Promise.all(tko_channel.memberIds.filter(tko_memberId => tko_memberId !== tko_actor.memberId).map(async tko_memberId => { const tko_cached = await tko_redis.getCache(`chat:typing:${tko_actor.tenantId}:${tko_channelId}:${tko_memberId}`); if (!tko_cached) return null; try { const tko_value = JSON.parse(tko_cached); return tko_value.isTyping && Number(tko_value.expiresAt) > Date.now() ? { channelId: tko_channelId, memberId: tko_memberId, isTyping: true, expiresAt: Number(tko_value.expiresAt) } : null; } catch { return null; } })); return tko_indicators.filter((tko_value): tko_value is NonNullable<typeof tko_value> => Boolean(tko_value)); }
export function seedDemo(tko_actor: PlatformActor) { return getChatStore().seedDemo(tko_actor); }
